### ISSUE TITLE
Can not create empty JSON schema

### ISSUE THREAD

**Issue by lasseebert** [dry-rb/dry-validation#101]
I would expect the following to create an empty JSON schema (a schema that does not accept any input), but it fails:

```
[1] pry(main)> require "dry-validation"
=> true
[2] pry(main)> Dry::Validation.JSON {}
NoMethodError: undefined method `each_with_object' for nil:NilClass
from /usr/local/lib/ruby/gems/2.3.0/gems/dry-types-0.7.1/lib/dry/types/hash.rb:7:in `schema'
```

Just wanted to hear if this is expected before diving more into it. I tested this in `master`.

The use case is a default schema for endpoints in a JSON api application.

**Comment by solnic** [comment]
What would it do if it's empty? This should crash like that obviously so I will improve it but w/o rules it will just be a no-op that will pass through the input.

**Comment by lasseebert** [comment]
Thanks @solnic

One thought: Since JSON schemas also act as a "white lister" it might be more consistent to always return a result with empty output on an empty JSON schema. 

It might be a wierd edge-case, but I like an empty schema better than a nil value :-)

Please tell me if I can do anything to help with the implementation, though I'm pretty new to this awesome gem.

**Comment by solnic** [comment]
When this is fixed, an empty schema with sanitizer turned on will return an empty hash. I can see how this can be useful.

**Comment by solnic** [comment]
I reported an issue in dry-types since it's actually a bug there.

**Comment by lasseebert** [comment]
Thanks for leading me in the right direction.

I've opened a PR in dry-types that fixes the problem for me. Closing this issue since it's an issue in dry-types.
