### ISSUE TITLE
Support handling empty arrays in form schemas

### ISSUE THREAD

**Issue by timriley** [dry-rb/dry-validation#102]
In HTML forms it seems there’s no way to properly submit an empty array. So instead of some blank value being submitted with the key, it just doesn’t get submitted at all. And unlike checkboxes with the hidden input you can place above them to ensure a default “off” value is submitted, with arrays there seem to be no such workarounds.

For our app, this is the best I could come up with for a schema where you really do want the array’s key to be present, so its nested validations can run:

```ruby
schema = Dry::Validation.Form do
  key(:contributors).each do
    schema do
      key(:contributor_id).required(:int?)
    end
  end

  configure do
    def call(input)
      input = input.dup
      input["contributors"] = [] unless input.key?("contributors")

      super(input)
    end
  end
end

input = {}
result = schema.(input)
# => #<Dry::Validation::Result output={:contributors=>[]} messages={}>
```

It would be nice if we could somehow support this kind of use case a little bit better with the form schemas.

**Comment by solnic** [comment]
This will be solved once we have support for types with default values. Then we can tweak `Form::Array` to be a default type having `[]` as the fallback value when `nil` was passed.

**Comment by timriley** [comment]
This sounds good. For our usage (which I think is a fairly reasonable approach for handling empty arrays in forms), I think we'd need https://github.com/dry-rb/dry-types/issues/76 to be in place alongside this.

**Comment by solnic** [comment]
Closing this one since all pieces are done
