### ISSUE TITLE
Discussion: improve hints

### ISSUE THREAD

**Issue by mrbongiolo** [dry-rb/dry-validation#104]
Right now `dry-validation` create hints in some cases, honestly I'm not sure when it happen.
This kind of behavior goes against the general explicit behavior or `dry-v`. 

Sample:
```ruby
TheSchema = Dry::Validation.Schema do
  required(:name).value(:str?, :filled?, :gt?: 2, :cant_be_a_john?)
end

TheSchema.(name: "")

# messages={:name=>["name is missing", "name has to be gt 2", "sorry we don't like Johns"]}
```

Some apps would like this behavior, but some wont, probably some need this behavior only for a specific key or schema.

We could have a `config.hints` option that could be used for the entire schema. The options could be `true | false`, or maybe a "level" of hinting like: `[:all, :type_check, :custom_predicates, :builtin_predicates]`, not sure if this would be possible or even viable.

Another way to set the hints could be per key. Something like: `required(:name).value(:str?, :filled?, :gt?: 2, :cant_be_a_john?).hints(:cant_be_a_john?)`.

**Comment by solnic** [comment]
This should be done prior 1.0

**Comment by AMHOL** [comment]
I was always under the impression that hints would be stored under a different key than actual error messages, would it not be simpler to just do

**Comment by solnic** [comment]
@AMHOL yeah it crossed my mind too but I thought it's gonna be way too different from "typical validation libs" and people may get confused, now I'm on the fence heh

**Comment by AMHOL** [comment]
@solnic it's already way too different from typical validation libs, I see that as a positive :wink:

**Comment by mrbongiolo** [comment]
I like @AMHOL suggestion, wouldn't that be easier also? What about: `messages(:hints)`?

**Comment by solnic** [comment]
Yeah this is the downside so we should think this through. It would not
simplify the implementation of the hint compiler BUT it would not require
additional features in the DSL. So pros and cons...
