### ISSUE TITLE
Custom predicate error messages

### ISSUE THREAD

**Issue by tak1n** [dry-rb/dry-validation#114]
Currently for custom predicate messages only `%{value}` is available.
For custom predicates which take 2 arguments (value and maybe a numeric limit etc) there is no way to output the limit which was used for that predicate.

**Comment by tak1n** [comment]
What I could come up with now: https://github.com/tak1n/dry-validation/commit/f061a13595978afc76c88aef0e0c1b2ad320ef83

Not sure if there is a better solution to that, would also be cool to specify the argument by the same name  which it got in the custom predicate.
My knowledge about dry-v is still quite limited so not sure if we can get it somehow via: http://ruby-doc.org/core-2.2.0/Method.html#method-i-parameters

**Comment by solnic** [comment]
Please do open a PR and we can discuss the approach there.

**Comment by jeremyf** [comment]
@tak1n Can this issue be closed?

**Comment by fran-worley** [comment]
@jeremyf not yet. The PR was accidentally merged and then reversed. We are looking at ways of making the param names available to avoid names like arg0. Please see the open PR in dry-logic and issue #165 for more details.

**Comment by fran-worley** [comment]
This has now been addressed and a passing spec added via https://github.com/dry-rb/dry-validation/commit/1afd86eb0b8ed2f6c59ad2f580ec86681c39321e
