### ISSUE TITLE
Schema: Whitelisting

### ISSUE THREAD

**Issue by jodosha** [dry-rb/dry-validation#115]
Hello 😄  I expected that `Result#output` would whitelist and coerce the input.

```ruby
require 'bundler/setup'
require 'dry-validation'

schema = Dry::Validation.Schema do
  key(:foo) { filled? }
  key(:num) { type?(Integer) & eql?(23) }

  key(:bar).schema do
    key(:baz) { filled? }
  end
end

result = schema.call(
  foo:     'ok',
  num:     23,
  unknown: 'no',
  bar: {
    baz: 'yo',
    wat: 'oh'
  }
)

puts 'Expected'
puts Hash[foo: 'ok', num: 23, bar: { baz: 'yo' }]

puts "\n"

puts 'Actual'
puts result.output

__END__

Expected
{:foo=>"ok", :num=>23, :bar=>{:baz=>"yo"}}

Actual
{:foo=>"ok", :num=>23, :unknown=>"no", :bar=>{:baz=>"yo", :wat=>"oh"}}
```

I've noticed that `Dry::Validation.Form` works as expected, any reason why this isn't true for `Schema` as well? Thank you! 😄

**Comment by solnic** [comment]
Plain `Schema` has input processor turned off, you can do that via `configure { config.input_processor = :sanitizer }`. In case of `Form` and `JSON`, apart from sanitization, coercion is applied too.

**Comment by jodosha** [comment]
@solnic Thanks for the quick reply! Any reason why that isn't turned on by default?

**Comment by solnic** [comment]
I believe having a plain schema without input processing can be valuable in some cases, but if it's unexpected we should turn it on by default. Coercion won't be available though as we don't have a generic coercer, hence `Form` and `JSON` have their custom coercion logic.

**Comment by jodosha** [comment]
@solnic Yeah that makes sense. I've turned it like this:

```ruby
    module ClassMethods
      def validations(&blk)
        schema = Dry::Validation.__send__(_schema_type, build: false, &blk)
        schema.configure(&_schema_config)

        self.schema = schema.new
      end

      private

      def _schema_type
        :Schema
      end

      def _schema_config
        lambda do |config|
          config.input_processor = :sanitizer
        end
      end
    end
```

So please don't remove `build: false` 😉 

---

I'm closing this. Thanks!

**Comment by solnic** [comment]
@jodosha `build: false` is a feature used internally too, it's not going away :)
