### ISSUE TITLE
Form: required(:foo).maybe(:empty?) fails unexpectedly

### ISSUE THREAD

**Issue by jodosha** [dry-rb/dry-validation#125]
```ruby
require 'bundler/setup'
require 'dry-validation'

form = Dry::Validation.Form do
  required(:foo).maybe(:empty?)
end

result = form.call('foo' => {})
puts result.success?
puts result.messages[:foo].inspect

__END__

Expected:
  true
  nil

Actual:
  false
  ["is missing", "must be empty"]
```

**Comment by jodosha** [comment]
Similar error:

```ruby
result = form.call('foo' => ['23'])

__END__

Actual:
  false
  ["is missing", "must be empty"]
```

**Comment by solnic** [comment]
Just like with `maybe(:none?)` this actually makes no sense as `maybe` means that something can be nil. In Form we only coerce an empty string to a nil but there's an idea to coerce empty arrays into nil as well. I believe you want `required(:foo).value(:hash?, :empty?)` here, ie:

```
irb(main):002:0> Dry::Validation.Form { required(:foo).value(:hash?, :empty?) }.(foo: {})
=> #<Dry::Validation::Result output={:foo=>{}} messages={}>
irb(main):003:0> Dry::Validation.Form { required(:foo).value(:hash?, :empty?) }.(foo: { a: 1 })
=> #<Dry::Validation::Result output={:foo=>{:a=>1}} messages={:foo=>["must be empty"]}>
```

**Comment by timriley** [comment]
Thanks for the reminder about empty array coercion. I'll try PR that one today. I'd like to do empty hash coercion too!

**Comment by timriley** [comment]
FYI, I've just pushed up https://github.com/dry-rb/dry-types/pull/88, which is not quite exactly what @solnic mentioned above: it coerces blank strings into arrays or hashes when those form values are handled by dry-validation form schema keys that are typed as arrays or hashes.

AFAIK there's actually no way to submit an empty array or object in a regular form post (that PR above is a way to make it possible when you explicitly want it), so I'm not sure we even need to do any extra work to coerce them to nil..

**Comment by fran-worley** [comment]
See #177 which raises errors when illogical schemas are created using macros and updates the specs to reflect.

**Comment by solnic** [comment]
This is now improved via #177
