### ISSUE TITLE
Feature request: make .schema to accept objects that respond to #schema

### ISSUE THREAD

**Issue by jodosha** [dry-rb/dry-validation#136]
I have the following two validators:

```ruby
class AddressValidator
  include Hanami::Validations

  validations do
    required(:city).filled
  end
end

class CustomerValidator
  include Hanami::Validations

  validations do
    required(:name).filled
    required(:address).schema(AddressValidator.schema)
  end
end
```

It would be neat to have the following syntax instead:

```ruby
    required(:address).schema(AddressValidator)
```

Can `.schema` check if the given object respond to `#schema` and eventually use it? Thanks!

**Comment by AMHOL** [comment]
Seems reasonable to me, marking as help wanted but will try and get to it soon if nobody picks it up

**Comment by ttdonovan** [comment]
@jodosha @AMHOL I think my pull request provides a solution to the problem you want to address. Take a look and I'm open to any feedback.

**Comment by ttdonovan** [comment]
@jodosha @AMHOL it appears that this pull request has been merged so this issue could be closed.

**Comment by jeremyf** [comment]
@jodosha I can verify that this is working in our application. https://github.com/ndlib/sipity/blob/99cfed77182444eda4ba680b21f52e9ef6a65928/app/data_generators/sipity/data_generators/submission_window_schema.rb#L14-L15

**Comment by AMHOL** [comment]
Thanks @ttdonovan @jeremyf
