### ISSUE TITLE
`max_size?` errors not being generated with .required or .maybe macro and block syntax

### ISSUE THREAD

**Issue by dgollahon** [dry-rb/dry-validation#139]
This does not work as expected (required)

```ruby
schema = Dry::Validation.Schema { key(:foo).required { max_size?(2) } }
p schema.call(foo: 'bar').messages
# Expected: { foo: ["size cannot be greater than 2"] }
# Actual:   {}
```

Nor does this (maybe)

```ruby
schema = Dry::Validation.Schema { key(:foo).maybe { max_size?(2) } }
p schema.call(foo: 'bar').messages
# Expected: { foo: ["size cannot be greater than 2"] }
# Actual:   {}
```

But this works (no required)

```ruby
schema = Dry::Validation.Schema { key(:foo) { max_size?(2) } }
p schema.call(foo: 'bar').messages
# Expected: { foo: ["size cannot be greater than 2"] }
# Actual:   { foo: ["size cannot be greater than 2"] }
```

As does (non-block style)

```ruby
schema = Dry::Validation.Schema { key(:foo).required(max_size?: 2) }
p schema.call(foo: 'bar').messages
# Expected: { foo: ["size cannot be greater than 2"] }
# Actual:   { foo: ["size cannot be greater than 2"] }
```

**Comment by dgollahon** [comment]
The above was on 0.7.4. I moved to master to see if it still had the issue and it does, but the new syntax seems to work.

```ruby
schema = Dry::Validation.Schema { required(:foo) { max_size?(3) } }
p schema.call(foo: 'bar').messages
# Expected: { foo: ["size cannot be greater than 2"] }
# Actual:   { foo: ["size cannot be greater than 2"] }
```

**Comment by solnic** [comment]
These macros don't support blocks at all, only a list of predicates. We can easily add support for blocks though. BTW `key` is now `required` and `required` is now `filled` so `key(:foo).required` becomes `required(:foo).filled`.

**Comment by jeremyf** [comment]
@dgollahon By your last comment, it appears much of this may be resolved. Is that the case? Also @solnic are you suggesting that the given macros support blocks?

**Comment by dgollahon** [comment]
@jeremyf It certainly explains the confusing behavior.

It seems like it would be great to have block support for the macros (or maybe only have block OR hash support as it's somewhat confusing what the differences are) or at least document clearly that macros remove the normal block support.

**Comment by solnic** [comment]
macros should support blocks, I'll add that in next release
