### ISSUE TITLE
Feature request: custom predicate inheritance for nested schemas

### ISSUE THREAD

**Issue by jodosha** [dry-rb/dry-validation#140]
Consider the follow use case: register a domain.

The following syntax is NOT allowed, but it would be nice to have:

```ruby
schema = Dry::Validation.Schema do
  configure do
    config.messages_file = '...'

    def email?(current)
      current.include?('@')
    end
  end

  required(:technical_contact).schema do
    required(:email).filled(:email?)
  end

  required(:administrative_contact).schema do
    required(:email).filled(:email?)
  end
end
```

We have configured the top-level schema to include the `email?` predicate. Nested schemas (`:technical_contact` and `:administrative_contact`) don't inherit that configuration and raise an `ArgumentError`: `+email?+ is not a valid predicate name`.

**Comment by AMHOL** [comment]
@jodosha please see the commit referencing this issue, you can configure a global predicates container, I'm not keen on defining methods in the configure block myself, and think the intention was for one-off cases, will the custom predicate container suffice for your needs?

**Comment by jodosha** [comment]
@AMHOL Thanks for your reply!

> will the custom predicate container suffice for your needs?

Yes, absolutely. I assumed that DRY philosophy was against [global settings](https://github.com/dry-rb/dry-validation/commit/e080fb8f3938aa4be1052ddf2fbffd9dfcd5192d).

---

Closing this. Thanks!

**Comment by AMHOL** [comment]
Cool, glad that works for you, not really, the intention is that all mutable state happens before the request phase, so you configure your objects on start-up and then avoid mutable state during the request phase, that way multi-threading isn't an issue
