### ISSUE TITLE
Undefined method 'visit_xor' raised when using xor operator in rule

### ISSUE THREAD

**Issue by kaushikvinaytg** [dry-rb/dry-validation#144]
Following scenario seems to throw an error
```ruby
  require 'dry-validation'

  BudgetSchema = Dry::Validation.Schema do
    key(:total_budget).maybe(:int?)
    key(:daily_budget).maybe(:int?)
    rule(total_or_daily: [:total_budget, :daily_budget]) do |total_budget, daily_budget|
      total_budget.filled? ^ daily_budget.filled?
    end
  end

  BudgetSchema.call({total_budget: 100, daily_budget: 10})
```

throws an error 

dry-validation-0.7.4/lib/dry/validation/error_compiler.rb:30:in `visit': undefined method `visit_xor' for #<Dry::Validation::ErrorCompiler::Input:0x007faee927aa98> (NoMethodError)
 Did you mean?  visit
                visit_error
                visit_attr
                visit_el
                visit_result
                visit_val
                visit_set
                visit_key

**Comment by AMHOL** [comment]
Thanks for reporting this @kaushikvinaytg

**Comment by fran-worley** [comment]
@kaushikvinaytg I've just checked this with master and can't replicate it (see below). Can you double check this with master? You'll need to use `required` instead of `key`.

```ruby
schema = Dry::Validation.Schema do
  configure do
    def self.messages
      Messages.default.merge(
        en: { errors: { total_or_daily: 'you must fill one or the other!' } }
      )
   end
  end

  required(:total_budget).maybe(:int?)
  required(:daily_budget).maybe(:int?)
  rule(total_or_daily: [:total_budget, :daily_budget]) do |total_budget, daily_budget|
    total_budget.filled? ^ daily_budget.filled?
  end
end

schema.(total_budget: nil, daily_budget: 100).messages[:total_or_daily] => nil
schema.(total_budget: 105, daily_budget: 100).messages[:total_or_daily] => 'you must fill one or the other!'
```

**Comment by dNitza** [comment]
@kaushikvinaytg I also came across this issue just now and it turned out that I hadn't defined an error message for my custom rule.

**Comment by kaushikvinaytg** [comment]
@fran-worley @dNitza Thank you. I realised was passing error messages in yml file in a wrong format, now its working after correcting my mistake, but regardless of `required`, `key` or `optional`, man I feel so stupid. Will close the issue now.

**Comment by solnic** [comment]
Hmm I'd consider this to be a bug, this shouldn't crash like that because you forgot to add a custom message. Re-opening...

**Comment by solnic** [comment]
This is fixed on master, here's a complete example (notice that you must add a custom message in order to make it meaningful):

``` ruby
require 'dry-validation'

BudgetSchema = Dry::Validation.Schema do
  configure do
    def self.messages
      Dry::Validation::Messages.default.merge(
        en: {
          errors: {
            total_or_daily: 'either total_budget or daily_budget must be filled'
          }
        }
      )
    end
  end

  required(:total_budget).maybe(:int?)
  required(:daily_budget).maybe(:int?)

  rule(total_or_daily: [:total_budget, :daily_budget]) do |total_budget, daily_budget|
    total_budget.filled? ^ daily_budget.filled?
  end
end

puts BudgetSchema.call({total_budget: 100, daily_budget: 10}).messages.inspect
# {:total_or_daily=>["either total_budget or daily_budget must be filled"]}

puts BudgetSchema.call({total_budget: 100, daily_budget: nil}).messages.inspect
# {}

puts BudgetSchema.call({total_budget: nil, daily_budget: 10}).messages.inspect
# {}
```
