### ISSUE TITLE
Extensive integration test suite

### ISSUE THREAD

**Issue by jodosha** [dry-rb/dry-validation#146]
While working on integration between `dry-v` and `hanami-v`, I wrote a test suite for all the builtin predicates.

It tests for missing, nil, blank strings, string values (eg. `"1"`), expected Ruby types (eg `1`), unexpected types (eg. a hash when an int is expected).

All these values are used to test all the six combinations of `required`/`optional` (for keys) and `value`, `filled`, `maybe` macros (for values).

All these combinations are tested both for `Schema` and `Form`.

This results in almost 3000 assertions which run in 3 seconds.

---

This extensive testing helped to spot issues in `dry-v` (and related gems) that I reported here.

Each time you folks apply a fix for these issues, I run `bundle update` and get the fixes (thank you!), but also new failures.

These new failures deserve new tickets. But that will make the feedback process really slow. It will take days to spot the new errors and a week to fix. If `dry-v` codebase will include these tests, feedback will become immediate and hopefully no broken code will be pushed.

**I believe that the `hanami-v` tests really belong here.**

I can take care of open a PR to add them here. But because it's a huge work, before to dive into it, I want to be sure that it will be accepted by you.

WDYT? @solnic @timriley @AMHOL Thank you!

**Comment by timriley** [comment]
This sounds good to me. It's true that these tests would be testing logic that is in other gems (dry-logic and dry-types), but dry-validation is one of the big places where these things work together in integration, and makes sense as a repository for these high-level integration tests.

**Comment by solnic** [comment]
I agree. It would be great to get these specs merged in here. It's great and very helpful that you worked on these tests! One thing that we should improve is to have a shared suite that is executed against different types of schemas. Right now it's so-so as we have some tests for Form and some for plain Schema w/o coercions. There are a lot of tests that can be shared to avoid duplication.
