### ISSUE TITLE
Make predicates building blocks for custom predicates

### ISSUE THREAD

**Issue by jodosha** [dry-rb/dry-validation#156]
In the example below we want to reuse builtin predicates like `bool?` and `true?` as building blocks for custom predicates.

```ruby
require 'bundler/setup'
require 'dry-validation'

schema = Dry::Validation.Schema do
  configure do
    def self.messages
      super.merge(en: { accepted?: 'must be accepted' })
    end

    # alternative 1
    def accepted?(current)
      bool? & true?
    end

    # or

    # alternative 2
    def accepted?(current)
      current.bool? & current.true?
    end
  end

  required(:terms).value(:accepted?)
end
```

---

Another potential improvement would be to reuse custom predicates as building blocks for other custom predicates.

```ruby
require 'bundler/setup'
require 'dry-validation'

schema = Dry::Validation.Schema do
  configure do
    def self.messages
      super.merge(en: { foo?: 'must equal "foo"', foobar?: '...' })
    end

    def foo?(current)
      current == "foo"
    end

    def foobar?(current)
      current.foo? || current == "bar"
    end

  required(:name).value(:foobar?)
end
```

**Comment by fran-worley** [comment]
This would be amazing as I use this a lot and end up having to re-write base predicates.

**Comment by solnic** [comment]
You can do this:

``` ruby
def accepted?(current)
  self[:bool?].(current) && self[:true?].(current)
end
```
Although in this specific case just using `required(:terms).value(:true?)` should be enough, I think.

**Comment by fran-worley** [comment]
@solnic will `required(:terms).value(:true?)` coerce from a string correctly?

**Comment by solnic** [comment]
Yes it will, once you add:

``` ruby
true?: 'form.true',
false?: 'form.false',
```
to [this class](https://github.com/dry-rb/dry-validation/blob/master/lib/dry/validation/input_processor_compiler/form.rb#L7)

:)

**Comment by fran-worley** [comment]
@solnic nice work on your OSS holiday! I'll raise a PR. Any chance you could look at https://github.com/dry-rb/dry-validation/pull/155 I think its ready to merge

**Comment by solnic** [comment]
@fran-worley I'm still on OSS holidays until end of May actually, I just decided to support your dry-v efforts so that people don't have to wait for too long, esp with hanami integration. I'm only replying to issues/merge PRs, not doing any coding

**Comment by fran-worley** [comment]
@solnic I know I just meant you wrote the code in a comment rather than in a file so you haven't broken your OSS Holiday!

**Comment by solnic** [comment]
OK so I realized this would be an anti-pattern. Predicates are the low-level primitives used in rules. It's fine to use another predicate for negation (ie `empty?` is `!filled?`) but for such cases like `accepted?` it should only check if a given value is one of the values that are treated as "accepted". If this relies on coercion, it should simply check `value == true`.

**Comment by jodosha** [comment]
@solnic In other terms, do you think that predicates should always check for simple conditions, while high level rules are dedicated to complex scenarios?

In some cases a predicate `foo?` can be an abstraction to complex logic that is wrong to be invoked from another predicate, but it's safe to be managed from a rule.

**Comment by solnic** [comment]
@jodosha yes, otherwise you don't know which predicate actually failed :) we actually already have that in place, because dry-logic provides `Rule` objects and they use predicates, and predicates in rules could be plain predicates or other rules too.

Please let me know if you have other examples than `accepted?`, we could expose various APIs for composing complex rules.

**Comment by jodosha** [comment]
@solnic Ok, I'm fine with this clear separation of roles. Thank you. I'm closing this.
