### ISSUE TITLE
Make it possible to specify a predicate that has no args

### ISSUE THREAD

**Issue by solnic** [dry-rb/dry-validation#160]
We need a way for composing predicates even when they don't require any args, so ie this can work:

``` ruby
Dry::Validation.Form do
  configure do
    def activation_code_required?
       # some logic which figures this out and relies on injected deps
       # so it doesn't need any input args
    end
  end

  required(:activation_code).maybe

  rule(new_user: [:activation_code]) do |activation_code|
    activation_code_required?.then(activation_code.filled?)
  end
end
```

/cc @apotonick

**Comment by fran-worley** [comment]
@solnic I think (if I understood @apotonick correctly) we need to go a step further and be able to define rules that don't rely on a key at all. In your example above you are still hooking the rule to a key (:activation_code).

**Comment by solnic** [comment]
`activation_code_required?` doesn't rely on any value, that's what Nick is asking for

**Comment by fran-worley** [comment]
Unless I'm missing something, it does require the key

**Comment by solnic** [comment]
high level rule that doesn't rely on any values makes no sense, the trick is to be able to compose predicates that rely on external information, ie something that queries a db etc.

**Comment by fran-worley** [comment]
@solnic The implementation as you described it would be really useful I have quite a few examples where I have to pass in the value only to ignore it as I don't need it. So I'm saying :+1:

**Comment by solnic** [comment]
This shouldn't be that hard (famous last words) as predicates have -1 arity so we can easily apply them w/o any input, it's a matter of looking what crashes right now and remove/tweak the code which assumes that we always pass in values when applying predicates. I *think* a `Rule::Check` from dry-logic w/o any value evaluator would do the trick, as it would simply apply its predicate with empty args.

**Comment by fran-worley** [comment]
@solnic I'm working on this as we speak. I'll PR when I have something!

**Comment by apotonick** [comment]
Thanks for mentioning me here, this is the only thing we need to release Reform 2.2 (which will define dry-v as default).

**Comment by fran-worley** [comment]
@apotonick is the implementation described here correct? We are still hooking validation to a key, it's just that we will make the input optional.

**Comment by apotonick** [comment]
Oh, you're right @fran-worley ! We need field-less "rules"!

**Comment by fran-worley** [comment]
@apotonick can you provide a use case as I am struggling to come up with one.

**Comment by apotonick** [comment]
In Reform-speak: :stuck_out_tongue_winking_eye: 

```ruby
collection :items do
  # ..
end

validate do
  items.size <= 5 
end
```

**Comment by fran-worley** [comment]
@apotonick but items is a key! I already do this.

```ruby
required(:items) { max_size?(5) }
```

**Comment by apotonick** [comment]
Ehm... eh... uhm....hmm...?

**Comment by fran-worley** [comment]
@apotonick Using Reform 2.1 & dry-V 6.0 I can already do this:

```ruby
class CheckboxForm < Reform::Form
  collection :field_options, form: ::Fields::FieldOptionForm

   #used to validate that at least one field option exists
   validation :defaults do
     key(:field_options){ |field_options| field_options.min_size?(1) }
  end
end
```

**Comment by apotonick** [comment]
I can't come up with an example anymore where the validation doesn't have a field... :smirk: 

Anyways, is that about right? https://github.com/apotonick/reform/blob/38155cbfde48e2dde10aad437d7b9bfc8383830c/test/errors_test.rb#L31

**Comment by fran-worley** [comment]
@apotonick  Looks right to me, in the Reform docs it might be helpful to point to this page: http://dry-rb.org/gems/dry-validation/custom-predicates/ which has a useful example for reusing custom predicates.

**Comment by solnic** [comment]
done via https://github.com/dry-rb/dry-validation/pull/180
