### ISSUE TITLE
Register custom types

### ISSUE THREAD

**Issue by jodosha** [dry-rb/dry-validation#161]
Let's start from an example of what I'm looking for:

```ruby
class Url
  def initialize(url)
    @url = url.to_s
  end

  def ssl?
    @url.start_with?('https')
  end

  def to_str
    @url
  end
end

form = Dry::Validation.Form do
  configure do
     def secure?(current)
       puts current.class # => I WISH it was `Url` but is `String` instead.
       current.ssl?
     end
  end

  required(:website) { type?(Url) & secure? }
end

result = form.call(website: 'https://example.com')
puts result.success?
puts result.messages
puts result.output.fetch(:website).class
```

In this example, `website` is received as a string from the HTML form.
What I would love to achieve is that it's casted to a `Url` object and I'm able to use the casted value:

  1. for further validations
  2. from `output`

---

### Types must inherit from `dry-types`

The first obstacle to make it to run is that `Url` isn't recognized as a type from `form`, unless I make my class to inherith from `dry-types` classes eg: `Dry::Types::Value`.

I would avoid this. Is there any other way to register a custom type?

---

### Custom types aren't used for coercions

Builtin types are used to coerce incoming form inputs. If we receive a string representing an integer (eg. `"1"`) and we set the type expectation via `type?(Integer)`, that input is coerced into an integer.

That means we can safely compare with other integers (eg. `gt?(0)`) and have the casted value in `Result#output`.

```ruby
form = Dry::Validation.Form do
  required(:number) { type?(Integer) & gt?(0) }
end

result = form.call(number: '1')
puts result.success?                    # => true
puts result.output.fetch(:number).class # => Fixnum
```

**The same policy isn't applied to custom types.**

If we look at the first example above, we see that we expect a `Url` type, but from our form we receive the value as a string. But in this case the `type?(Url)` predicate instead of coerce it (like in the `type?(Integer)` case), it fails.

By running it we can see the discrepancies:

```ruby
result = form.call(website: 'https://example.com')
puts result.success?
puts result.messages
puts result.output.fetch(:website).class # => Url

# Actual:
false
{:website=>["must be Url", "must be secure"]}
String

# Expected
true
{}
Url
```

It's also worth to be mentioned that despite the `"must be secure"` failure, the `secure?` predicate is never invoked.

**Comment by tak1n** [comment]
Regarding to:
```
It's also worth to be mentioned that despite the "must be secure" failure, the secure? predicate is never invoked.
```

i think the reason here was that if previous checks fail the developer gets a list he has to fulfill instead of fixing each validation in a separate step.

**Comment by kwando** [comment]
@jodosha Try adding

```ruby
Dry::Types.register_klass(Url)
```
Before defining your schema

**Comment by jodosha** [comment]
@kwando yay! 🎉 That solves the problem. Thank. You. Very. Much! 💚

**Comment by rocknruby** [comment]
Just in case, it's now called: 
```ruby
Dry::Types.register_class(Url)
```
