### ISSUE TITLE
Custom predicate with more than one input (two or more keys)

### ISSUE THREAD

**Issue by lbrito1** [dry-rb/dry-validation#163]
I've been using dry-validation only for a few days now, but there doesn't seem to be any way of either accessing other keys within the context of a custom predicate or passing more than one value as an input for the custom predicate. This is problematic for me: I'm working on a project with several legacy validations that depend on more than one value.

From what I understand of `Dry::Validation.Schema`, the `input` passed when calling the Schema isn't stored, so it makes sense not to be able to access other `key`s within a custom predicate (although it would be useful in my use case). 

However, I don't see why one shouldn't be able to define a custom predicate with two or more keys, perhaps something like:

`key('id').required(custom_validation?: key('name'))`

Where `custom_validation` would receive two arguments.

Is there any way of achieving something similar to this?

**Comment by solnic** [comment]
Yes there is, we have the concept of high-level rules that can depend on one or more values. See [docs here](http://dry-rb.org/gems/dry-validation/high-level-rules/).

**Comment by lbrito1** [comment]
Hi @solnic , thanks for the quick answer.

I'm familiar with the rules examples in the docs. I'm not sure if the rules are sufficient (or convenient) for my use case though. Consider this SSCCE:

```
schema = Dry::Validation.Schema do
  configure { config.messages_file = './errors.yml' }
  key(:email).maybe

  rule(:email_rule) do
    value(:login).true? > value(:email).filled?
  end
end

puts schema.(login: true, email: nil).messages
```

Using the following error yml:

```
errors:
  rules:
    email_rule: 'my-custom-error'
```

The result of the the last (`value(:email).filled?`) evaluation will be printed: `{:email=>["must be filled"]}`. However, I expected that `'my-custom-error'` would be used. Am I wrong to expect this? Is something wrong in the snippet?

Other than that, AFAIK rules expect operations over predicates. I'm interested in the flexibility of plain ruby syntax, which I know can be done with custom predicates. That's why in my case it would be really useful to be able to use more than one input attribute in a custom predicate.

**Comment by solnic** [comment]
this should be:

``` yaml
en:
  errors:
    email_rule: 'my-custom-error'
```

**Comment by solnic** [comment]
btw we should revisit look up paths for high-level rule messages, it's kinda confusing right now

**Comment by solnic** [comment]
oh and re more than one arg in a predicate, you can use this syntax for now:

``` ruby
schema = Dry::Validation.Schema do
  configure do
    def some_predicate?(email, login)
      # somet stuff
    end
  end

  key(:email).maybe

  rule(email_rule: [:login, :email]) do |login, email|
    login.some_predicate?(email)
  end
end
```

This is obviously a bit confusing, so we're gonna make `some_predicate?(login, email)` work in the next release.
