### ISSUE TITLE
Verbose inequality names

### ISSUE THREAD

**Issue by cllns** [dry-rb/dry-validation#164]
Hi there!

How do you all feel about using more verbose names for the inequality predicates? Right now, I don't think it's clear what `lt?`, `gt?`, `lteq?` and `gteq?` mean. In my opinion, predicate names should be obvious: you shouldn't have to look them up.

So:
`lt?` => `less_than?`
`gt?` => `greater_than?`
`lteq?` => `less_than_or_equal_to?`
`gteq?` => `greater_than_or_equal_to?`

I imagine the problem is less with `lt?` and `gt?` and more with `lteq?` and `gteq?` because the verbose versions of those are quite long.

A couple factors, if you decide you want to do this:

1. Support both the short syntax and the long syntax? That could be confusing.

2. Just `less_than_or_equal?` might be sufficient, without the trailing `_to`. Regardless of which is picked, I imagine many people will mess this up. Therefore, whichever version is *not* chosen should have a specific error saying something like 'You might want to use... instead.` (though maybe Ruby 2.3's did_you_mean will take care of that)

Related: #6

Thanks!

**Comment by solnic** [comment]
Sorry for late reply. 👎 from me on this, mostly because these are rather common abbreviations and long versions are just...well, long :)

Any thoughts on this @AMHOL @timriley @fran-worley ??

**Comment by timriley** [comment]
I think the current names are good and fit with the overall general length of dry-logic's built-in predicate names.

**Comment by fran-worley** [comment]
I'm inclined to agree. We could make the longer ones an alias for the shorter ones for those who prefer the 'full English' ?

**Comment by solnic** [comment]
> We could make the longer ones an alias for the shorter ones for those who prefer the 'full English' ?

We can't support aliases as these identifiers are used for messages too...

**Comment by fran-worley** [comment]
Ohhh yeah. Forgot about that. I guess people will just have to read the docs.

**Comment by AMHOL** [comment]
Yeah I prefer the existing names too

**Comment by solnic** [comment]
OK so I'm gonna close this one
