### ISSUE TITLE
Change the DSL so we have access to the predicate registry

### ISSUE THREAD

**Issue by fran-worley** [dry-rb/dry-validation#165]
See https://github.com/dry-rb/dry-logic/pull/13 for the background to this issue.

To quote @solnic 

> I planned to make an improvement in the dsl part of dry-v so that when we're generating rule ast we also already have access to predicate registry so that we can raise errors when invalid predicates are being defined. When you have a predicate registry, you also have access to arg names, so we could build an ast including names.
>
>Caveat: a schema object (not its class) has predicates too, and we invoke the DSL before a schema instance is created, so it's a chicken-egg issue. We could look into create a predicate registry for the DSL by merging configured Predicates module (class-level access, so we have it before a schema object is created) and somehow extract predicate methods from a schema.
>
>One solution would be to actually change how accessing predicates on a schema object works. Currently we have Schema#[] which can return an existing predicate if it's in the configured class-level registry, or see if a schema implements that predicate, then it returns a Dry::Logic::Predicate instance and pass in method object as the predicate function. Now, the problem here is that we don't have these predicates when DSL is invoked, so now I'm thinking about changing it so that we actually create unbound predicates using method_added hook and bind them when creating a schema instance and passing that registry, with all schema predicates bound to its instance, to the rule compiler.
>
>There are actually nice benefits of doing so, first of all we would have an explicit representation of schema-bound predicates, and we could easily avoid schema rule recompilation when using Schema#with and only recompile rules that have predicates that must be bound to a schema.
>
>So yeah, I feel like this is the way to go with this. It's gonna be a really nice improvement.

**Comment by solnic** [comment]
I feel like we need our own predicate registry object, which is aware of the configured predicates (Schema.config.predicates) and it has access to schema class, so that it can hook into its method_added and auto-add unbound predicates, then it can be used to compile rules, it could expose an interface like `#bind(schema_object)` or something, and also `#[]` to access predicates (required by rule compiler). I believe this is all we need.

**Comment by fran-worley** [comment]
Thanks @solnic. That sounds like a sensible solution. I should have some time this week to put something together.

**Comment by solnic** [comment]
@fran-worley that's great! feel free to send an early-stage PR :)
