### ISSUE TITLE
New user experience: was confused by key behaviour, santizers and schema types

### ISSUE THREAD

**Issue by greghuc** [dry-rb/dry-validation#166]
Hi there,

I just started using dry-validation and dry-types (very cool libraries :-). I thought I'd report some issues that have tripped me up along the way (I'm using github head). I suspect that other new users will run into similar issues, particularly if they're using the libraries as black boxes, and not reading the source code. Might be worth documenting these issues more for the upcoming big releases.

The issues I ran into were:
- Do attribute keys need to be strings or symbols? => It seems that dry-validation accepts both, and outputs validated keys as symbols.
- How are key/value attribute pairs handled that aren't declared in the schema? => After experimentation and source-code reading, I discovered that such key/value pairs would normally be passed through, or filtered out by setting `configure { config.input_processor = :sanitizer }`. This wasn't intuitive.
- I didn't (don't :-) understand the differences between `Dry::Validation.Schema`, `Dry::Validation.Form` and the new `Dry::Validation.JSON` schema => I wanted to use the simplest possible schema to validate input for a JSON API. In the end, I settled on using `Dry::Validation.Schema` with `configure { config.input_processor = :sanitizer }` explicitly set. `Dry::Validation.Form` also worked for validating my parsed JSON input. But I decided not to use it, as I didn't know what other magical things it might be doing.

Example program follows, which I used to explore some of these issues.

```
require 'bundler/setup'

require 'dry-validation'

TestSchema = Dry::Validation.Schema do
  required(:email).filled(:str?)
  required(:message).filled(:str?)
end

SanitizingTestSchema = Dry::Validation.Schema do
  configure { config.input_processor = :sanitizer }

  required(:email).filled(:str?)
  required(:message).filled(:str?)
end

# Shows that no-sanitizer passes through undeclared key/value pairs, and that string keys are converted to symbols
puts TestSchema.call(email: 'test@test.com', 'message': 'I am a message', unexpected_key: '?').output
# => {:email=>"test@test.com", :message=>"I am a message", :unexpected_key=>"?"}

# Shows that sanitizer filters out undeclared key/value pairs, and that string keys are converted to symbols
puts SanitizingTestSchema.call(email: 'test@test.com', 'message': 'I am a message', unexpected_key: '?').output
# => {:email=>"test@test.com", :message=>"I am a message"}
```

**Comment by solnic** [comment]
`Form` and `JSON` have different coercion logic, and they both coerces string keys to symbols. Plain `Schema` has no coercion or sanitization or key-coercion logic. We've been considering turning on sanitization by default though. Still up for a debate.

**Comment by fran-worley** [comment]
Form is actually documented on the website here:

http://dry-rb.org/gems/dry-validation/forms/

We could probably do with a similar page for JSON though...

**Comment by greghuc** [comment]
I think the root issue is understanding the difference in behaviour between the schema types (when do they behave differently?).

A single ‘schema’ page might be enough, covering all the different types, with a table showing the differences.

As a new user, I’ve read the ‘Form Validation’ page several times. The top half of the page seems to describe my use of Dry::Validation.Schema with a sanitiser enabled, so doesn’t uniquely apply to Dry::Validation.Form. I’m presuming the 'Handling Empty Strings’ is describing the custom form coercion.

**Comment by solnic** [comment]
OK let's add more documentation about differences between various schema types :)

**Comment by faucct** [comment]
It is impossible to use `Dry::Validation::Form` coercions while sanitizing the input. I think that the sanitation should be independent from `config.input_processor`.

**Comment by solnic** [comment]
This is straight-forward in dry-schema now. Unknown keys are always rejected, `Params` and `JSON` schemas coerce string keys to symbols. Values are coerced when type specs are used.
