### ISSUE TITLE
Usage of `each` with `included_in?` is not working

### ISSUE THREAD

**Issue by mrbongiolo** [dry-rb/dry-validation#171]
On branch `master`.

Trying to use this:
```ruby
required(:skills).each(included_in?: ['some', 'valid', 'skills'])
```

Throws this:
```
/dry-validation-846c4de4998c/lib/dry/validation/schema/value.rb:36:in `block in each': [:included_in?, ["some", "valid", "skills"]] is not a symbol nor a string (TypeError)
```

**Comment by fran-worley** [comment]
This is not specific to `:included_in?` it affects any predicate with options being used in each.

**Comment by solnic** [comment]
`each` predicates are applied to each element of an array, so this should work I think. We probably accidantely coerce options to array with a splat operator somewhere.

**Comment by fran-worley** [comment]
@solnic it's because `{key: "value"}.to_a` returns `[[:key, "value"]]` so when you splat it to args you get `[:key, "value"]` and that fails in send which expects the first param to always be a symbol.

**Comment by fran-worley** [comment]
and you'll have the same issue with `when` aswell as it works in the same way
