### ISSUE TITLE
Dry.Validation.Form invalid types raise errors from predicates

### ISSUE THREAD

**Issue by fran-worley** [dry-rb/dry-validation#176]
Say we have a form with the following dry-validation form schema:

``` ruby
schema = Dry::Validation.Form do
  required(:foo).filled(format?: /bar/)
end
```

and we call it with an invalid type (e.g. hash, array etc.): `schema.call({ 'foo' => { 'a' => '1' } } )`

We get a type error (quite correctly) from the `format?` predicate.

``` ruby
TypeError:  no implicit conversion of Hash into String
```

This behaviour makes sense when you can control the input (e.g. schema) but not in the case of forms which can be subject to HTML hacks. 

In cases like this, wouldn't it be better to raise a validation error 'must be string'?

**Comment by AMHOL** [comment]
Do you mean implicitly add a `str?` check when we use the format predicate?

Not sure whether it's better to just be explicit in such cases:

```ruby
require 'bundler/inline'

gemfile(true) { gem 'dry-validation', github: 'dry-rb/dry-validation' }

schema = Dry::Validation.Form do
  required(:foo).filled(:str?, format?: /bar/)
end

schema.call('foo' => { 'a' => '1' })
# => #<Dry::Validation::Result output={:foo=>{"a"=>"1"}} messages={:foo=>["must be a string", "is in invalid format"]}>
```

**Comment by fran-worley** [comment]
I just wondered whether it is safer in FORM to assume the predicate `:str?` unless a type predicate is given (e.g. `:int?`) or is that a little magical?

**Comment by solnic** [comment]
You should add a `:str?` if you expect a string, we could add `format` macro to DRY it up

**Comment by fran-worley** [comment]
@solnic if you do that, you'd have to do that for loads of predicates (e.g. `included_in?`, `:size?` etc.) Either we advise people to always declare the type even if its a string, or we assume string unless you declare something else for safety.

**Comment by solnic** [comment]
good point, I'll be adding an explicit `#type` interface to the DSL. This should help us with improving cases like this one.

**Comment by solnic** [comment]
OK so I figured out how this could be handled without getting type-specs involved - we could have a simple system for automatic rule composition based on predicate requirements. In example we could define that `:format?` requires to be used in conjunction with `:str?` so that a macro can do it automatically. It's only a matter of adding an API for defining such requirements. We could easily cover lots of common cases and reduce boilerplate in schema definitions like that.

**Comment by fran-worley** [comment]
Sounds cool. You'd have to be able to define options though as some predicates support more than one type. Also should only apply to form as you have less control over the input.
