### ISSUE TITLE
New type specs no longer coerces form arrays

### ISSUE THREAD

**Issue by fran-worley** [dry-rb/dry-validation#192]
Following #189 we have a use case which no longer validates correctly in forms.

Lets take this example:
```ruby
schema = Dry::Validation.Form do
  configure { config.type_specs = true }
  required(:foo, :array).each(:int?)
end

#expect to pass as it is a form
schema.({ 'foo' => ['3'] })

#actually fails:
#<Dry::Validation::Result output={:foo=>["3"]} messages={:foo=>{0=>["must be an integer"]}}>
```

We need to be able to specify 'nested-types' e.g. 
```
schema = Dry::Validation.Form do
  configure { config.type_specs = true }
  required(:foo, array: :integer)
end
```

**Comment by fran-worley** [comment]
@solnic can we fix this before you release 0.8 ?

**Comment by solnic** [comment]
Yeah it's on my list of things to finish prior the release. I'll do it tomorrow.

**Comment by solnic** [comment]
ps. unless you want to take a stab at it :D

**Comment by fran-worley** [comment]
I doubt I will have time before you want to release so sorry. I wasn't trying to rush you, just didn't want it to slip through the cracks!

**Comment by solnic** [comment]
No worries. It is a quick-fix I'll handle it :)

**Comment by solnic** [comment]
OK so this is fixed and the syntax is `required(:foo, [:int])` after all because a hash would conflict with...the hash syntax, so ie `array: :int` means `array key with int type in a hash` so that was reserved already.
