### ISSUE TITLE
Better way of specifying top-level rules

### ISSUE THREAD

**Issue by solnic** [dry-rb/dry-validation#193]
``` ruby
# when you want a sanity check for input making sure it is a hash
Dry::Validation.Schema do
  input :hash

  required(:foo, :int).maybe(:int?, :even?)
end

# when you want a schema for an array input which checks if it is really an array
# and automatically uses `each` rule for specified schema rules
Dry::Validation.Schema do
  input :array

  required(:foo, :int).maybe(:int?, :even?)
end
```

This should also fix #98

**Comment by jeanfbrito** [comment]
Sorry for the out of time question. But how I can use `input :hash?` nowadays with the updated `dry.schema`?
I need to update old `dry.validation 0.13` to the `dry.schema 1.x` but I cant find nothing that helps me in two weeks.

Could you light my path in some way?

**Comment by timriley** [comment]
@jeanfbrito I recommend you bring this to the forum: https://discourse.dry-rb.org

We don't use GitHub issues for support.
