### ISSUE TITLE
Unit testing schemas

### ISSUE THREAD

**Issue by webPapaya** [dry-rb/dry-validation#197]
Hi, 

I'm currently reviewing dry-validations for usage on one of my projects. One thing I wanted to know is if there is a way to unit test the schema definitions. eg.

```ruby
describe "email" do 
  it "gets validated with presence" do 
    # ????
  end

  it "gets validated with my_custom_predicate (eg. email)" do 
    # ????
  end
end
```

I would then create a couple of unit tests for `my_custom_predicate` and just verify that the schema is using the `my_custom_predicate`. Without testing the schema I would have to test all possibilities of `my_custom_predicate` everywhere it is used. The only thing which matters to my tests is that attribute x is verified with predicate `my_custom_predicate`.

Thanks for your advice.

**Comment by mrbongiolo** [comment]
The `custom_predicate` can be unit tested easily.
You can do something like:
```ruby
expect(MyApp::Predicates[:custom_predicate?].call(valid_input).to eql true
```

I'm not sure how you should test that your schema is using the `custom_predicate` on the right field.

Usually I do test my custom predicates directly where the Schema is using them, usually this is done within an operation, so it makes sense to know that if the operation is called with wrong input I receive the expected errors.
This might be too repetitive for complex schemas, another options is to unit test the Schema, and then test that it's been used where it should be.

**Comment by solnic** [comment]
Just check behavior, absolutely no need to check which predicate was used, the outcome should be that the error message is correct. Otherwise you're testing implementation details.
