### ISSUE TITLE
Make `maybe(:schema?)` a thing

### ISSUE THREAD

**Issue by daniels** [dry-rb/dry-validation#199]
A schema I've been working on would have benefitted from the possibility for a value to be either nil (or possibly an empty hash) or a hash conforming to a sub schema. This isn't straight forward in dry-validation as is, the one solution I've come up with is as a custom predicate calling the sub schema, but then you lose the error information from the inner schema.

The feature would be very similar to what `#maybe` macro allows for other predicates. Just like `required(:foo).maybe(:str?, size?: 10)` mandates the key to be present but accepts either nil or a string conforming to additional requirements, my schema would require the key but accept either nil or a hash conforming to additional requirements.

I don't know what the syntax should be like. Before I realized that this isn't implemented I tried to use `schema {}` as a predicate, maybe it could be made to work similarly: `required(:foo).maybe(hash?, schema?: MySubSchema)`?

**Comment by solnic** [comment]
We can support this syntax:

``` ruby
required(:data).maybe(SubSchema)

# or

required(:data).maybe do
  schema do
    # ..
  end
end
```

**Comment by daniels** [comment]
Weirdly enough, I have now seen an example of where `#schema` does seem to work as a predicate, in the code that prompted #190. I went back and found the context and full example from @joevandyk in the chat.

Inside an `#each` block, schema can be used like a predicate, and if the value is wrapped in an array it behaves like I would expect. Here is the code extracted from the chat log together with a failing spec when trying to do the same where the value is directly under the key (old syntax):

```ruby
require 'rspec'
require 'dry-validation'

RSpec.describe "a schema allowing nil or a schema" do

  describe "my schema" do

    let(:schema) {
      Dry::Validation.Schema do
        configure do
          def iz_hash?(value)
            value.is_a?(Hash)
          end
        end

        key(:foo) {
          none? | iz_hash?.then(
            schema { key(:bar).required(:str?) }
          )
        }
      end
    }

    it "validates a nil value" do
      expect(schema.call({ foo: nil })).to be_success
    end

    it "validates a hash matching the sub schema" do
      expect(schema.call({ foo: { bar: "baz" } })).to be_success
    end

    it "fails validation if the hash doesn't match the sub schema" do
      expect(schema.call({ foo: { qux: "baz" } })).to be_failure
    end


  end

  describe("joeschema") do

    let(:joeschema) {
      Dry::Validation.Schema do
        configure do
          def iz_hash?(value)
            value.is_a?(Hash)
          end
        end
        key(:foo).each do
          none? | iz_hash?.then(
            schema { key(:bar).required(:str?) }
          )
        end
      end
    }

    it "validates a nil value" do
      expect(joeschema.call(foo: [nil])).to be_success
    end

    it "validates a hash matching the sub schema" do
      expect(joeschema.call(foo: [{bar: "baz" }])).to be_success
    end

    it "fails validation if the hash doesn't match the sub schema" do
      expect(joeschema.call(foo: [{ quz: "baz" }])).to be_failure
    end

  end

end
```

The first group fails with `ArgumentError: +schema+ is not a valid predicate name` but the last passes.

**Comment by solnic** [comment]
Yeah it's because I haven't unified how `schema` syntax is used in the DSL; I'll be improving that
