### ISSUE TITLE
Duplicated keys in nested schemas produce incorrectly nested validation messages

### ISSUE THREAD

**Issue by dgollahon** [dry-rb/dry-validation#201]
It appears that keys that have a parent key with the same name clobber the nesting structure of output messages.

See my test script:

```ruby
require 'dry/validation'

# With duplicate keys

schema =
  Dry::Validation.Schema do
    required(:foo, :hash).schema do
      required(:foo).filled
    end
  end

puts schema.call({}).messages # => {:foo=>["is missing"]}
# OK

puts schema.call(foo: {}).messages # => {:foo=>["is missing"]}
# NOT OK - I expected {:foo=>{:foo=>["is missing"]}}

puts schema.call(foo: { foo: 'iamfilled' }).messages
# OK

puts '*' * 80

# Renaming the inner foo to bar

schema =
  Dry::Validation.Schema do
    required(:foo, :hash).schema do
      required(:bar).filled
    end
  end

puts schema.call({}).messages # => {:foo=>["is missing"]}
# OK

puts schema.call(foo: {}).messages # => {:foo=>{:bar=>["is missing"]}}
# OK

puts schema.call(foo: { bar: 'iamfilled' }).messages # => {}
# OK

puts '*' * 80

# Also occurs with other keys between the duplicates in the hierarchy

schema =
  Dry::Validation.Schema do
    required(:foo, :hash).schema do
      required(:bar, :hash).schema do
        required(:foo).filled
      end
    end
  end

puts schema.call({}).messages # => {:foo=>["is missing"]}
# OK

puts schema.call(foo: {}).messages # => {:foo=>{:bar=>["is missing"]}}
# OK

puts schema.call(foo: { bar: {} }).messages # => {:bar=>{:foo=>["is missing"]}}
# NOT OK - what happened to the first :foo?

puts schema.call(foo: { bar: { foo: 'iamfilled' } }).messages # => {}
# OK
```

**Comment by dgollahon** [comment]
Just for fun I decided to poke around the source and see if I could figure out what the issue is.

I think I found _where_ the problem lives, but I don't understand the expected input conditions / desired behavior of the line of code.

Perhaps someone else may benefit from starting at
https://github.com/dry-rb/dry-validation/blob/master/lib/dry/validation/error_compiler/input.rb#L84
or, if someone can explain to me what's going on there / what the contract of `visit_predicate` is, maybe I can help fix it.

**Comment by solnic** [comment]
@dgollahon yeah current implementation is rather overly complex as a result of lots of internal changes between early versions and 0.7. In the 0.8.0 release we started the process of simplifying this as now predicate ast includes all information about the arguments. I'll be rewriting error compiler completely for 0.9.0 and I bet I'll make it 3 x simpler and 10 x faster :) Anyhow...

I guess our `nil` shows up when `token[:name]` is nil, so doing `compact` on the resulting array should fix it. This method returns a hash with potentially deeply nested structure when a rule has a path with size > 1 so ie if a rule evaluates input under `[:user, :address, :city]` then we're gonna get `{ user: { address: { city: ["some message"] } } }` back from `visit_predicate`.

**Comment by solnic** [comment]
Oh I wait, `token[:name]` shouldn't be nil because it defaults to the rule name. So I guess `Array(name)` includes a nil in some cases. This should be called `path` rather than `name` btw, and it can be an array.

**Comment by solnic** [comment]
Should be fixed on master

**Comment by dgollahon** [comment]
Thanks, @solnic! Unfortunately I found one more case where this fails:

I locally added this test to the `nested_schemas_spec` to verify:

```ruby
  context 'when two schemas have the same name' do
    subject(:schema) do
      Dry::Validation.Schema do
        required(:foo).schema do
          required(:foo).schema do
            required(:bar).filled
          end
        end
      end
    end

    it 'fails when the inner key is missing' do
      expect(schema.call(foo: { foo: {} }).messages).to eql(
       foo: { foo: { bar: ["is missing"] } }
      )
    end
  end
```

Output:

![image](https://cloud.githubusercontent.com/assets/4211073/16542908/ef0aa8d8-4070-11e6-9a7a-f7426d2b6d07.png)

**Comment by solnic** [comment]
Huh I tried to fix this but it's a dead-end. I'll just go ahead and rewrite the damn thing. We've got a ton of complexity in error compiler that is no longer needed.

Does this bug affect you now?

**Comment by dgollahon** [comment]
Ah, ok. Sounds good.

It does. The project I work on tries to return detailed error messages with the full key path to where the user's json is incorrect. In two specific cases we drop a second `data` in the key path so it could potentially be a bit confusing to the user, therefore it would be nice to have it fixed. On a personal note, I'm especially motivated by it being the only active bug in our issue tracker and I've been trying to hit 0, heh.

I really appreciate your work on this issue and I look forward to seeing it fixed whenever you are able to repair it. :) I'd also be happy to help work on this issue in my free time this week if there are some small / clear tasks I could help out with, though I suspect my unfamiliarity with the codebase and the nature of this being a rewrite may prohibit me from being too helpful.

**Comment by solnic** [comment]
@dgollahon oh yeah then I'll try to fix this soon. It makes no sense to fix this in the current implementation of the error compiler though so I'll just rewrite it. I know that "rewrite" sounds scary but truth is we need to do *way less work* now that we have nested schemas and all arg info in predicates :)
