### ISSUE TITLE
Expose validation steps API

### ISSUE THREAD

**Issue by solnic** [dry-rb/dry-validation#209]
Since 0.9.0 schemas use an internal `executor` object which has steps that are being executed when a schema is called. This is a nice foundation that we can use to add ability to provide your own steps.

We could have something like this:

``` ruby
class MyStep
  # results is our error accumulator hash
  def call(input, results)
    # do something
  end
end

Dry::Validation.Schema do
  configure do
    config.steps << MyStep.new
  end
end
```

Things to figure out:
- Result object API compatible with dry-logic results, maybe sth like `Validation.(Success,Failure)(rule_name, input_values_that_were_checked)`
- Should we only allow appending steps, or should this be more flexible?

**Comment by dNitza** [comment]
@solnic — I have been looking at implementing this feature. Is this something that is still on the map for version 1.0?

**Comment by solnic** [comment]
@dNitza yes, but things may change a lot internally, so it’s better to hold off until we’re done with the work on dry-schema

**Comment by solnic** [comment]
This won't be needed in 1.0.0.
