### ISSUE TITLE
Dry::Validation.Form - error when validating array type

### ISSUE THREAD

**Issue by mkarbowiak** [dry-rb/dry-validation#212]
I want to be able to pass an array and nil as `arr` parameter.
This works:
```ruby
schema = Dry::Validation.Schema do
  required(:arr).maybe(:array?)
end

schema.call(arr: [])
# => #<Dry::Validation::Result output={:arr=>[]} messages={}>

schema.call(arr: [1, "foo"])
# => #<Dry::Validation::Result output={:arr=>[1, "foo"]} messages={}>

schema.call(arr: nil)
=> #<Dry::Validation::Result output={:arr=>nil} messages={}>

schema.call(arr: "foo")
=> #<Dry::Validation::Result output={:arr=>"foo"} messages={:arr=>["must be an array"]}>

schema.call(foo: 1)
# => #<Dry::Validation::Result output={:foo=>1} messages={:arr=>["is missing"]}>
```

but since I wanted type coercion earlier I had to go with `Dry::Validation.Schema` what resulted in:

```ruby
schema = Dry::Validation.Form do
  required(:arr).maybe(:array?)
end
# NoMethodError: undefined method `[]' for nil:NilClass
```

**Comment by solnic** [comment]
This was a known issue in dry-types where it expected a member type for `*.array`. I was on the fence with how to fix it but ended up taking pragmatic approach, so we now accept `*.array` without a member type. Which means it won't crash in the use case like yours.

It's in 0.9.2 that I just released, it's gonna pull in dry-types 0.8.1 too.
