### ISSUE TITLE
Result#messages(full: true) returns the same output of #messages

### ISSUE THREAD

**Issue by jodosha** [dry-rb/dry-validation#220]
```ruby
(byebug) result
#<Dry::Validation::Result output={} messages={:foo=>["is missing", "must be greater than 23"]}>
(byebug) result.messages
{:foo=>["is missing", "must be greater than 23"]}
(byebug) result.messages(full: true)
{:foo=>["is missing", "must be greater than 23"]}
```

**Comment by solnic** [comment]
oh wait, this is expected, we memoize messages on the first call. What's the use case for calling more than once?

**Comment by jodosha** [comment]
@solnic I'm sorry, but I've ran into this problem because of some tests that were using both the signatures.

```ruby
result.messages # do some assertions
result.messages(full: true) # other assertions which used to fail.
```

As a side note, memoization was unexpected. 😉

**Comment by fran-worley** [comment]
@solnic this is going to be an issue in Reform. Reform collates errors from different schemas into its own errors API, we will need to run the call once for standard and again for full so our users get the choice between the two at run time.

A better solution would be to be able to grab the message_set (like we discussed) and then convert between full and normal when needed. That way we don't have to run the compilers twice.

I'll raise this as a separate issue to avoid confusion between the reform use can and Hanami's.

**Comment by solnic** [comment]
@fran-worley I just did that in master, there's `Result#message_set` now

**Comment by solnic** [comment]
BTW if you think memoizing `messages` no first call might be confusing, I can change that too

**Comment by fran-worley** [comment]
@solnic 🌟 I'll check it out, thanks!
I think it could confuse as you would expect @jodosha example to work.

**Comment by solnic** [comment]
@jodosha @fran-worley I removed memoizations and added a couple of things that you may find useful:

``` ruby
result = schema.(some_input)

message_set = result.message_set # returns raw `MessageSet` instance

message_set.root? # true if the errors are about the input itself, and no specific keys were checked
message_set.dump # returns an array for root errors and hash for key-based errors
message_set.to_h # returns hash (nil is used for the root key if it's root messages)
message_set.to_a # all errors in a flat array although nested hashes are not dumped to_a recursively

message_set.messages # error message objects
message_set.hints # hint message objects

```

**Comment by fran-worley** [comment]
Thanks @solnic I'll feedback how I get on with reform :)

**Comment by jodosha** [comment]
@solnic Thanks! 💖 

To clarify. Memoization isn't bad per se, but because that means to mutate an instance, I was surprised to see it here.

Anyway, I'm glad you removed it. Thank you again!

**Comment by solnic** [comment]
This is now released in 0.9.3 :)

**Comment by kirs** [comment]
I think this change broke `.messages(as_hash: false)` that returned a structure like this one:

```
#<Dry::Validation::MessageSet:0x007fb87190ec88
 @hints={},
 @messages=
  [#<Dry::Validation::Message predicate=:array? path=[:transactions] text="must be an array" options={:args=>[], :rule=>:transactions, :each=>false}>],
 @paths=[[:transactions]],
 @placeholders={:transactions=>[]}>
```

However `as_hash: false` wasn't documented, it was a useful option in my case to fetch errors as a list.

**Comment by kirs** [comment]
Oh, I just realized that I can use `message_set` and get the same results. Sorry about complaining here.

**Comment by solnic** [comment]
@kirs no worries, I actually added this method so that @fran-worley can experiment with it a bit in Reform, hence no docs or anything. Now just use `#message_set` as you figured out already, this one will stay.
