### ISSUE TITLE
Base Schema for Dry::Validation.Form

### ISSUE THREAD

**Issue by YayConnolly** [dry-rb/dry-validation#224]
Currently, calling 
```
class BaseSchema < Dry::Validation::Schema
...
end

Dry::Validation.Form(BaseSchema) do 
...
``` 
raises `ArgumentError - wrong number of arguments (given 2, expected 0..1)`. I expected it to work like the following does:
```
class BaseSchema < Dry::Validation::Schema
...
end

Dry::Validation.Schema(BaseSchema) do
...
```

Maybe this isn't a new feature, but a documentation issue. Would this be equivalent for the first example?
```
class BaseSchema < Dry::Validation::Schema::Form
  ...
end

Dry::Validation.Schema(BaseSchema) do
...
```

**Comment by solnic** [comment]
if you define a class then don't use `do end` syntax, so:

`class BaseSchema < Dry::Validation::Schema do; end` => `class BaseSchema < Dry::Validation::Schema; end`

**Comment by YayConnolly** [comment]
Sorry, that was a typo. Edited above

**Comment by solnic** [comment]
Ah yeah, sorry about that. This is actually not supported yet, silly little thing that haven't got a chance to add yet...I'll do it in next version.

**Comment by solnic** [comment]
I should add that for now just do:

``` ruby
Dry::Validation.Schema(Dry::Validation::Form, rules: BaseForm.class.rules)
```
