### ISSUE TITLE
How to access the attribute(s) of the current rule from a custom predicate?

### ISSUE THREAD

**Issue by contentfree** [dry-rb/dry-validation#228]
Given a rule of `required(:name).filled(:my_custom_predicate?)`, how can I reference the attribute – :name – from my custom predicate? 

This is especially useful for scoped uniqueness validators. I'm working around it currently by passing the attribute name into the predicate, eg `required(:name).filled(unique?: [:name, scope: :company_id])`

**Comment by solnic** [comment]
That's not supported, yet. I need to experiment a bit to see how to solve this. It should be possible to provide additional data for predicates, we build new predicate instances for each schema, so we have a place where we could pass in more info. It's mostly a matter of coming up with the desired interface for that, which means that a simple method definition won't be enough.

**Comment by dnd** [comment]
Reform works around this/makes this possible by passing the form instance being validated in using `#with` before the call. `schema.with(form: form).call(fields)`. Then you can just define `option :form` in your configure block and you can get access to anything you need.

**Comment by victormier** [comment]
Any news about this? Is there a preferred way to solve this or could I help out?

**Comment by solnic** [comment]
This needs to wait for 1.0.0. In general development is on hold until I'm done with rom 4.0. I'll get back to dry-validation in July.

**Comment by solnic** [comment]
This will be supported OOTB by the new rule system that's going to be introduced via #440
