### ISSUE TITLE
Support Dry::Validation::Result#to_either

### ISSUE THREAD

**Issue by saverio-kantox** [dry-rb/dry-validation#229]
To properly chain validations with other more 'monadic' operations, I found the need of something like
```ruby
MySchema.(params).to_either
.fmap { |output| do_stuff(output) }
.bind { |whatever| else }
```

Do you think it makes sense to have a native `to_either`, plus delegated `bind` and `fmap` directly on the result? In that case what would be the desired content of the Right, the result itself or the output? And the Left would contain the result or just the errors?

**Comment by solnic** [comment]
This sounds like a good idea. We could add an optional monad extension for `Result`. I suppose `Left` should include error messages, and `Right` should include result output. WDYT @flash-gordon @timriley ??

**Comment by flash-gordon** [comment]
👍

**Comment by timriley** [comment]
Yep, this seems good to me 👍

I wondered for a moment as to whether the `Left` side should also contain the output too, but I realise that in most situations, the _original_ input (i.e. before it was passed to the schema) should still be available to reuse in the error case anyway.
