### ISSUE TITLE
type? predicate unexpectedly uses class constructor as validator when it takes an argument

### ISSUE THREAD

**Issue by ZimbiX** [dry-rb/dry-validation#230]
I've had to spend several hours debugging unexpected behaviour due to this feature that is - as far as I can tell - undocumented.

The `type?` validation predicate is peculiar. If the constructor of the supplied class takes an argument, it is given complete responsibility for validation and is passed the value being validated. The validation fails if an exception is raised, and passes otherwise. On validation failure, no exception or useful error comes back to Trailblazer/Reform to indicate that the validation is happening this way.

```ruby
# In Piece::Create validation
Dry::Types.register_class Direction
required(:direction).value(type?: Direction)

# In Piece::Create spec
result, op = Piece::Create.run(piece: { direction: Direction.new(:east) })
expect(result).to be true
result, op = Piece::Create.run(piece: { direction: :east })
expect(result).to be false

# In Direction
def initialize facing
  raise ArgumentError unless facings.include? facing
  @facing = facing
end
```

In my application, the Direction class constructor required an argument for its facing, and threw an unspecified exception if this was not one of the accepted symbols. Testing expected failure of the Create operation with a valid facing symbol resulted in unexpected behaviour that was incredibly difficult to debug.

The solution I have found is to, while registering the class as a dry type, pass another method that takes no arguments as the constructor argument.

```ruby
Dry::Types.register_class Direction, :class
```

Though I am only starting to understand the basics of dry-validation, it doesn't make sense to me for this to be the default functionality when using a validation that is supposed to be just checking if the class type matches. I'm sure this kind of validation class method would be useful at some point, but I think it would be much more suitable as a separate validation predicate.

Hopefully this is helpful. I would at least ask that this behaviour be documented somewhere, to save others making the same mistake. Keep up the good work =)

**Comment by solnic** [comment]
Sorry for this late reply. I'll improve this in 0.10.0

**Comment by solnic** [comment]
What was the reason for registering your own class as a dry-type? There's no need for that when you use `type?` predicate, unless it really is a dry type with a constraint, which we can use to infer predicates from.

**Comment by ZimbiX** [comment]
Ahh, ok. That would indicate that the issue actually lies with Reform. I'll file it there instead. Thanks.

Here's a demo, anyway:

```ruby
require 'reform'
require 'reform/form/dry'
Reform::Form.send :feature, Reform::Form::Dry

# Modified from: http://dry-rb.org/gems/dry-validation/basics/built-in-predicates/#types

class Direction
end

RSpec.describe "type?" do
  let(:schema) do
    Dry::Validation.Schema do
      required(:facing).value(type?: Direction)
    end
  end

  class Form < Reform::Form
    ::Dry::Types.register_class Direction
    property :facing, virtual: true
    validation do
      required(:facing).filled(type?: Direction)
    end
  end

  let(:input_valid)   { {facing: Direction.new} }
  let(:input_invalid) { {facing: Object.new} }

  it "as regular ruby" do
    expect(input_valid[:facing].class).to eq Direction
    expect(input_invalid[:facing].class).to_not eq Direction
  end

  it "with dry-validation" do
    expect(schema.call(input_valid).success?).to eq true
    expect(schema.call(input_invalid).success?).to eq false
  end

  it "with reform" do
    expect(Form.new(0).validate(input_valid)).to eq true
    expect(Form.new(0).validate(input_invalid)).to eq false
  end
end
```

Without `::Dry::Types.register_class Direction`, it raises an error:

```
/home/brendan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/dry-container-0.5.0/lib/dry/container/resolver.rb:22:in `block in call': Nothing registered with the key "direction" (Dry::Container::Error)
```
