### ISSUE TITLE
Support for custom types with type specs

### ISSUE THREAD

**Issue by timriley** [dry-rb/dry-validation#231]
Right now dry-validation supports using custom type objects using the sanitizer input processor and a type object specified for a key in the schema. Taken from `spec/integration/schema/using_types_spec.rb`:

``` ruby
context 'custom coercions' do
  subject(:schema) do
    Dry::Validation.Schema do
      configure { config.input_processor = :sanitizer }

      required(:email).filled(Dry::Types['strict.string'].constructor(&:strip))
    end
  end

  it 'applies custom types to input prior validation' do
    result = schema.(email: ' jane@doe.org  ')

    expect(result).to be_success
    expect(result.to_h).to eql(email: 'jane@doe.org')
  end
end
```

IIRC, this input processor feature will disappear before 1.0 and be fully replaced with the type specs feature. Is this right?

If this is the case, then I think it would be good if we could allow the type specs to work with custom type objects in order to achieve a similar behaviour to this spec example above. Looking at the current code (in particular, `Dry::Validation::TypeSpecs#lookup_type`), it seems we only support the "built-in" types from dry-types, which wouldn't allow a developer to create e.g. their own coercing type object and use it as a type spec in a dry-validation schema.

**Comment by flash-gordon** [comment]
Can you imagine @timriley, this will work exactly like this in the next version! 🎉 

```ruby
schema = Dry::Schema.define do
  required(:email).filled(Dry::Types['strict.string'].constructor(&:strip))
end

schema.(email: ' jane@doe.org  ')
 => #<Dry::Schema::Result{:email=>"jane@doe.org"} errors={}>
```
