### ISSUE TITLE
predicate dynamic args - option vars are nil

### ISSUE THREAD

**Issue by fran-worley** [dry-rb/dry-validation#232]
So I bumped into this when working on a use case via Reform (we always pass in the form instance via `schema.with(form: form).()`). I wanted to access a method on my form as the dynamic arg for a predicate, only to find that form was nil when the dynamic arg method was called.

Interestingly, the same method when called as a custom predicate can return the form instance without issue.

I extended this spec:  https://github.com/dry-rb/dry-validation/blob/master/spec/integration/schema/dynamic_predicate_args_spec.rb

```ruby
RSpec.describe Dry::Validation::Schema, 'dynamic predicate args via option objects' do
  subject(:schema) do
    Dry::Validation.Schema do
      configure do
        option :form
        
        def data
          form.data # here we get an error as form is nil
        end
      end

      required(:letter).filled(included_in?: data)
    end
  end
  let(:form){ OpenStruct.new(data: %w(a b c)) }
  
  it 'evaluates predicate arguments' do
    expect(schema.with(form: form).(letter: 'a')).to be_success
    expect(schema.with(form: form).(letter: 'f')).to be_failure
  end
end
```

**Comment by ZimbiX** [comment]
Thanks for logging this. I'd moved on and forgotten about it

**Comment by gorkunov** [comment]
@fran-worley I found workaround:
```ruby
subject(:schema) do
    Dry::Validation.Schema do
      configure do
        option :form

        def data
          form ? form.data : [] 
        end
      end

      required(:letter).filled(included_in?: data)
    end
  end
```

Seems schema starts validate predicates after initialization, so it happens before passing form in `with`, in that moment form option is nil. I have no idea how to fix this :).

**Comment by solnic** [comment]
This can't be fixed on dry-v side. These dynamic args are evaluated when we build the rules, and we build the rules in the constructor. If there's an option that a give dyn-arg relies on, then it must be set to something when you initialize the first schema instance.

I believe Reform should simply build a schema class, and instantiate it with needed options. So ie `schema_class = Dry::Validation.Form(build: false); schema_class.new(schema_class.rules, form: reform_object)`.

Closing...

**Comment by fran-worley** [comment]
@solnic you're too quick for me, I was just coming to the same conclusion! I'll check out the build option roughly what does it do?

**Comment by solnic** [comment]
@fran-worley `Dry::Validation.Schema` and `Dry::Validation.Form` methods are just shortcuts for defining a schema *class* and creating its initial *instance* too. I added these just to reduce some boilerplate. You can always define a schema class in a normal way like that:

``` ruby
class Schema < Dry::Validation::Schema::Form
  define! do
    required(:foo).value(:str?)
  end
end

schema = Schema.new
```
