### ISSUE TITLE
 Can someone fix it?

### ISSUE THREAD

**Issue by junofjun** [dry-rb/dry-validation#247]
I'm using this 'rails-settings-ui' gem.

I think the following commit blamed

>>>  https://github.com/dry-rb/dry-configurable/commit/8a6a127bfe4b411359fc670a8fe82ed8438ac458#diff-d7f37a47ef26baa286f14a4c07319f89L82

i've been getting following error.

>>> There was an error while trying to load the gem 'rails-settings-ui'. (Bundler::GemRequireError)

I think that an error has come out in the following

https://github.com/dry-rb/dry-validation/blob/d8d63d3da3354b704bfa8cb28cda24197debe0bb/lib/dry/validation/schema/class_interface.rb#L25

Can someone fix it?

**Comment by AMHOL** [comment]
@junofjun dry-configurable 0.2.0 has been yanked, just run `bundle update dry-validation`, sorry for the inconvenience
