### ISSUE TITLE
Allow better control over error messages

### ISSUE THREAD

**Issue by RKushnir** [dry-rb/dry-validation#248]
I'd like to suggest a feature, which would support my use case. There's a predicate:

``` ruby
def youtube_url?(kind, input)
  Yt::Models::URL.new(input).kind == kind
end
```

Depending on the `kind` argument, which can be `:playlist`, `:subscription`, `:video` or `:channel`, I need to show different error messages(e.g. `must be a link to a YouTube clip`, `must be a link to a channel` etc). For that, I'd need a way to override the default lookup paths depending on the argument value.

**Comment by solnic** [comment]
This will be completely under your own control starting from 1.0.0. See #440 for progress.
