### ISSUE TITLE
Can't provide a proper custom rule for option parameters

### ISSUE THREAD

**Issue by dsounded** [dry-rb/dry-validation#250]
http://pastebin.com/39dT3PKh

Basically I need to check if my `combinations` include current `categories` in my object(like multiple  parallel `included_in`)

But now it throws an error `+combinations+ is not a valid predicate name`

**Comment by solnic** [comment]
In 0.10.0 you will be able to write it like that:

``` ruby
require 'dry-validation'

schema = Dry::Validation.Schema do
  configure do
    option :combinations, { c1: 'a', c2: 'b', c3: 'c' }

    def self.messages
      super.merge(en: { errors: { combinations: 'invalid combinations' }})
    end
  end

  required(:c1).filled(:str?)
  required(:c2).filled(:str?)
  required(:c3).filled(:str?)

  validate(combinations: %i[c1 c2 c3]) do |c1, c2, c3|
    combinations[:c1] == c1 && combinations[:c2] == c2 && combinations[:c3] == c3
  end
end
```

**Comment by dsounded** [comment]
@solnic  Will I be able to pass `option :combination` as it was before ?

**Comment by solnic** [comment]
@dsounded no need for that, I added `validate` feature which accepts a block that is executed in the context of your schema, so you just use whatever you need there.

**Comment by dsounded** [comment]
I see
