### ISSUE TITLE
make sure that a key rule is added as a minimum when using 'required' without additional restrictions

### ISSUE THREAD

**Issue by pvmeerbe** [dry-rb/dry-validation#251]
as discussed on gitter only using  'required(:my_key)'  currently doesn't  create a validation rule in the background. As a result no validation is done, which is not what one would expect. 

See http://pastebin.com/1KrDRzSB

```
schema = Dry::Validation.Schema do
   required(:email)
end

schema.rules
 #  => {}
```

Suggestion from Fran  Worley  on gitter : 

```
   @solnic we probably should make sure that a key rule is added as a minimum if you call required, I can see it confusing people especially as you can't use the key? predicate independently.
```

**Comment by pvmeerbe** [comment]
Suggestion for new tests related to this issue is added below. The test "fails when required option without additional restrictions is not  present"  will fail due to the current issue.

Adding the following line

     add_rule(val) if key_class == Key

in lib/dry/validation/schema/dsl.rb:108 solves this issue but causes several other tests to fail, so probably not the correct solution...

   

    RSpec.describe Dry::Validation::Schema do
      describe 'defining schema with required keys' do
        subject(:schema) do
          Dry::Validation.Schema do
            required(:first_name)
            required(:email) { |email| email.filled? }
          end
        end
    
        describe '#call' do
          it 'success when keys are present with value' do
            expect(schema.(first_name: 'Adriaan', email: 'adriaan@whatever.com')).to be_success
          end
    
          it 'success when required key without additional restrictions is present with nil value' do
            expect(schema.(first_name: nil, email: 'adriaan@whatever.com')).to be_success
          end
    
          it 'success when required key without additional restrictions is present with empty string value' do
            expect(schema.(first_name: '', email: 'adriaan@whatever.com')).to be_success
          end
    
          it 'fails when required key with additional filled? restriction is present with empty string value' do
            expect(schema.(first_name: 'Adriaan', email: '')).to_not be_success
          end
    
          it 'fails when required option without additional restrictions is not  present' do
            expect(schema.(email: 'adriaan@whatever.com')).to_not be_success
          end
    
          it 'fails when required option with additional filled? restrictions is present' do
            expect(schema.(first_name: 'Adriaan')).to_not be_success
          end
    
        end
      end
    end

**Comment by solnic** [comment]
@pvmeerbe we need to aggregate these rules separately and use them only when there are no other rules, unfortunately DSL-related code is overly complex so it's gonna be harder than it should be now. It's something I'll be improving before 1.0.0 for sure. If you'd like to make it work with the existing implementation feel free to send a PR :)

**Comment by solnic** [comment]
This has been addressed in dry-schema where key-map is always built and will always preprocess input, even when there are no rules:

``` ruby
[1] pry(main)> s = Dry::Schema.Params { required(:email) }
=> #<Dry::Schema::Params:0x00007f8600a73838...>
[2] pry(main)> s.(foo: "bar", email: "jane@doe.org")
=> #<Dry::Schema::Result{:email=>"jane@doe.org"} errors={}>
```
