### ISSUE TITLE
0.9.5 is broken

### ISSUE THREAD

**Issue by am-kantox** [dry-rb/dry-validation#252]
Gem 0.9.5 is broken: there is an obsolete version of [`lib/dry/validation/message_compiler.rb:15`](https://github.com/dry-rb/dry-validation/blob/v0.9.5/lib/dry/validation/message_compiler.rb#L15), calling `@default_lookup_options = { message_type: message_type, locale: locale }`.

That results in:

> /home/am/.rvm/gems/ruby-2.3.1/gems/dry-validation-0.9.5/lib/dry/validation/message_compiler.rb:15:in \`initialize': undefined local variable or method \`message_type' for #<Dry::Mutations::Errors::ErrorCompiler:0x00000001ddfa08> (NameError)

on any try to use it.

**Comment by solnic** [comment]
In 0.9.x `MessageCompiler` is an abstract class, it's changed in 0.10.0 though where it's the only message compiler we have (ErrorCompiler and HintCompiler are removed).
