### ISSUE TITLE
Consider allowing anonymous rules

### ISSUE THREAD

**Issue by dgollahon** [dry-rb/dry-validation#253]
I had a use-case for this today and discussed it in the gitter:

> Daniel Gollahon @dgollahon 10:02
> Hi. Is there a way to create anonymous rules in dry-validations? Or do i have to specify them as:
> rule(name: %i[args])
> I'm not saying this should be a feature, just curious if it exists. I have a case where I'm validating something but do not at all care about the error messages, only whether or not the thing is valid. I also use mutant in CI and it complains that it can rename the argument name__mutant__. I can expose the schema and expect something about it to kill the mutant, but if there already happens to be a way to define the rule anonymously, that'd be cool.
> 
> Piotr Solnica @solnic 16:26
> @dgollahon this is an interesting use-case that I haven’t thought about, could you please report an issue about this?

It might be cool if there was a default rule name based off of the names of the dependent keys. Again, more for discussion as to whether others might have a use for this than "please add this".

**Comment by solnic** [comment]
Do you need messages for other rules though?

**Comment by dgollahon** [comment]
In other parts of the application, that would be helpful but I don't currently do it because I haven't decided how I want to map rules to user-facing error messages that come from rule violations exactly.

In this specific instance, though, no. I'm validating some non-user-facing data that I'm importing from an external source before persisting to the db (to avoid constraint violations), so I don't care about error messages at all--I just want to ensure that my data quality rules are enforced. On a related note, is there any roadmap for having a `Dry::Validation.Model`? I saw it mentioned in some issue a while back... I've been using `.Schema` and then `to_h`'ing the structs I have before persisting them which is fine for now but not perfect.

**Comment by solnic** [comment]
@dgollahon messages are compiled lazily when you ask for them, this means that `schema.(input).success?` is all you need

**Comment by dgollahon** [comment]
@solnic: right, that's what I'v been using.

**Comment by dgollahon** [comment]
If it was confusing, the `to_h`ing was just so i could get a hash for dry-validation to validate against since, AFAIK, there is no attribute equivalent.

**Comment by solnic** [comment]
@dgollahon there used to be `attr` macro but we removed it, in general the idea is to validate data before using it for anything

**Comment by dgollahon** [comment]
@solnic: Right, I was looking for it the other day and saw that.

Yeah, this happens to already come back to me from an internal lib in struct form so it's kind of an unusual case. Normally throughout the app user input gets validated before getting coerced into any other structure but that wasn't as much of an option here.

**Comment by solnic** [comment]
Anonymous rules will be supported in 1.0.0. Check #440 to see progress.

**Comment by dgollahon** [comment]
Awesome! :) Looking forward to a 1.0.
