### ISSUE TITLE
format? should be excluded from hints

### ISSUE THREAD

**Issue by solnic** [dry-rb/dry-validation#257]

**Comment by klebervirgilio** [comment]
I'm happy to help! :)

Besides, the documentation, specs and a good code read, would you have any other thing to say before I start?

Thanks!

**Comment by solnic** [comment]
@klebervirgilio great, thank you :) There's [a constant](https://github.com/dry-rb/dry-validation/blob/master/lib/dry/validation/message_set.rb#L9) for filtering out specific predicates, so it's a matter of adding `format?` there and adding specs making sure it is excluded in `Result#messages`
