### ISSUE TITLE
Can't use custom varialbes in message translation built by `validate` block

### ISSUE THREAD

**Issue by dsounded** [dry-rb/dry-validation#259]
For now I can't pass vars there, even more it seems like there is no access to `option` vars

**Comment by solnic** [comment]
I need to figure out an API for this. It would be nice if this was "close" to the actual validate block definition.

**Comment by dsounded** [comment]
@solnic any update ?

**Comment by solnic** [comment]
@dsounded mostly this https://discuss.dry-rb.org/t/plans-for-dry-validation-dry-schema-a-new-gem/215

**Comment by milushov** [comment]
@solnic any updates? discuss link not woking for me

**Comment by milushov** [comment]
ow, wrong link, proper one is https://discourse.dry-rb.org/t/plans-for-dry-validation-dry-schema-a-new-gem/215

**Comment by solnic** [comment]
@milushov I started working on dry-schema recently (see https://github.com/dry-rb/dry-schema/pull/3 to see the progress)

**Comment by solnic** [comment]
this will be finally addressed by the rewrite (first step is #440 then I'll add support for message translations and this issue will be fixed, finally).
