### ISSUE TITLE
Validating against a partial schema

### ISSUE THREAD

**Issue by UberMouse** [dry-rb/dry-validation#261]
Hey,

I started using this library a few days ago and it's been working quite well so far but I have a question about something I am going to want to do in the future; hopefully, it's possible. 

Basically, I'm using dry-validations to validate incoming JSON for an API against some Schemas before they get stored into MongoDB (not using Mongoid validations because so many of them are conditional). What I have now will work for a full POST/PUT request for example, but I am also keen to support PATCH using the [JSON Merge Patch RFC](https://tools.ietf.org/html/rfc7386) which means it would be nice if I was able to validate the partial JSON against the Schema, with it only validating the fields that are present in the partial merge fragment.

If this isn't possible the other alternative is to just perform the merge update against the object before validating it so it's a full JSON object at that point instead of a partial. But that adds a bit of complexity it would be preferable to avoid.

Cheers

**Comment by solnic** [comment]
This is on our 1.0.0 roadmap :) it's very likely it'll be added in one of
the 0.x releases so that people can test it easily in the wild before we
hit 1.0.0

**Comment by UberMouse** [comment]
Great, I'll just go with my alternative approach for now then :) 

Looking forward to when it drops.
