### ISSUE TITLE
High-level rule messages of nested schemas don't respect hierarchy

### ISSUE THREAD

**Issue by Kukunin** [dry-rb/dry-validation#264]
I believe it's bug (at least very weird behaviour), when nested schema contains high level rules.
Let me demonstrate with code:

``` ruby
A = Dry::Validation.Schema do
  required(:parent).schema do
    required(:child).filled(:str?)
    rule(child_only: [:child]) do |child|
      child.format?(/\d+/)
    end
  end
end

A.call(parent: {}).errors
# => {:parent=>{:child=>["is missing"]}}

A.call(parent: {child: ''}).errors
# => {:parent=>{:child=>["must be filled"]}}

A.call(parent: {child: 'abc'}).errors
# => {:child_only=>["is in invalid format"]}
```

As you can see, there is no hierarchy in the errors output.

I'm not sure what is expected behaviour, but at least it's required to preserve nested structure.

BTW, it doesn't work even for three levels of nesting:

``` ruby
A.call(parent: {child: {}}).errors
# => {:parent=>{:child=>{:grandchild=>["is missing"]}}}
A.call(parent: {child: {grandchild: 'abc'}}).errors
# => {:digits_only=>["is in invalid format"]}
```

On previous version **0.9.5** it was like this:

``` ruby
A.call(parent: {child: ''}).messages
# => {:parent=>{:child=>["must be filled"]}}

A.call(parent: {child: 'abc'}).messages
# => {:parent=>{:child_only=>["is in invalid format"]}}
```

So, looks like regression

**Comment by solnic** [comment]
I'll fix it in 0.10.4

**Comment by Kukunin** [comment]
It's still present in 0.10.5 =(

**Comment by solnic** [comment]
It's very likely I'll extract high-level rules to a separate gem, it makes dry-v way too complicated and what's most important - it's a different concept

**Comment by Kukunin** [comment]
thanks for update

**Comment by solnic** [comment]
High-level rules will work differently in 1.0.0.
