### ISSUE TITLE
Validation bug with nested schema and type_specs enable

### ISSUE THREAD

**Issue by Kukunin** [dry-rb/dry-validation#265]
I have to use `type_specs = true` as workaround of another bug, and noticed that it works differently in direct and nested schemas. 

I have one field, which has both coercion and validation rules, and I try to set them separately in schema DSL, which seems logically.

It works fine for direct schema, but if this schema is nested, coercion doesn't seem to work.
Here is example in code:

``` ruby
        Types = Dry::Types.module
        Validation = Types::Strict::String.constrained(format: /\A\w+\z/)
        Coercion = Validation.constructor { |a| a.gsub(/\s+/, '') }

        A = Dry::Validation.Form do
          configure { config.type_specs = true }
          required(:val, Coercion).filled(Validation)
        end
        B = Dry::Validation.Form do
          required(:parent).filled(A)
        end

        hash = {'val' => 'a b c'}
        p A.call(hash)
        #<Dry::Validation::Result output={:val=>"abc"} errors={}>
        p B.call('parent' => hash)
        #<Dry::Validation::Result output={:parent=>{:val=>"a b c"}} errors={:parent=>{:val=>["is in invalid format"]}}>
```

A couple more considerations:
1. It doesn't matter, either `B` schema is `type_specs = true` or not
2. It works fine, if there is `required(:val, Coercion).filled(Coercion)`
3. Coercing in `A` stops to work if `Dry::Validation.Form` changes to `Dry::Validation.Schema` (is it by intention?)

Maybe there is mistake how I understand `type_specs`, but as for me, it's expected, that Coercing should be in `required` and validation should be in `filled` helpers.

Currently I use second consideration as workaround

**Comment by solnic** [comment]
This shouldn't be allowed, if you want to pass in a schema you need to do `required(:parent).schema(A)`. Can you confirm that this works?

**Comment by Kukunin** [comment]
with `schema` instead of `filled`

```ruby
    B = Dry::Validation.Form do
      required(:parent).schema(A)
    end
```

it's the same. A schema works, but B schema doesn't

**Comment by flash-gordon** [comment]
This will be fixed in the next version. I'm closing this one since, here's another issue for tracking progress https://github.com/dry-rb/dry-schema/issues/25
