### ISSUE TITLE
Nil options and nested schema oddity

### ISSUE THREAD

**Issue by stackus** [dry-rb/dry-validation#267]
When you pass in a `nil` for an option value the non-nil values are bubbled to the top of the defined options list for the nested schemas.

In this example there's two nested schemas but the problem only needs one.

``` ruby
schema = Dry::Validation.Schema do
  configure do
    option :foo
    option :bar
    option :fizz
  end

  required(:data).schema do
    required(:attributes).schema do
      required(:buzz).filled
      validate(buzz?: [:buzz]) do |value|
        p foo: foo, bar: bar, fizz: fizz
      end
    end
  end

  # validate(data?: [:data]) do |value|
  #   p foo: foo, bar: bar, fizz: fizz
  # end
end

schema.with(foo: 'foo', bar: 'bar', fizz: 'fizz').call(data: {attributes: {buzz: 'buzz'}})
# {:foo=>"foo", :bar=>"bar", :fizz=>"fizz"}

schema.with(foo: nil, bar: 'bar', fizz: 'fizz').call(data: {attributes: {buzz: 'buzz'}})
# {:foo=>"bar", :bar=>"fizz", :fizz=>nil}

schema.with(foo: 'foo', bar: nil, fizz: 'fizz').call(data: {attributes: {buzz: 'buzz'}})
# {:foo=>"foo", :bar=>"fizz", :fizz=>nil}

schema.with(foo: 'foo', bar: 'bar', fizz: nil).call(data: {attributes: {buzz: 'buzz'}})
# {:foo=>"foo", :bar=>"bar", :fizz=>nil}
```

If you were to check on the values of the options outside of any `.schema` the nil would be in the correct place.

I'm using version `0.10.3`.

**Comment by solnic** [comment]
Nested schemas use separate schema objects, and options from the top level schemas are not propagated to the nested schemas (at least not yet). I need to think about this a bit as I'm not sure how exactly I want to solve this. For now, using top-level `validate` block with a path to a value (using an array of symbols) should work (if *that* doesn't work, then it's an obvious bug and should be easy to fix, please let me know if that's the case).

**Comment by solnic** [comment]
This DSL is removed in dry-schema, which will be used for schemas in dry-validation 1.0.0. This means it won't be addressed and similar functionality can be achieved using the new rule system.
