### ISSUE TITLE
Using required/optional should not be allowed in a `when` block

### ISSUE THREAD

**Issue by nkratzke** [dry-rb/dry-validation#272]
I would like to check in a mapping the value of one entry only if another entry has a specific value.
E.g. if 'A' is set to 'a' then 'B' should set to 'a' as well. This is a logical implication and I thought this could be expressed in dry-validation using "when".

I provide here some minimized code and I am quite sure that this code should be evaluated to false. However I got true. But why?

Did I understood the "when" method wrong? Or is this a bug?

```
require 'dry-validation'

TEST = { 'A' => 'a', 'B' => 'B' }

validator = Dry::Validation.Schema do
  required('A').filled(:str?).when(eql?: 'a') do  # => true
    required('B').filled(:str?).value(eql?: 'a')  # => false
  end
end                                               # should end in false (according to implication truth table)

puts validator.call(TEST).success?                # However, it is evaluated to true, why?
```

**Comment by solnic** [comment]
You need to define all keys, always, even when they are optional. We should not allow `required` in the context of a `when` block, as it just doesn't work the way you expected. Your case can be expressed using high-level rule:

``` ruby
Dry::Validation.Schema do
  required('A').filled(:str?)
  required('B').filled(:str?)

  # using abstract rule syntax
  rule(a_eql_b: %w(A B)) do |a, b|
    a.eql?('a').then(b.eql?('a'))
  end

  # or using custom block
  validate(a_eql_b: %(A B)) do |a, b|
    a == 'a' ? b == 'a' : true
  end
end
```

I'm actuallly not happy with `when` syntax, we came up with it as a nice syntax sugar but it introduced a couple of challenges in the internals and I'm not sure if it's really worth the effort.

**Comment by nkratzke** [comment]
Hmm, it is not quite clear to me, why required should not be allowed in a when block?
What ist the reason for this?
To check implications is a common tasks in validations I think. There are a lot of use cases to check only b if a is set. So, there should be a pragmatic way to express this.
I love dry-validation but implication handling is not really convincing in dry-validation from my point of view.

**Comment by solnic** [comment]
Because `when` block should deal with values, not keys. In dry-v you define a schema, including required and optional keys, missing key is also an error, and we want to validate that too. So, first of all a schema defines a structure, then it defines individual values. High-level rules are applied only when the structure is valid *and* individual values that a given high-level rule depends on are valid too. With this approach, various rules won't be even applied when keys are missing, and the only check that would be applied is `key?`.

If we allowed defining `required('A').filled(:str?)` inside that `when` block, it would mean that you only expect that key to present, and its value to be a string, when `A`'s value equals `"a"` - and it is *not* what you want to check, because you do expect both `A` and `B` to be present in the data structure, and then you have certain rules for the values.

Validating structures is something that other validation libraries don't do, so it's something to learn and understand.

btw - under the hood, that `when` block *creates a high-level rule*, as I mentioned, it's just a syntax-sugar.

**Comment by nkratzke** [comment]
You explained exactly the problem I have to validate. In a JSON definition format some keys must be only present if another key value pair is existing. Think of JSON structure like this one here.

```
[
{
   'type': 'district',
   'provider': 'AWS',
   'aws_access_key_id': 'akid',
   'aws_secret_access_key': 'secret',
  .... 
},
{
  'type': 'district',
  'provider': 'GCE',
  'gce_secret_key_file': 'path/to/secrete/key.file',
  ...
}
]
```

In this example the keys 'type' and 'provider' must be set. The keys 'aws_...' must be only set and validated if provider == AWS and keys 'gce_...' must be only set and therefore validated if provider == GCE. It is still a schema but some parts depend on other parts!

Do you really think these kind of problems are uncommon and must not be validateable by dry-v?

**Comment by kwando** [comment]
I would validate this in two steps, first validate the common ones ```type``` and ```provider``` and then lookup a second validation schema based on the ```provider``` field value. This "pattern" could also easily be turned into a reusable class/component.


```ruby
PROVIDER_SCHEMAS = {
  'AWS' => Dry::Validation.Form{
    required(:aws_access_key_id).filled
    required(:aws_secret_access_key).filled
  },
  'GCE' => Dry::Validation.Form{
    required(:gce_secret_key_file).filled
  }
}.freeze

base_schema = Dry::Validation.Form{
  required(:type).filled
  required(:provider).filled(included_in?: PROVIDER_SCHEMAS.keys)
}


base_result = base_schema.call(params)

if base_result.success?
  provider_schema = PROVIDER_SCHEMAS[base.to_h[:provider]]
  provider_result = provider_schema.call(params)
  if provider_result.success?
    # merge results or do whatever
    return base_result.to_h.merge(provider_result.to_h)
  else
    raise 'validation error'
  end
else
  raise 'validation error'
end

```

**Comment by nkratzke** [comment]
Thank you very much. That is basically how I refactored my solution getting to know that when does not work as intended.

So, that is fine for my current situation.

However, the downside of this solution is, that schema validation logic has to be coded partly outside the schema definition. I do not think that this is intent of dry-validation?

Therefore, I would propose to refactor when completely being able to handle logic implications in a way of my initial comment.

**Comment by solnic** [comment]
That's a missing feature, please stick to the workaround for now. I'll be adding support for this before 1.0.0.

**Comment by flash-gordon** [comment]
@solnic do you still think this is a bug?

**Comment by flash-gordon** [comment]
See also https://github.com/dry-rb/dry-validation/issues/383

**Comment by solnic** [comment]
`when` was removed in dry-schema, so this is not going to be addressed.
