### ISSUE TITLE
Get errors symbols instead of message

### ISSUE THREAD

**Issue by nicolas-besnard** [dry-rb/dry-validation#274]
I'd like to know if there's a way to use the errors symbols instead of the translation in a YML file ?

**Comment by nicolas-besnard** [comment]
up :)

**Comment by nicolas-besnard** [comment]
Found something working [here](https://discuss.dry-rb.org/t/get-keys-instead-of-sentences-for-validation-errors/150)

**Comment by flash-gordon** [comment]
I think the linked solution is fine. It'll work a similar way in the next version.
