### ISSUE TITLE
Form validation not passing through input params to output

### ISSUE THREAD

**Issue by maltoe** [dry-rb/dry-validation#277]
Hello all,

I might just have some configuration missing or something like that, or am just stupid, but for some reason this:

```rb
require 'dry-validation'

s = Dry::Validation.Form do
  configure { config.type_specs = true }
  required(:items).each do
    schema do
      required(:title).filled?(:str?)
    end
  end
end

puts s.(items: [{title: 'abc'}]).output
```

... doesn't give me the `title` attribute back.

Gist with code, reproduced once at a colleague's machine: https://gist.github.com/maltoe/befcdae03c3ba775ba511e0dd4ad44e6

Tried with master, too.

Interestingly, your specs seem to be fine. [These lines](https://github.com/dry-rb/dry-validation/blob/master/spec/integration/schema/form_spec.rb#L123-L129) describe exactly the same schema and inside the specs it *does* return the nested attribute.

```rb
# l. 132. works perfectly
it 'passes nested hashes to its output' do
  expect(schema.(items: [{ title: 'Foo' }]).output[:items].first).to eq({ title: 'Foo' })
end
```

It's probably some really stupid mistake, and I'd like to apologize in advance for that :)

Thank you!
malte

**Comment by Kukunin** [comment]
Because you use `type_specs = true`, you need to set explicitly type of attribute. 

```ruby
require 'dry-validation'

s = Dry::Validation.Form do
  configure { config.type_specs = true }
  required(:items).each do
    schema do
      required(:title, :string).filled?(:str?)
    end
  end
end

puts s.(items: [{title: 'abc'}]).output
```

works well

**Comment by Kukunin** [comment]
more about type_specs: http://dry-rb.org/gems/dry-validation/type-specs/, if you haven't seen it

**Comment by maltoe** [comment]
oops, that `type_spec` wasn't supposed to be there, sorry. I actually didn't have it in there while testing (see the gist). It still fails without it for me. 

However, it does work as you showed and - yes please, type_specs, here I come. Thank you!

**Comment by flash-gordon** [comment]
dry-schema's variant, the dsl of the next release
```ruby
s = Dry::Schema.Params do
  required(:items).value(:array).each do
    schema do
      required(:title).filled(:str?)
    end
  end
end
```
