### ISSUE TITLE
Defining rules for nested schemas

### ISSUE THREAD

**Issue by Goltergaul** [dry-rb/dry-validation#279]
Hi i can't find how to do this in the documentation. I have this schema:

```
FILTER_SCHEMA = Dry::Validation.Form do
  required(:user_id).filled(:str?)
  required(:group_id).filled(:str?)
  required(:filter).schema do
    required(:type) { str? & included_in?(["friends", "users"]) }
    optional(:query).filled(:str?)
  end
end
```

and i would like to define a rule that when filter => type is "users" then filter => query must be filled out

I tried the following:

```
rule(query_for_users: [:type, :query]) do |type, query|
  type.included_in?(["users"]) > query.value(:filled?)
end
```

but this does not work. How can i specify that `type` and `query` are inside `filter`?

**Comment by solnic** [comment]
Try this: `rule(query_for_users: [[:filter, :type], [:filter, :query]]) ...`

**Comment by Goltergaul** [comment]
thank you very much!
