### ISSUE TITLE
Type specs problem

### ISSUE THREAD

**Issue by vladra** [dry-rb/dry-validation#284]
Hi guys!

I've encountered error, when type spec working properly only with `Dry::Validation.Form`, but not with `Dry::Validation.Schema`. Is this intended behavior or a bug?

```ruby
require 'dry-types'
require 'dry-validation'

Types = Dry::Types.module
Price = Types::Coercible::Int
          .constrained(included_in: 0..5)
          .constructor { |i| i == 'unknown' ? 0 : i }

NotWorks = Dry::Validation.Schema do
  configure do
    config.type_specs = true
  end
  required(:price, Price).filled(Price)
end

bad = NotWorks.(price: 'unknown')
# output = {:price=>"unknown"}
# errors = {:price=>["must be one of: 0 - 5"]}

Works = Dry::Validation.Form do
  configure do
    config.type_specs = true
  end
  required(:price, Price).filled(Price)
end

good = Works.(price: 'unknown')
# output = {:price=>0}
# errors = {}
```

**Comment by solnic** [comment]
Plain `Schema` doesn't set up any input processor. You can configure it via `config.input_processor = :form` which will essentially turn a plain schema into a form schema.

**Comment by vladra** [comment]
Got it, thanks for help.

Btw there are duplication I think:
https://github.com/dry-rb/dry-validation/blob/master/lib/dry/validation/input_processor_compiler/form.rb#L25
