### ISSUE TITLE
High-level rule to compare nested values

### ISSUE THREAD

**Issue by chikamichi** [dry-rb/dry-validation#287]
Hi,

I have a somewhat advanced (?) use-case I have not been able to solve by looking at the documentation, specs and issues. I would gladly take insights :)

Here it goes. The data to be validated looks like this:

``` ruby
{
  foo: 'bar',
  # some more key: value pairs…
  areas: [
    {
      side_id: 42,
      # some more key: value pairs…
    },
    {
      side_id: 43,
      # some more key: value pairs…
    }
  ],
  items: [
    {
      product_id: 1
      # some more key: value pairs…
    },
    {
      product_id: 2
      # some more key: value pairs…
    },
    # … some more items
  ]
}
```

I need to check for cross-ids consistency, with the added constraint that some ids are not part of the raw data (but must be fetched from a database through relationships). Specifically:
- the first item in `items` is considered the "default item"
- the default item has a product_id, which references a `Product` record in a database
- this `Product` record has a relationship to exactly two `Side` records (say, `has_many :sides` to use a Rails-like convention)
- those `Side` records' ids *must match*, the `side_id`s from the `areas` collection in the dataset.

So with the example above, ids-wise, it's valid only if `Product(id: 1).sides.map(&:id) == [42, 43]`.

SoC being a good thing, I have two seperated schemas for `areas` and `items` where I validate for `side_id` and `product_id` presence/values, among other things:

``` ruby
required(:areas).filled(size?: 2) { each { schema(DRAWABLE_AREA_SCHEMA) }}
required(:items).filled(min_size?: 1) { each { schema(ITEM_SCHEMA) }}
```

Now, I wish to add a high-level rule to cross-check ids:

``` ruby
rule(side_id_consistency: [:areas, :items]) do
  # ?
end
```

Any hints appreciated regarding the DSL to leverage here!

**Comment by solnic** [comment]
This is not supported yet :( I'll be working on a new version of `rule` DSL, so that it's more flexible, and scenarios like yours will be supported. For now you can use `validate` block where you can use arbitrary code to perform validation, but it won't associate error messages with individual elements in `items` array (which is something to improve too).

**Comment by chikamichi** [comment]
Alright then! Thank you for the insight.

**Comment by solnic** [comment]
I marked this as a feature request, I'll be working on it before 1.0.0

**Comment by faucct** [comment]
Hello, any progress?

**Comment by flash-gordon** [comment]
It'll be supported during the ongoing rewrite, track it in https://github.com/dry-rb/dry-validation/pull/440
