### ISSUE TITLE
Documentation bug: broken link to "a rule AST"

### ISSUE THREAD

**Issue by smakagon** [dry-rb/dry-validation#290]
On this page: http://dry-rb.org/gems/dry-validation/

There is a link:

> The DSL is very abstract, it builds **a rule AST** which is compiled into an array of rule objects. This means alternative interfaces could be easily built.

This link looks like this: https://github.com/dry-rb/dry-validation/wiki/Rule-AST but when I click - it redirects me to home page of repository (https://github.com/dry-rb/dry-validation)

I hope this is the right place to post this bug.

Thanks for a great work you do with dry-rb!

**Comment by flash-gordon** [comment]
Thanks. We keep docs in a separate repo: https://github.com/dry-rb/dry-rb.org/blob/master/source/gems/dry-validation/index.html.md
For now, I removed the link but we'll be working on docs more thoroughly before 1.0 is out
