### ISSUE TITLE
Coercions not happening without form processor for query params in plain roda

### ISSUE THREAD

**Issue by HoneyryderChuck** [dry-rb/dry-validation#294]
Using the latest `0.10`, I'm integrating this gem to filter parameters coming from a plain roda app.

I've defined the following rule in my schema (or similar):

```ruby
optional(:per_page).maybe(:int?, gt?: 0, lteq?: 100)
```

Back in the roda app example, I have this line defined:

```ruby
...
# params contains {:per_page => "2"}
result = MySchema.call(params)
if (errors = result.messages).empty?
...
```

And I'm getting something like this structure: ```#<Dry::Validation::Result output={:per_page=>"2"} errors={:per_page=>["must be an integer"]}>```

which seems to be a bug, as it passes ```per_page``` to the output, but also defines it as an error.

Now, if I go back to my schema and define:

```ruby
config.input_processor = :form
```

it all works, because apparently the form processor coerces what can be coerced (?). 

I'll keep this as a workaround, but this doesn't seem (IMO) a sane default, as the purpose of putting something like dry-validation in front of serialization/storage is to validate and coerce user-input, or am I missing smth here?

**Comment by solnic** [comment]
We're going to add `Schema.Params` prior 1.0.0. For now just use `Schema.Form` even for request parameters.

> as the purpose of putting something like dry-validation in front of serialization/storage is to validate and coerce user-input, or am I missing smth here?

Coercion is very common but enabling it by default for plain schemas would be problematic, because we have different input processor types depending on the use case.

**Comment by TiagoCardoso1983** [comment]
Fair enough. Will `Schema.Params` be just an alias of `Schema.Form`, or will it contain something more general-purpose? Good to know that this has been caught up already, though.

**Comment by solnic** [comment]
I don't know yet, it's possible there will be some differences in features (ie file uploads could be Form-specific) so an alias won't be enough

**Comment by flash-gordon** [comment]
We already have this alias in the latest versions, though as of today it's an alias. Feel free to use it.
