### ISSUE TITLE
Accessing parameters inside custom predicates

### ISSUE THREAD

**Issue by vetalpaprotsky** [dry-rb/dry-validation#295]
Is there any ability to access parameters (that were passed to the schema) inside a custom predicate?
```
Dry::Validation.Form do
  configure do
    def my_predicate?
      params  # something like that
    end
  end

  required(:name).filled(:my_predicate?)
end
```
Or is there a way to pass them to the predicate?

**Comment by v-kolesnikov** [comment]
Try the following documentation for the dry-validation library:
[High-level Rules](http://dry-rb.org/gems/dry-validation/high-level-rules/)
[Custom Validation Blocks](http://dry-rb.org/gems/dry-validation/custom-validation-blocks/)
[Dynamic Predicate Arguments](http://dry-rb.org/gems/dry-validation/dynamic-predicate-arguments/)

**Comment by flash-gordon** [comment]
yep, it's on the docs
