### ISSUE TITLE
config.type_specs = true AND missing type_spec should not be allowed

### ISSUE THREAD

**Issue by kwando** [dry-rb/dry-validation#297]
```ruby 
my_schema = Dry::Validation.Form{
  required(:name).filled(:str?) # <--- whoops I forgot to specify a type
  required(:age, :int).filled
  required(:email, Types::Email).filled
}

result = my_schema.call(name: 'kwando', age: 28, email: 'kwando@example.com')
result.errors => # name => ["is missing"]
```

I would like to a) get an exception if I forget got define a type when type_specs is enabled or b) default to an "pass through" type which is not doing any coercion at all.

**Comment by flash-gordon** [comment]
Closing this since this option won't present in the next release. Type specs will be optionally inferred from type predicates.
