### ISSUE TITLE
Using dry-validation to check class attribute and / or external actor (API)

### ISSUE THREAD

**Issue by nicolas-besnard** [dry-rb/dry-validation#309]
I'd like to use dry-validation to ensure a particular class attributes is greater than an other.

For exemple:

```ruby
Dry::Validation.Schema do
  required(:contribution).filled?
  required(:payment_amount).filled(:int?)

  rule(payment_amount_is_greater_than_contribution_amount: [:contribution, :payment_amount]) do |contribution, payment_amount|
    payment_amount.gt?(value(:contribution).amount)
  end
end
```

But I got the error `ArgumentError: +amount+ is not a valid predicate name`

My second use case will be an external API call as a validator:

```ruby
Dry::Validation.Schema do
  required(:user).filled?

  rule(user_has_remote_account: [:user]) do |user|
    value(:user).remote_account?
  end
end
```

I think I can use a custom predicate for that, but I'm not sure it's the right way to do it.

Any chance someone can help me ? :)

**Comment by solnic** [comment]
`rule` uses internal DSL so you can't access normal values there. You can use `validate` instead:

``` ruby
  validate(user_has_remote_account: [:user]) do |user|
    user.remote_account?
  end
```

**Comment by nicolas-besnard** [comment]
Thanks for your quick answer ! Unfortunately, this method is not documented on your website :(

**Comment by solnic** [comment]
I'd appreciate if you could report an issue about missing docs under dry-rb/dry-rb.org project

Thanks,
Piotr
