### ISSUE TITLE
"Input Processing" with options

### ISSUE THREAD

**Issue by hqm42** [dry-rb/dry-validation#317]
Lets say I want to constrain users of my saas app to modify only models of their own client:

```ruby
result = AddItemToBucketSchema.
         with(client: current_user.client).
         call({bucket_id: '123', item_id: '456'})
```

I have to validate that the `bucket` and `item` belong to the given `client`. I also want to use input processing to prefetch the `bucket` and the `item` and store them in the output of the validation to do something like this:

```ruby
if result.success?
  bucket_instance = result[:bucket_id]
  item_instance = result[:item_id]
  bucket_instance.add_item(item_instance)
end
```

I figured out how to load the model instances using `Dry::Types` but I was not able to inject the current `client` into the type constructor.

**Comment by Kukunin** [comment]
Have you seen last section here: http://dry-rb.org/gems/dry-validation/basics/working-with-schemas/. It's about DI in schemas

```ruby
schema = Dry::Validation.Schema do
  configure do
    option :my_thing

    def some_predicate?(value)
      my_thing.is_it_ok?(value)
    end
  end
end

schema.with(my_thing: MyThing).call(input)
```

**Comment by solnic** [comment]
This will be easily doable using the new `rule` system in 1.0.0.
