### ISSUE TITLE
Form schemas do not reject :float? validation when values are already numeric

### ISSUE THREAD

**Issue by rfestag** [dry-rb/dry-validation#320]
I am writing an application that accepts data in multiple formats (url form encoded and json in particular). Using Dry::Validations.Form seems to work the best, but it doesn't behave quite as expected on data I have already parsed from JSON. In particular, I have something like this:

```ruby
ProductSchema = Dry::Validation.Form do
  required(:name).filled(:str?)
  required(:description).filled(:str?)
  required(:stock).filled(:int?)
  required(:pack_size).filled(:int?)
  required(:pack_cost).filled(:float?)
end
```

The :int? requirements do not appear to be honored properly when I pass it a hash parsed from JSON. If I pass it a float (say {..., stock: 10.1...}, I the value appears to be coerced to an integer. However, when I pass it a hash parsed from URI encoded form data (say {..., stock: "10.1", ...}, it does appear to behave correctly (ie, it detects the value is not an integer, and fails validation). 

I have tried switching to using the JSON validator, but that obviously doesn't work with the form data (since all of the values are strings, so all numeric validators fail). I really don't want to define the same schema twice just to support multiple formats, so I think my only option is to use the Form validator.

Based on current behavior, I think the best solution is to update the Form validator to check that, if a numeric value is passed, it still passes validation . It already properly accepts/coerces other values (for instance, if I have a :str? validator, and pass it a numeric value, it converts to a string). The only case I've seen an issue with so far is when a float is passed as a value to a field with an :int? validator. I'd be happy to create a pull request if somebody could point me where to look...I quickly skimmed through and didn't see anything obvious.

**Comment by AndKiel** [comment]
I've got something similar but I'm using `dry-validation` with `reform`.

My problem is that `int?` together with `gt?` allows Float value to pass validation which is unexpected.

```ruby
class WhateverForm < Reform::Form
  property :max_count

  validation do
    required(:max_count).filled(:int?, gt?: 0)
  end
end

RSpec.describe WhateverForm do
  subject { described_class.new(Whatever.new) }

  it 'validates numericality of max count' do
    result = subject.validate(max_count: 2.5)
    expect(subject.errors[:max_count]).to_not be_empty
  end
end
```

The test above does not pass as `errors[:max_count]` is empty.

**Comment by flash-gordon** [comment]
I don't think that's the right approach to take. Nothing stops you from reusing the same definition across different forms, it's totally possible with the current dry-validation release

```ruby
definition = proc do
  required(:name).filled(:str?)
  required(:description).filled(:str?)
  required(:stock).filled(:int?)
  required(:pack_size).filled(:int?)
  required(:pack_cost).filled(:float?)
end

ProductFormSchema = Dry::Validation.Form(&definition)
ProductJSONSchema = Dry::Validation.JSON(&definition)
# and then choose the right schema depending on the request format
```

That's more robust way IMO, I use it in my code.
