### ISSUE TITLE
Pass arguments to errors in YAML

### ISSUE THREAD

**Issue by igor-alexandrov** [dry-rb/dry-validation#321]
Here is what I have in my errors file:

```yml
en:
  errors:
    not_a_date?: "is not a date"
    after?: "must be after %{date}"
    after_or_equal_to?: "must be after or equal to %{date}"
```

I also added custom predicate:
```ruby
module Lion
  module Predicates
    include Dry::Logic::Predicates

    predicate(:after_or_equal_to?) do |value, current|
      current >= value
    end
  end
end
```

Currently if current value is less then required date it returns false, but I need to pass `:date` key to populate my error.

Don't understand how this can be done.
Thanks.

**Comment by solnic** [comment]
This will be supported OOTB with the new rule API in 1.0.0
