### ISSUE TITLE
Error for unknown custom rules dependencies

### ISSUE THREAD

**Issue by cutalion** [dry-rb/dry-validation#328]
Here is an example.

```ruby
schema = Dry::Validation.Schema do
  required(:x).filled(:int?)

  validate(with_option: [:x, :foo]) do
    raise 'will not be raised'
  end
end

result = schema.(x: 1)
puts result.success? #=> true
```
Would be nice to check dependencies and warn user about unknown keys. It may be hard to notice typo in deps without any errors.

**Comment by solnic** [comment]
high level rules in schemas will be gone in 1.0.0 so I'll make sure this will be addressed in the new API

**Comment by solnic** [comment]
This won’t be addressed as this dsl was removed in dry-schema which will be schema backend in dry-validation 1.0
