### ISSUE TITLE
String keys support

### ISSUE THREAD

**Issue by khataev** [dry-rb/dry-validation#330]
If i try to use optional element with schema declaration i get an error:

```
NoMethodError: undefined method `visit_1' for #<Dry::Types::Compiler:0x005613a459dfb8 @registry=Dry::Types>
Did you mean?  visit
from /home/andrey/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/dry-types-0.10.3/lib/dry/types/compiler.rb:15:in `visit'
```

```ruby
class Declaration

  def self.validate(json)
    DeclarationSchema.call(JSON.parse(json)).messages
  end

  private

  DeclarationSchema = Dry::Validation.JSON do
    required(:dev).schema do
      required('1').each do
        schema do
          optional('1.1').schema do
            required(:value).filled(:str?)
          end
        end
      end
    end
  end

end

str = <<-EOT
{
  "dev": {
    "1": [{
      "1.1": {
        "1.1.1": {
          "value": "aaaaaaaaaaaaaaa"
        },
        "1.1.2": {
          "value": "aaaaaaaaaaaaaaaa"
        },
        "1.1.3": {
          "value": "aaaaaaaaaaaaaaaa"
        },
        "comment": {
          "value": "aaaaaaaaaaaaaaaa"
        }
      }
    }]
  }
}
EOT

Declaration.validate(str)
```

**Comment by kimquy** [comment]
@khataev can you share the error. I just run the script above on the latest version & seem no problem for me.

**Comment by khataev** [comment]
@kimquy excuse me first version of post was with wrondg contents, updated

**Comment by kimquy** [comment]
yeah! I did some debugging. Think that this is a 🐛 ! It raised the exception from `dry-types compiler` however I think it come from the `optional`

**Comment by khataev** [comment]
@kimquy Yes, it works fine with `required`, but with `optional` don't. It seems to me such an obvious case, strange to find bug there. Maybe there is another syntax for validating optional object in JSON?

**Comment by solnic** [comment]
What if you use symbols as key names instead of strings?

**Comment by kimquy** [comment]
@solnic just test against symbols & seem work fine.

**Comment by solnic** [comment]
We shouldn't allow non-symbol key names :/ In case of Form and JSON the output gets symbolized and string keys are assumed in the input.

**Comment by khataev** [comment]
@solnic, @kimquy yep, it works with symbols, but it looks like a bit ugly if key is a number or starts with number:
```ruby
optional(:'1.1.1').schema do
  required(:value).filled(:str?)
end
```

thanks!

**Comment by solnic** [comment]
Please stick to it for now, we can look into supporting string keys in the near future.

**Comment by khataev** [comment]
no problem ;)

**Comment by solnic** [comment]
This will be improved via https://github.com/dry-rb/dry-schema/issues/29
