### ISSUE TITLE
high level rules are onerous to debug

### ISSUE THREAD

**Issue by lastobelus** [dry-rb/dry-validation#334]
### Can't Log

```ruby
rule(whatever: [:blah]) do | blah|
  puts "value(:blah): #{value(:blah).inspect}"
  blah.filled?
end
```

Results:
```
dry-validation-0.10.5/lib/dry/validation/predicate_registry.rb:106:in `raise_unknown_predicate_error': +puts+ is not a valid predicate name (ArgumentError
```

### Can't debug

```ruby
rule(whatever: [:blah]) do | blah|
  byebug
  blah.filled?
end
```

Results:

nothing -- never drops into byebug.

**Comment by lastobelus** [comment]
I guess they are both being executed at load time anyway, not when validation is actually being run.

Is there any way to debug the execution of a custom rule?

**Comment by solnic** [comment]
rule blocks are basic objects so you can use `::Kernel.byebug` to put a breakpoint inside these blocks.

**Comment by roman-glebov** [comment]
Any luck with that? `::Kernel.byebug` stops only at the time of definition of the rule, application of the rule is still blackbox for me :)

**Comment by solnic** [comment]
@roman-glebov what do you want to debug? the only thing that happens is execution of predicates, so you can put a breakpoint there

**Comment by roman-glebov** [comment]
```
rule(whatever: [[:foo, :bar], :baz, :blah]) do |bar, baz, blah|
  ::Kernel.byebug
  bar.eql?('something') | baz.eql?(false) | blah.eql?(true)
end
```

I tried to debug the rule block. I do debug successfully inside predicates. But sometimes I don't need to create new predicate. I just use default predicates and want to have ability to take a look at the values inside the rule.

**Comment by flash-gordon** [comment]
Closing since this kind of rule will be removed in the next version.
