### ISSUE TITLE
syntax error with xor, then

### ISSUE THREAD

**Issue by jodeci** [dry-rb/dry-validation#336]
Original discussion:
https://github.com/trailblazer/reform/pull/435

According to the guides, I should be able to use the following syntax:
http://dry-rb.org/gems/dry-validation/basics/predicate-logic/

```
Dry::Validation.Schema do
  required(:age) { filled? then int? }
end
```

However, in practice, using `then`, `xor` will result in a syntax error. Reproducible with:
https://github.com/dry-rb/dry-validation/blob/master/spec/integration/schema/xor_spec.rb#L17
https://github.com/dry-rb/dry-validation/blob/master/spec/integration/injecting_rules_spec.rb#L6

**Comment by solnic** [comment]
In ruby operators are methods that can be called without `.`, `then`, `xor` are not operators so you need a dot ie `filled?.then(int?)`
