### ISSUE TITLE
#to_either raises exception when used with schemas

### ISSUE THREAD

**Issue by bernardeli** [dry-rb/dry-validation#337]
I may have hit a bug in dry-validations while using it with monads and structs. 

I currently have a value object and am running validations re-using them. It's expected to return a Left, however, with no inputs provided, it blows up.

```ruby
require "dry-struct"
require "dry-types"
require "dry-validation"

module Types
  include Dry::Types.module
end

Dry::Validation.load_extensions(:monads)
Dry::Validation.load_extensions(:struct)

class Flags < Dry::Struct::Value
  attribute :admin, Types::Strict::Bool
end

PersonValidation = Dry::Validation.Schema {
  required(:name).filled(:str?)
  required(:flags).schema(Flags)
}

output = PersonValidation.call({})

puts output.to_either

=> /Users/ric/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/dry-validation-0.10.7/lib/dry/validation/message_set.rb:113:in `[]': no implicit conversion of Symbol into Integer (TypeError)
```

The expectation of the Left is the following:

```ruby
Left({:name=>["is missing"], :flags=>["is missing"]})
```

Let me know if it needs further details and how I can help.

Thanks,
Ricardo

**Comment by Bugagazavr** [comment]
I have same problem https://gist.github.com/Bugagazavr/c4db936718c3bed53d9125507b300743

**Comment by flash-gordon** [comment]
This duplicates https://github.com/dry-rb/dry-validation/issues/356
