### ISSUE TITLE
Required attribute without predicates doesn't error as expected when missing

### ISSUE THREAD

**Issue by jamesottaway** [dry-rb/dry-validation#339]
I have a simple schema which includes one required attribute:

``` ruby
schema = Dry::Validation.Schema do
  required(:foo)
end
```

When I call it without a `foo` key I don't get any errors:

``` ruby
schema.call({}).errors   # => {}
```

I would've expected an "is missing" error in there.

If I extend the schema to add a predicate to the `required(:foo)` part and try again I get the expected error:

``` ruby
schema = Dry::Validation.Schema do
  required(:foo).filled
end

schema.call({}).errors   # => {:foo=>["is missing"]}
```

Confirmed in v0.10.7 FWIW.

**Comment by flash-gordon** [comment]
Will be fixed in the next version:
```ruby
schema = Dry::Schema.define do
  required(:foo)
end
2.6.1 :001 > schema.({})
 => #<Dry::Schema::Result{} errors={:foo=>["is missing"]}> 
```
