### ISSUE TITLE
undefined method `visit_type' with dry-types 0.11.0

### ISSUE THREAD

**Issue by MarcPer** [dry-rb/dry-validation#346]
`dry-validation` crashes with the newest `dry-types`. I have checked and this doesn't happen for `dry-types` versions before `0.11.0`.

Here is a small script to reproduce this error:
```ruby
require "dry-validation"

module Test
  include Dry::Logic::Predicates
end

Dry::Validation.Form do
  configure { predicates Test }
end
```

And here is the stack trace:
```
NoMethodError: undefined method `visit_type' for #<Dry::Types::Compiler:0x00000001657920 @registry=Dry::Types>
Did you mean?  visit
               visit_safe
        from /usr/local/bundle/gems/dry-types-0.11.0/lib/dry/types/compiler.rb:16:in `visit'
        from /usr/local/bundle/gems/dry-types-0.11.0/lib/dry/types/compiler.rb:11:in `call'
        from /usr/local/bundle/gems/dry-validation-0.10.7/lib/dry/validation/input_processor_compiler.rb:16:in `call'
        from /usr/local/bundle/gems/dry-validation-0.10.7/lib/dry/validation/schema/deprecated.rb:14:in `input_processor'
        from /usr/local/bundle/gems/dry-validation-0.10.7/lib/dry/validation/schema/class_interface.rb:165:in `default_options'
        from /usr/local/bundle/gems/dry-validation-0.10.7/lib/dry/validation/schema/class_interface.rb:35:in `new'
        from /usr/local/bundle/gems/dry-validation-0.10.7/lib/dry/validation.rb:23:in `Schema'
        from /usr/local/bundle/gems/dry-validation-0.10.7/lib/dry/validation.rb:29:in `Form'
        from (irb):7
        from /usr/local/bin/irb:11:in `<main>'
```

**Comment by GustavoCaso** [comment]
Thanks for reporting I will have a look ASAP

**Comment by GustavoCaso** [comment]
@MarcPer I have tried your code with the latest version and it works.

I just bundle install everything from scratch
![image](https://user-images.githubusercontent.com/4672858/27842679-61885510-610c-11e7-9227-968ac7759782.png)
check `dry-types 0.11.0`

and using the console
![image](https://user-images.githubusercontent.com/4672858/27842700-95d59c6a-610c-11e7-8169-940e9fdfc09b.png)

Maybe I'm missing something

**Comment by MarcPer** [comment]
@GustavoCaso, I see you used `dry-validation (0.11.0)`. The problem happened to me while using `dry-validation (0.10.7)`. The latter has accepts `dry-types (0.11.0)` as a dependency as well because you have in the *gemspec*:
```ruby
spec.add_runtime_dependency 'dry-types', '~> 0.9', '>= 0.9.0'
```

Anyway, I am glad this is fixed already on `dry-validation (0.11.0)`. And thank you for the quick response.

**Comment by GustavoCaso** [comment]
@MarcPer can we close the ticket?

**Comment by MarcPer** [comment]
Yes, of course. Sorry
