### ISSUE TITLE
Getting keys names of nested settings easier

### ISSUE THREAD

**Issue by mensfeld** [dry-rb/dry-validation#347]
Hey, before I do the configuration of settings, I need to get the keys or a nested config to do some metaprogramming (based on the nested settings key names I build a DSL for Karafka). For now I use something like that:

```ruby
Karafka::Setup::Config._settings.find {|s| s.name == :kafka}.value.instance_variable_get('@klass').settings
```

It would be super helpful to be able to get those names easier.

**Comment by solnic** [comment]
This is now provided by `key_map` feature in dry-schema.
