### ISSUE TITLE
X or Y filled?

### ISSUE THREAD

**Issue by BarakHarizi** [dry-rb/dry-validation#352]
Hey,
I'm using Dry Validations in my project.
I'm trying to figure out how to achieve the following:
require either X or Y to be filled, meaning you should have at least one of the two filled.
I was looking at High-level Rules and tried to do the following:
```
rule(x_or_y_filled: [:x, :y]) do |x, y|
   x.filled? | y.filled?
end

```
but it doesn't seem to enforce the behaviour I desire.
Any ideas?

**Comment by AMHOL** [comment]
@BarakHarizi I think the exclusive or (XOR`^`) operator should work for that:

```rule(x_or_y_filled: [:x, :y]) do |x, y|
   x.filled? ^ y.filled?
end

**Comment by AMHOL** [comment]
@BarakHarizi you need to define the schema for the key/value pairs for this to work:

```ruby
require 'bundler/inline'

gemfile(true) do
  source 'https://rubygems.org'

  gem 'dry-validation'
end

schema = Dry::Validation.Schema do
  optional(:x).maybe(:int?)
  optional(:y).maybe(:int?)

  rule(x_or_y_filled: [:x, :y]) do |x, y|
    x.filled? & y.filled?
  end
end

schema.(x: 1, y: 1)
# => #<Dry::Validation::Result output={:x=>1, :y=>1} errors={}>
schema.(x: 1)
# => #<Dry::Validation::Result output={:x=>1} errors={:x_or_y_filled=>["must be filled"]}>
schema.({})
# => #<Dry::Validation::Result output={} errors={:x_or_y_filled=>["must be filled"]}>
```

It should probably error in a scenario where a rule is defined with nothing to infer the schema or type specs, not sure whether that will change with https://discourse.dry-rb.org/t/plans-for-dry-validation-dry-schema-a-new-gem/215 but that's one for @solnic

**Comment by BarakHarizi** [comment]
@AMHOL thanks man!
I was missing this part:
```
optional(:x).maybe(:int?)
optional(:y).maybe(:int?)
```
didn't know you are required to first define the two as optionals.
You just saved me a lot of time! thanks again! :)

**Comment by AMHOL** [comment]
@BarakHarizi NP :smile:
