### ISSUE TITLE
Wrong translation key for rules

### ISSUE THREAD

**Issue by raykov** [dry-rb/dry-validation#353]
This line https://github.com/dry-rb/dry-validation/blob/58699acf23d3c101e01662a8633197ca39b68696/lib/dry/validation/messages/abstract.rb#L58 generates translation keys like `%{locale}.rules.name` for `Dry ::Validation::Messages::I18n`. And can't find translation with this key. It looks like we should have `translation.yml` like this

```
en:
  "%{locale}":
    rules:
      name: Name
```

For `Dry ::Validation::Messages::YAML` it works fine, because here we have `key % { locale: :en}`
https://github.com/dry-rb/dry-validation/blob/58699acf23d3c101e01662a8633197ca39b68696/lib/dry/validation/messages/yaml.rb#L38

So, we need to fix this for `Messages::I18n`

Also we need to provide ability use namespaces for `rules`

**Comment by regedarek** [comment]
hi

**Comment by solnic** [comment]
This was fixed in dry-schema, thus it'll be fixed here in 1.0.0.
