### ISSUE TITLE
Documentation doesn't clearly state that Input Preprocessing doesn't work on a schema

### ISSUE THREAD

**Issue by ericschultz** [dry-rb/dry-validation#357]
I'm a new user of Dry-validation and I was confused for hours about why my input preprocessing constructor (as described in http://dry-rb.org/gems/dry-validation/input-preprocessing/) wasn't called. I discovered upon reading a few more times that if you use a Schema, there's no input preprocessing. It is implied I suppose by saying on http://dry-rb.org/gems/dry-validation/input-preprocessing/ that "Prior to validation, we need to coerce values and symbolize keys based on the information in the rules" but it should be clearer in the input preprocessing documentation.

**Comment by flash-gordon** [comment]
The docs will be massively updated before the next release. The things about processing are going to change significantly, you can read it about on the Piotr's [announce](https://solnic.codes/2019/01/31/introducing-dry-schema/) of dry-schema. Also, we keep docs in a separate repo https://github.com/dry-rb/dry-rb.org
