### ISSUE TITLE
Default Schema don't filter undescribed params

### ISSUE THREAD

**Issue by semenovDL** [dry-rb/dry-validation#366]
```ruby
require 'dry-validation'

schema = Dry::Validation.Schema do
  required(:email).filled(:str?)
end

validated =  schema.call(email: 'admin@google.com', password: 'hackyou')
puts validated.success? # => true
puts validated.output # => {:email=>"admin@google.com", :password=>"hackyou"}
```

**Comment by PavelTkachenko** [comment]
I think that such behavior is OK. Because we do not specify that any other params should be filtered. Maybe it is good idea to implement such DSL:

```ruby
schema = Dry::Validation.Schema do
  method :default # as it used to be
  method :strict # makes :success? to be false if any not declared keys are present
  method :filter # just filters keys not declared keys
end
```

**Comment by PavelTkachenko** [comment]
This is considered as bug
#66

**Comment by kurko** [comment]
Yep. I arrived here after looking at #66. Add `config.input_processor = :sanitizer`.

**Comment by flash-gordon** [comment]
This will be the default behavior in the next release

**Comment by mengqing** [comment]
I thought `sanitizer` is already the default setting but apparently its not. Is there a way to set this as the default setting without having to create a base schema that every other schemas have to nest with?

**Comment by solnic** [comment]
@mengqing no, you either configure it in each schema, or use a base schema and inherit from it

**Comment by mengqing** [comment]
@solnic Thanks for the quick reply
