### ISSUE TITLE
Form processor with type specs doesn't coerce int arrays inside hashes

### ISSUE THREAD

**Issue by Morozzzko** [dry-rb/dry-validation#369]
If you use `Dry::Validation:Form` with `type_specs = true` and arrays inside hashes (see example below), it won't coerce the values inside the array and fail instead.

```ruby
        Dry::Validation.Form do
          configure do
            config.type_specs = true
          end

          required(:foo).schema do
            required(:bar, :array).each(:int?)
          end
        end
```

There are two workarounds I have found:

1. Don't use the type_specs (duh) (*probably not a good solution*)
2. Define a type similar to `IntArray = Dry::Types['form.array'].of(Dry::Types['coercible.int'])` and use it in the validation block (`required(:bar, IntArray).each(:int?)`)

This seems like a bug, so I'm opening this issue

UPD: wrote [some tests](https://gist.github.com/Morozzzko/aa269cc30ba847b72169a8ebe08f267f) to demonstrate both the problem and the 2nd ~~solution~~ workaround

**Comment by flash-gordon** [comment]
It's not obvious how it should work in dry-schema
```ruby
required(:bar).value(:array).each(Types::Params::Integer, :int?)
```
throws an error

**Comment by flash-gordon** [comment]
probably related to https://github.com/dry-rb/dry-validation/issues/424 and https://github.com/dry-rb/dry-validation/issues/291

**Comment by solnic** [comment]
@flash-gordon re your example, please report an issue in dry-schema, and here's what should work:

``` ruby
required(:bar).value(array[:integer]).each(:int?)
```

**Comment by flash-gordon** [comment]
ref https://github.com/dry-rb/dry-schema/issues/21
