### ISSUE TITLE
Arity mismatch when using splat in custom validation block 

### ISSUE THREAD

**Issue by stefkin** [dry-rb/dry-validation#371]
I have a schema with a bunch of optional fields (23 to be exact). I need to check if at least on of the fields is filled. 

I figured I could use a custom validation block. Something like:

```
  validate(has_some_value: DECIMAL_FIELDS) do |*fields|
    fields.any? { |field| !field.nil? }
  end
```

But I ended up with the following error:
ArgumentError: wrong number of arguments (23 for -1)

It pops up in dry-logic's curry rule which makes sense at the first glance.

I ended up using the following rule instead:

```
  rule(any_value_filled: DECIMAL_FIELDS) do |*fields|
    fields.reduce(fields.first.filled?) { |acc, f| acc | f.filled? }
  end
```

splat works fine here, no errors.

It led me to think that custom validation behavior might be a bug

**Comment by flash-gordon** [comment]
Both APIs will be changed in the next release, see https://github.com/dry-rb/dry-validation/pull/440
