### ISSUE TITLE
Nested schemas with dependency fails 

### ISSUE THREAD

**Issue by groyoh** [dry-rb/dry-validation#373]
## Expected behavior

When using nested schemas, I'd expect parent schema to pass down the `option` configuration down to the nested schemas so that we can use the `option` within predicate that are used by the nested schemas.

Here is an example:

```ruby
begin
  require 'bundler/inline'
rescue LoadError => e
  $stderr.puts 'Bundler version 1.10 or later is required. Please update your Bundler'
  raise e
end

gemfile(true) do
  source 'https://rubygems.org'
  gem 'dry-validation', '~> 0.11'
end

schema = Dry::Validation.Schema do
  configure do
    option :email_check
    option :postal_code_check, -> { ->(input) { input.length == 6 } }

    def email?(value)
      email_check.call(value)
    end

    def postal_code?(value)
      postal_code_check.call(value)
    end
  end

  required(:email).filled(:email?)
  optional(:address).schema do
    optional(:postal_code).filled(:postal_code?)
  end
end

email_check = ->(input) { input.include?('@') && input.end_with?('.com') }
input = {
  email: 'foo@bar.com',
  address: {
    postal_code: '123456722'
  }
}
result = schema.with(email_check: email_check).call(input)
```

## Actual behavior

In the case where the parent `option` has no default value and the nested schema `option` has a a default value, it actually raises an error `dry_valid.rb:24:in `postal_code?': undefined method `call' for nil:NilClass (NoMethodError)`.

This happens because [here](https://github.com/dry-rb/dry-validation/blob/master/lib/dry/validation/schema_compiler.rb#L67) the `opt_vals` won't be empty 
 since we pass the parent dependency. Then `Hash[opt_keys.zip(opt_vals)]` will `zip` over all the option keys, it will find a value for the parent dependency but none for the nested schema dependency and therefore setting the nested schema dependency to `nil`.

**Comment by solnic** [comment]
This type of functionality is being removed in 1.0.0. You'll be able to leverage the new rule API to achieve the same thing and a simpler way.
