### ISSUE TITLE
Order of type specs in form schema changes string coercion behaviour

### ISSUE THREAD

**Issue by timriley** [dry-rb/dry-validation#376]
A form schema with type specs defined like so will coerce a `""` to `nil` (which is the correct behaviour):

```ruby
schema = Dry::Validation.Form do
  configure do
    config.type_specs = true
  end

  required(:title, [:nil, :string]).maybe
end

schema.("title" => "")[:title]
# => nil
```

But if the type spec is provided as `[:string, :nil]` (i.e. in the opposite order), `""` is not coerced:

```ruby
schema = Dry::Validation.Form do
  configure do
    config.type_specs = true
  end

  required(:title, [:string, :nil]).maybe
end

schema.("title" => "")[:title]
# => ""
```

This is a really subtle change in behaviour and could result in empty strings getting written to database columns for blank input instead of leaving them as NULL.

We should make it so that the appropriate form coercions apply regardless of the order of types, at least for the common case of nullable types.

**Comment by FunkyloverOne** [comment]
Guys, it looks like you have this bug for a while, I've caught it just now, and it is really unexpected behavior. In my case it was `[:bool, :string, :integer]` - successfully coerces `1` or `'1'` to `true`, while `[:string, :integer, :bool]` fails! Kinda crazy.

**Comment by flash-gordon** [comment]
I reported it to dry-schema, track it there https://github.com/dry-rb/dry-schema/issues/28
