### ISSUE TITLE
Strict whitelisting for keys

### ISSUE THREAD

**Issue by ilnurnasyrov** [dry-rb/dry-validation#377]
it is known which fields would be passed to api. But i don't known, how to make schema more strict.

I want something like this
```ruby
Contract = Dry::Validation.JSON {
  required(:id).filled
}

Contract.call(id: 1, qwe: 1) #=> #<Dry::Validation::Result output={:id=>1} errors={:qwe=>['unknown field']}>
```

**Comment by danlo** [comment]
See: https://github.com/dry-rb/dry-validation/issues/115

**Comment by flash-gordon** [comment]
It will be the default behavior in the next release

**Comment by nowakov** [comment]
@flash-gordon Hey. Can we get an ETA on the next release? We have a feature that depends on this functionality and I'm not sure if we should wait or try to implement it on our own.

Thanks :)

**Comment by solnic** [comment]
@nowakov this will be available in dry-schema/validation 2.0.0. ETA is ~March.

**Comment by kelvinlzhang** [comment]
@solnic @flash-gordon same question as @nowakov, do you guys have an updated ETA?

**Comment by solnic** [comment]
@kelvinlzhang no, not really, most likely before the end of the year though
