### ISSUE TITLE
How to reuse schema in array element validation?

### ISSUE THREAD

**Issue by anfinil** [dry-rb/dry-validation#380]
How can I reuse schema to validate array item? Like
```
Schema = Dry::Validation.Schema do
  required(:items).each do
    schema(ArrayItemSchema)
  end
end
```

**Comment by danzanzini** [comment]
try this: `required(:items).filled { each(ArrayItemSchema) } `

**Comment by mkristian** [comment]
this was my saviour `Dry::Validation.Schema do required(:addresses).maybe { each(AddressSchema) }; end`

@anfinil did solve your problem ?

**Comment by flash-gordon** [comment]
It will work like this in the next version
```ruby
Form = Dry::Schema.Params do
  required(:bar).type(:integer).value(:int?)
end

FormContainer = Dry::Schema.Params do
  optional(:foo).value(:array).each(Form)
end
```
though we still have an unresolved issue https://github.com/dry-rb/dry-schema/issues/25
