### ISSUE TITLE
[BUG] type coercion  in Dry::Validation.Form does not work with ActionController::Parameters

### ISSUE THREAD

**Issue by blaszczakphoto** [dry-rb/dry-validation#389]
I have a following schema:
```ruby
SignUpForm = Dry::Validation.Form do
  configure do
    config.type_specs = true
  end

  optional(:date_of_birth, :date).filled(:date?)
end

params = ActionController::Parameters.new(date_of_birth: '2000-10-23')
```

And when I call:
```ruby
result = SignUpForm.call(params).output
```

I expect the `result` variable to be eq to:
```ruby
expected_result = {
  date_of_birth: Date.new(2000, 10, 23)
}
```

But instead I got:
```ruby
(byebug) result.errors
{:date_of_birth=>["must be a date"]}
```

It works well with the `Hash` instead of `ActionController::Parameters`. I found a workaround:
```ruby
params.to_unsafe_hash
```

**Comment by slecorvaisier** [comment]
Hi, I have the same issue with the following
```
SignUpSchema = Dry::Validation.Params(BaseSchema) do
  required(:accept_terms).filled(:bool?, :true?)
end

params = ActionController::Parameters.new("accept_terms"=>"1")

SignUpSchema.call(params)
```

will returns
```
errors={:accept_terms=>["must be boolean"]}
```

It also works when converting the ActionController::Parameters into a hash:
```
SignUpSchema.call(params.to_h)
```

**Comment by flash-gordon** [comment]
I don't see how this is a bug. dry-validation/dry-schema work with ruby hashes, not `ActionController::Parameters`, as in, we don't have any specs for it neither we want to. Convert your input to hashes before validating.

**Comment by solnic** [comment]
I should add that for this type of functionality we can have `dry-validation-rails`.
