### ISSUE TITLE
Defining error message for custom predicate inside a module

### ISSUE THREAD

**Issue by davebream** [dry-rb/dry-validation#390]
Hi there.

Is it possible to define the error message inside a module with custom predicate? I need to define part of the message basing on the constant inside the module.

E.g. of the situation that I'm in:

```ruby
module CancellationPredicates
  include Dry::Logic::Predicates

  ADVANCE_IN_DAYS = [7, 14].freeze # I want to use ADVANCE_IN_DAYS inside the error message

  predicate(:predefined_free_cancellation_advance?) do |value|
    ADVANCE_IN_DAYS.include?(value)
  end
end
```

**Comment by roman-glebov** [comment]
Not sure if it is possible.
But you can pass `ADVANCE_IN_DAYS ` into predicate as argument inside a rule:

```
rule(:blabla) do
  value(:some_value).predefined_free_cancellation_advance? ADVANCE_IN_DAYS
end
```

And predicate then will look like

```
predicate(:predefined_free_cancellation_advance?) do |advance_in_days, value|
  advance_in_days.include?(value)
end
```

And then use `advance_in_days` in error messages file:

`this error message is using %{advance_in_days}`

**Comment by davebream** [comment]
@roman-glebov Is it possible to extract the rule to a module or sth so it is reusable across multiple schemas?

**Comment by roman-glebov** [comment]
@davebream As far as I know, nope. But you can create some base schema class with common rules http://dry-rb.org/gems/dry-validation/basics/working-with-schemas/

**Comment by davebream** [comment]
@roman-glebov Thanks!
