### ISSUE TITLE
Where to put schemas when using engines.

### ISSUE THREAD

**Issue by nmammeri** [dry-rb/dry-validation#397]
Hi 
I have all my models inside an engine that is shared between a front-app and an admin-app. I managed to keep all models and migrations inside the engine.

Have you guys thought about this use case?  Where should all my schemas live inside my engine? Of course I want to stay DRY and keep the schemas in in my shared engine and use them in both my front and admin apps.  With activemodel the validations live inside the models themselves so this not a problem.

Thanks

**Comment by flash-gordon** [comment]
Please, ask questions on our forum https://discourse.dry-rb.org/

Personally, I don't care if code is duplicated as far as it is used in different contexts. Trying to unify validation schemas can go against the application architecture and bring more pain than save you typing.
