### ISSUE TITLE
Reconsider default error message of confirmation macro

### ISSUE THREAD

**Issue by kaikuchn** [dry-rb/dry-validation#401]
Greetings,

Implementing a user signup form in Hanami, @nerdinand noticed that the default error message for the confirmation macro is rather unfortunate for passwords.

A common use case for the confirmation macro is to use it for verifying a user did not mistype some pass phrase. The default error message when the confirmation value does not match, prints the value that should've been matched.
That is problematic in the context of pass phrases where you would not want to echo it back to the user (otherwise: why even bother using a password input field etc).

I realise that secrets are not the only thing one may confirm, e.g., sometimes people want you to confirm your e-mail address. But I'd argue that most commonly it is used for passwords and that a safe default message in the form of `does not match` suffices for all use cases.
I am, however, unsure if it is even possible to change the current default message since `confirmation` is a macro?

Anyway, wanted to let you know about this and hear your thoughts on the matter.

Best regards,
Kai

**Comment by daniels** [comment]
I think this is a good idea.

I think the current message comes straight from `eql?` in the expanded rule, so I guess it's not possible to change _only_ the default message. But could there be a special `confirms?` (or `matches?` or whatever) predicate, with the same logic but a different message?

**Comment by solnic** [comment]
Closing because `confirmation` is going away in the 1.0.0 rewrite
