### ISSUE TITLE
TypeError defining a schema with an input_processor and array input

### ISSUE THREAD

**Issue by rhec** [dry-rb/dry-validation#402]
I'm trying to restrict the output keys in an array of hashes to those defined in the schema using the `sanitizer` input processor.

I added a spec to reproduce the error on this branch:
https://github.com/dry-rb/dry-validation/compare/master...rhec:bug-input-processor-with-array-input

The output of the spec is:
```
1) Dry::Validation::Schema for an array with input_processor = :sanitizer sanitizes output keys
     Failure/Error: type_compiler.(hash_node(schema_ast(ast)))
     
     TypeError:
       no implicit conversion of Dry::Types::Array::Member into Hash
     # ./lib/dry/validation/input_processor_compiler.rb:17:in `call'
     # ./lib/dry/validation/schema/deprecated.rb:14:in `input_processor'
     # ./lib/dry/validation/schema/class_interface.rb:166:in `default_options'
     # ./lib/dry/validation/schema/class_interface.rb:36:in `new'
     # ./lib/dry/validation.rb:23:in `Schema'
     # ./spec/integration/schema/array_schema_spec.rb:62:in `block (3 levels) in <top (required)>'
     # ./spec/integration/schema/array_schema_spec.rb:76:in `block (3 levels) in <top (required)>'
```

It doesn't appear to be specific to the `sanitizer` input_processor. `json` and `form` also fail, so I think it's array input and input_processors in general that don't work. I'd be happy to dig deeper, but fact that input_processor is in a file called `deprecated` and not mentioned in the docs makes me think I should ask first if there is another way to do this.

**Comment by pmackay** [comment]
@rhec did you get any further solving this? I'm finding a similar problem.

**Comment by rhec** [comment]
@pmackay no I'm simply looping through my array data and applying a schema individually to each item instead as a workaround. I never got confirmation, but my suspicion was that fixing this bug might be a waste as the `input_processor` feature seems likely to change radically or go away completely, given it's apparently deprecated.

**Comment by flash-gordon** [comment]
@rhec you're absolutely right. We're in the process of rewriting the library, input processors will be gone in the next version. At the moment, the new version doesn't have support for top-level arrays, we believe it can be added on top of the hash-first logic a little bit later (I hoper _before_ the release since it's something I need). Good news is now unkown keys are filtered out by default :) Also, track https://github.com/dry-rb/dry-validation/pull/440 for progress.
