### ISSUE TITLE
Mocking schemas in Rails controller tests

### ISSUE THREAD

**Issue by samstarling** [dry-rb/dry-validation#404]
Hello! I'm using dry-validation to validate JSON payloads in my Rails API controller, a bit like this:

```ruby
def create
  result = CreateUserSchema.call(member_params.to_hash)
  return result_as_json(result.errors) unless result.success?
  # create a user
end
```

I've got `CreateUserSchema` unit tested, so really I just want to mock `CreateUserSchema` and check that (for example) a 200 is returned when `success?` is true, and a 400 is returned when it is false. However, because it's frozen, when I try to do this:

```ruby
result = double('result', success?: true)
allow(CreateMemberSchema).to receive(:call) { result }
```

I get an error like this:
```
     RuntimeError:
       can't modify frozen object
```

Is there any way around this?

**Comment by timriley** [comment]
Hi @samstarling — we encourage you to use https://discourse.dry-rb.org/ for advice and support requests. Please go ahead and make your posts there and we'll see if someone can get back to you!

**Comment by samstarling** [comment]
@timriley Will do, thanks!
