### ISSUE TITLE
Some compatibility files are loaded from dry-types causing deprecation warnings

### ISSUE THREAD

**Issue by twe4ked** [dry-rb/dry-validation#413]
As far as I can tell we're not loading anything other than `dry-validation` in our app.

This has probably been happening for a while. There [was a bug in dry-rb](https://github.com/dry-rb/dry-core/commit/a6d0878cfd7e784c64dabb52b88b0027111d0dd4) that was hiding the problem.

**Comment by timbogit** [comment]
I am seeing these warnings as soon as I simply do this anywhere:
```ruby
require 'dry-validation'
```

Result (in our test suite, for example):
```
[dry-types] Int type was renamed to Integer
[dry-types] Form types were renamed to Params
```

From the Gemfile.lock:
```
    dry-types (0.13.2)
      concurrent-ruby (~> 1.0)
      dry-container (~> 0.3)
      dry-core (~> 0.4, >= 0.4.4)
      dry-equalizer (~> 0.2)
      dry-inflector (~> 0.1, >= 0.1.2)
      dry-logic (~> 0.4, >= 0.4.2)
    dry-validation (0.12.0)
      concurrent-ruby (~> 1.0)
      dry-configurable (~> 0.1, >= 0.1.3)
      dry-core (~> 0.2, >= 0.2.1)
      dry-equalizer (~> 0.2)
      dry-logic (~> 0.4, >= 0.4.0)
      dry-types (~> 0.13.1)
```

@twe4ked unsure this is the same thing, could you try and confirm?

**Comment by twe4ked** [comment]
Yeah, that's the same problem I'm seeing.

**Comment by flash-gordon** [comment]
Folks, I think I fixed this in master. Mind to check if it works for you?

**Comment by Morozzzko** [comment]
Tested it: no more deprecation warnings

Thank you!

**Comment by timbogit** [comment]
Confirming this fixed, as well.
Thanks @flash-gordon ! When can we expect an updated gem version to be pushed?

**Comment by flash-gordon** [comment]
today, as soon as I get the build passing
