### ISSUE TITLE
Type coercion is not working for date strings

### ISSUE THREAD

**Issue by dreikanter** [dry-rb/dry-validation#414]
I'm trying to check if a string contains valid DateTime:

``` ruby
schema = Dry::Validation.Schema do
  configure { config.type_specs = true }
  required('value', Types::Params::DateTime).filled(:date_time?)
end
```

But keep getting "must be a date time" error:

``` irb
> pp schema.call('value' => '2018-02-07T00:00:00+00:00').errors
=> {"value"=>["must be a date time"]}
```

In the same time type coercion works fine for this value:

```
> Types::Params::DateTime['2018-02-07T00:00:00+00:00']
=> Wed, 07 Feb 2018 00:00:00 +0000

> Types::Params::DateTime['2018-02-07T00:00:00+00:00'].class
=> DateTime
```

Looks like a bug.

**Comment by thefliik** [comment]
Type coercion might only work with `Dry::Validation.Form` (and you're using `Dry::Validation.Schema`). I seem to remember something like that coming up for me.

**Comment by dreikanter** [comment]
There is no more `Dry::Validation.Form` since v0.12.0: https://github.com/dry-rb/dry-validation/releases/tag/v0.12.0

I've tried using Params instead:

``` ruby
schema = Dry::Validation.Params do
  configure { config.type_specs = true }
  required('value', Types::Params::DateTime).filled(:date_time?)
end
```

Nothing changed:

```
> pp schema.call(ActionController::Parameters.new('value' => '2018-02-07T00:00:00+00:00')).errors
{"value"=>["must be a date time"]}
```

**Comment by thefliik** [comment]
Oh I didn't notice that you're feeding in an `ActionController:Parameter` object instead of a hash. Pretty sure you have to use hashes. ActionController:Parameter has some method to transform it into a hash.

**Comment by dreikanter** [comment]
Thank you! I have no idea why I was so sure `Dry::Validation.Params` suppose to process `ActionController:Parameter`. I think I've just been tired.
