### ISSUE TITLE
Multiple or operators on High-level Rules causes duplicated error messages

### ISSUE THREAD

**Issue by jclaro** [dry-rb/dry-validation#418]
Hi there,
Not sure if a bug or not doing it as should:

```ruby
optional(:mobile_phone).maybe(max_size?: 16, format?: PHONE_REGEX)
optional(:home_phone).maybe(max_size?: 16, format?: PHONE_REGEX)
optional(:work_phone).maybe(max_size?: 16, format?: PHONE_REGEX)

# ...

rule(at_least_one_phone:
    %i[mobile_phone home_phone work_phone]) do |mobile_phone, home_phone, work_phone|
        mobile_phone.filled? | home_phone.filled? | work_phone.filled?
end
```

error message:
`At Least One Phone must be filled or must be filled`

if I add a message to error_messages.yml

```ruby
en:
  errors:
    rules:
      at_least_one_phone:
        filled?: "must be filled. Please X"
```
error message:
`At Least One Phone must be filled. Please X or must be filled. Please X`

It works as expected if only two or operators are used.

**Comment by solnic** [comment]
High level rule dsl is being removed in 1.0.0 so this won’t be addressed.

**Comment by kouyaf77** [comment]
FYI

I had same issue.  I guess you can write the condition like 
```
mobile_phone.none? > home_phone.filled? | work_phone.filled?
```
