### ISSUE TITLE
Confirmation macro does not work

### ISSUE THREAD

**Issue by bolshakov** [dry-rb/dry-validation#428]
[Documentation](https://dry-rb.org/gems/dry-validation/comparison-with-activemodel/#2-3-confirmation) described the following syntax:

```ruby
required(:attr).confirmation
```

But it doesn't work:

```ruby
params = Dry::Validation.Params do
  required(:password).confirmation
end
NoMethodError: undefined method `confirmation' for #<Dry::Validation::Schema::Rule:0x00007fab5e41c4e8>
```

**Comment by jferrer** [comment]
Try with required(:password).filled(min_size?: 6).confirmation

**Comment by bolshakov** [comment]
@jferrer it works

**Comment by solnic** [comment]
Closing because `confirmation` is going away in the 1.0.0 rewrite
