### ISSUE TITLE
presence of array of items

### ISSUE THREAD

**Issue by rafath-mfind** [dry-rb/dry-validation#430]
Is there any option to validate presence of array without any elements? So input looks like:

```
[
{ name: nil, age: nil},
{ name: nil, age: nil}
]
```

But I can get empty array `[]`

```
schema = Dry::Validation.Schema do
          each do
            schema do
              required(:name).filled(:str?)
              required(:age).filled(:int?)
            end
          end
        end
```

in case when array is empty: 
```
schema.call([]) # => #<Dry::Validation::Result output=[] errors={}>
```

```
schema.call([{ name: 123 }]) # =>  #<Dry::Validation::Result output=[{:name=>123}] errors={0=>{:name=>["must be a string"], :age=>["is missing"]}}>
```

I'd like to validate presence of at least one element in array - How I can do that?

**Comment by flash-gordon** [comment]
top-level arrays aren't supported in dry-schema yet, is it correct @solnic ?
```
./bin/console:12:in `block in <main>': undefined method `each' for #<Dry::Schema::DSL:0x00007fe0d29033e0> (NoMethodError)
```

**Comment by solnic** [comment]
@flash-gordon they are not, and won't be, actually

**Comment by flash-gordon** [comment]
@solnic will I need to wrap my input with dummy hashes then? :)

**Comment by solnic** [comment]
@flash-gordon no, just do:

``` ruby
results = array.map { |el| element_schema.(el) }
```

...this was a silly feature, so it's going away.

**Comment by flash-gordon** [comment]
well, the question then is collecting the results

**Comment by flash-gordon** [comment]
also, your code implies the value is an array already. If it's something you get from `JSON.parse` it can be any JSON-compatible value

**Comment by flash-gordon** [comment]
Closing in favor of https://github.com/dry-rb/dry-schema/issues/22
