### ISSUE TITLE
Dry-validation fails starting with dry-logic 0.5.0

### ISSUE THREAD

**Issue by agrare** [dry-rb/dry-validation#438]
Once dry-logic 0.5.0 was released dry-validation began failing with the following exception:

```
ArgumentError: wrong number of arguments (given 0, expected 1)
/home/agrare/.gem/gems/dry-logic-0.5.0/lib/dry/logic/predicates.rb:17:in `nil?'
/home/agrare/.gem/gems/dry-configurable-0.7.0/lib/dry/configurable.rb:110:in `setting'
/home/agrare/.gem/gems/dry-validation-0.12.2/lib/dry/validation/schema/class_interface.rb:15:in `<class:Schema>'
/home/agrare/.gem/gems/dry-validation-0.12.2/lib/dry/validation/schema/class_interface.rb:7:in `<module:Validation>'
/home/agrare/.gem/gems/dry-validation-0.12.2/lib/dry/validation/schema/class_interface.rb:6:in `<module:Dry>'
/home/agrare/.gem/gems/dry-validation-0.12.2/lib/dry/validation/schema/class_interface.rb:5:in `<top (required)>'
/home/agrare/.gem/gems/activesupport-5.0.7.1/lib/active_support/dependencies.rb:293:in `require'
```

https://github.com/dry-rb/dry-configurable/blob/v0.7.0/lib/dry/configurable.rb#L110
https://github.com/dry-rb/dry-logic/blob/v0.5.0/lib/dry/logic/predicates.rb#L17

**Comment by carbonin** [comment]
This currently breaks a vanilla rails app with the `config` gem.

**Comment by solnic** [comment]
This will be fixed in 0.13.0. I'm about to release it.

**Comment by solnic** [comment]
Please update to dry-validation 0.13.0. It's fixed there.

**Comment by agrare** [comment]
Thanks @solnic !

**Comment by flash-gordon** [comment]
It's also safe to use 0.12.3, I've just released it. It has lower pinned versions of dry-types and dry-logic as dependencies. Feel free to choose depending on your case.
