### ISSUE TITLE
"Dynamic Schema" by passing a Hash?

### ISSUE THREAD

**Issue by zhandao** [dry-rb/dry-validation#442]
Hi all, thank you for these awesome gems.

I know the way to use `dry-validation` is passing a block to `Schema()` -- then a DSL instance will be initialized and the block will be exceuted on it.

What I want to do is validate the controller params based on the schemas defined in my OpenApi document. After parsing OpenApi document, I get a Hash like `{ name: 'age', required: true, type: 'integer' }`, but ... It can't be converted into block.

So, would you consider supporting this usage?
```ruby
Dry::Validation.Schema(
  required: {
    name: :filled,
     age: { type?: Integer, gteq?: 0 }
  },
  optional: { }
)
```

**Comment by solnic** [comment]
dry-validation is being rewritten on top of dry-schema, so this is no longer applicable here (Schema DSL implementation is gone in master, it now delegates to dry-schema). Furthermore, we use issues for bug tracking and confirmed feature requests. For discussions/questions please use https://discourse.dry-rb.org. See CONTRIBUTING.md for more info.
