### ISSUE TITLE
Rename `param` to `values` in rule blocks

### ISSUE THREAD

**Issue by solnic** [dry-rb/dry-validation#445]
Given that we have `params do ... end` for defining schemas, using the same `params` word within rule blocks might be confusing.

@flash-gordon @timriley any ideas for a better name? `data`? `result`?

**Comment by flash-gordon** [comment]
I'm inclining to `data`/`values`

**Comment by timriley** [comment]
I like `values`. Kind of fits nicely given we use `value` as part of the API inside the schema definition.

**Comment by igor-alexandrov** [comment]
What do you think about `input`? Since it is named as `input` here: https://github.com/dry-rb/dry-validation/blob/master/lib/dry/validation/contract.rb#L27

**Comment by solnic** [comment]
This is no longer `input`, this is actually `Result` object from `dry-schema`, so calling it `input` doesn't feel right.

**Comment by igor-alexandrov** [comment]
Got it, thanks.

So `values` sounds reasonable.
