### ISSUE TITLE
Add `schema` blocks

### ISSUE THREAD

**Issue by solnic** [dry-rb/dry-validation#447]
Just like `params` but using `Dry::Schema.define`.

**Comment by igor-alexandrov** [comment]
Are you sure this should be named `schema`? We already have `schema` that is used to access initialized Dry::Schema object.

**Comment by igor-alexandrov** [comment]
Or you mean that such blocks (`json`, `params`, `schema`) can be repeated several times?

**Comment by solnic** [comment]
> Are you sure this should be named `schema`? We already have `schema` that is used to access initialized Dry::Schema object.

Oh right. This needs to be renamed then. Let's just use `__schema__` to access initialized schema.

> Or you mean that such blocks (`json`, `params`, `schema`) can be repeated several times?

Nope! In fact, we should raise error if somebody tries to override already defined schema.

**Comment by igor-alexandrov** [comment]
Ok, I will do both.
