### ISSUE TITLE
Support "base" errors

### ISSUE THREAD

**Issue by solnic** [dry-rb/dry-validation#469]
With the new rule system and relying on schema results, it is now possible to define rules that can set errors for a parent key even when there are errors set for its child elements. This concept is known as "base" errors in `ActiveModel::Validation` and other similar libraries.

Here's an example use case:

``` ruby
class NewUserContract < Dry::Validation::Contract
  params do
    required(:address).hash do
      required(:street).filled(:string)
      required(:city).filled(:string)
      required(:country).filled(:string)
    end
  end

  rule(address: [:city, :country]) do
    city = values[:city]
    country = values[:country]

    failure("uhm, there's no #{city} in #{country}") unless valid_city?(city, country)
  end

   def valid_city?(city, country)
     # checks if city exists in the given country
   end
end

contract = NewUserContract.new

# this has an errors for both street and address keys, so we can't nest it the way we do now
contract.(address: { street: "", city: "Kraków", country: "Russia" })

# resulting error structure could look like this:
{ address: [["uhm, there's no Kraków in Russia"], { street: ["must be filled"] } }
```

**Comment by timriley** [comment]
@solnic this looks good to me. I presume the same approach will work in applying “base” errors to the root of the entire structure?

**Comment by solnic** [comment]
> I presume the same approach will work in applying “base” errors to the root of the entire structure?

@timriley uhm, no, I haven't thought about it. In #471 I introduced `ErrorSet` object and I think we want to store "base" errors separately from other errors. ie how would you identify errors for the entire structure?

**Comment by timriley** [comment]
I'd imagine I'd want _set_ a base error like this:

```ruby
class NewUserContract < Dry::Validation::Contract
  params do
    required(:email)
  end

  rule do
    failure("Sorry, users can only sign up on weekdays") if is_weekend?
  end

  def weekend?
    # ...
  end
end
```

That's a pretty contrived example of course. Sometimes the "base" error on the root structure would be determined based on one or more of the actual values, too.

Does that help at all?

**Comment by solnic** [comment]
@timriley yes this makes sense, no key path or message id means a failure applies to the whole input, now we just need to figure out an API for accessing these errors. I think we need a separate method for it, ie `ErrorSet#base` would return base errors (so, errors w/o a path).
