### ISSUE TITLE
Check performance against similar solutions

### ISSUE THREAD

**Issue by solnic** [dry-rb/dry-validation#470]
It's very likely performance is a bit worse than in `0.x` series, so let's check it and improve it if needed.

### TODO

- [x] `ActiveModel::Validations`
- [x] `ActiveRecord`
- [x] ~~`Sequel`~~ set up is too complex, esp that by default it does not use I18n. Giving up for now.
- [x] ~~`strong_parameters`~~ this actually makes no sense, `dry-schema` should be used standalone instead, and it *is* faster
- [ ] ???

**Comment by ahx** [comment]
I know it's not the same thing, but I assume JSON Schema validation is used for very similar use cases. So https://rubygems.org/gems/json_schemer, might be another candidate to compare with.

**Comment by solnic** [comment]
I spent some time on this and it's hard to come up with good scenarios. There's so much that's involved here that it's tricky to get a fair comparison. Overall `dry-validation` seems to be much faster in case of invalid input and ~1.5-2x slower with valid input (compared to AM, AR is slower in all cases).

Here are some sample results:

### Valid input

``` ruby
∞ [ruby-2.6.3][node-v8.12.0] dry-validation git(master) ✗ be ruby benchmarks/benchmark_form_valid.rb 
-- create_table(:users)
   -> 0.0036s
#<Dry::Validation::Result{:email=>"jane@doe.org", :age=>19} errors={}>
true
Warming up --------------------------------------
ActiveModel::Validations
                         4.721k i/100ms
        ActiveRecord     1.555k i/100ms
      dry-validation     2.245k i/100ms
Calculating -------------------------------------
ActiveModel::Validations
                         51.292k (± 3.5%) i/s -    259.655k in   5.068410s
        ActiveRecord     15.803k (± 2.7%) i/s -     79.305k in   5.022299s
      dry-validation     23.058k (± 2.0%) i/s -    116.740k in   5.064849s

Comparison:
ActiveModel::Validations:    51292.4 i/s
      dry-validation:    23058.2 i/s - 2.22x  slower
        ActiveRecord:    15802.6 i/s - 3.25x  slower
```

### Invalid input

```
#<Dry::Validation::Result{:email=>"", :age=>18} errors={:email=>["must be filled"], :age=>["must be greater than 18"]}>
false
false
Warming up --------------------------------------
         ActiveModel   196.000  i/100ms
        ActiveRecord   173.000  i/100ms
      dry-validation   694.000  i/100ms
Calculating -------------------------------------
         ActiveModel      1.993k (± 2.5%) i/s -      9.996k in   5.019657s
        ActiveRecord      1.763k (± 2.3%) i/s -      8.823k in   5.007969s
      dry-validation      6.927k (± 3.2%) i/s -     34.700k in   5.014876s

Comparison:
      dry-validation:     6927.2 i/s
         ActiveModel:     1992.7 i/s - 3.48x  slower
        ActiveRecord:     1762.7 i/s - 3.93x  slower
```

Notice that these benchmarks are not written in a way that we compare the same functionality. `dry-validation` does more checks through `dry-schema` than AR/AM do. It's not even possible to write a benchmark where AR/AM would do the exact same type of validation. Still worth to have *some* comparison though.

I'm sure we can make valid case faster, possibly faster than AM. This is something to investigate after 1.0.0.

I'm closing this for now, no need to keep it open as it's not a release blocker.

**Comment by solnic** [comment]
@ahx thanks for the suggestion, a PR adding it to the benchmarks would be cool 😄
