### ISSUE TITLE
Establish API for setting base errors

### ISSUE THREAD

**Issue by solnic** [dry-rb/dry-validation#481]
### Current ideas

``` ruby
rule do
  base.failure("oops")
end

rule do
  failure(nil, "oops")  # for consistency
end
```

**Comment by solnic** [comment]
@timriley @flash-gordon folks, I think I want to this:

``` ruby
rule do
  base.failure("oops") # set base, so with a nil key, same as key.failure(nil, "oops")
end

rule(:email) do
  key.failure("oops")  # auto-sets :email as the key
end

rule(:email, :address) do
  key.failure(:address, "oops")  # overrides default and sets :address
end
```

WDYT?

**Comment by timriley** [comment]
@solnic This feels pretty good. My initial thinking is that calling something a "key failure" that appears on the _base_ of a nested hash, e.g. `:address` would be confusing, but I suppose that error _is_ on the base of the "address key", so I suppose it works too.

Are you suggesting here that the only place you'd ever use `base.failure` is the on the base of the whole structure passed to the validation contract? Never elsewhere?

In this proposal are you thinking you'd remove the non-chained `failure` API? e.g.

```ruby
rule(:email) do
  failure("oops")  # auto-sets :email as the key
end
```

... is no longer a thing? And instead we'd use `key.failure("oops")` there?

**Comment by timriley** [comment]
The reason I ask all these questions is that if we're supporting many different ways of setting the same kinds of failures, I think we may end up with an API that's unclear or confusing to use.

**Comment by flash-gordon** [comment]
@solnic shouldn't it be `key(:address).failure("...")`?

**Comment by solnic** [comment]
> In this proposal are you thinking you'd remove the non-chained failure API?

Yes. I also prefer to have as little ways of setting errors as possible.

> @solnic shouldn't it be key(:address).failure("...")?

I like that, but I would prefer to keep the implicit key because it reduces duplication, so:

``` ruby
rule(:email) do
  key.failure("foo") # pre-sets :email by default
end
```

but I also like they idea of passing key name to the key method, so this would work too:

``` ruby
rule("address.street") do
  key(:address).failure("this whole thing is wrong")
end
```

Does this make sense?

**Comment by timriley** [comment]
@solnic those two code examples make sense to me. And narrowing down the number of ways to set an error is good 👍 

Would you now mind clarifying how you'd expect `base.failure("oops")` to work? Would it always set an error on the base of the _entire data structure_, no matter where you called it?

**Comment by solnic** [comment]
> Would you now mind clarifying how you'd expect base.failure("oops") to work? Would it always set an error on the base of the entire data structure, no matter where you called it?

Yes, it sets the error path to `[nil]` which indicates a base error. There's no need to support `base(:foo).failure("boom!")` because it's the equivalent of `key(:foo).failure("boom!")`.

**Comment by timriley** [comment]
@solnic cool, this is what I was hoping to hear, I think this should nicely cover everything then!

**Comment by flash-gordon** [comment]
yeah I didn't mean `key`'s arguments to be required, inheriting it from `rule` is a sensible default
