### ISSUE TITLE
Establish API for defining macros

### ISSUE THREAD

**Issue by solnic** [dry-rb/dry-validation#482]
Macros in dry-validation 1.0.0 will be based on `rule` API, for a good start we'll add `confirmation` because it exists in `0.x`:

### API ideas

``` ruby
class NewUserContract < Dry::Validation::Contract
  schema do
    required(:email).filled(:string)
    required(:password).filled(:string)
    required(:password_confirmation).filled(:string)
  end

  confirmation :password
end
```

**Comment by flash-gordon** [comment]
@solnic what kind of API do you have in mind beyond something like `def self.confirmation` in a base class?

**Comment by solnic** [comment]
@flash-gordon probably just that, yes. It’s only a matter of providing shortcuts to common rule types, which does boil down to contract class methods

**Comment by solnic** [comment]
Closing since there isn't anything special we need to do - these are just class methods, ie:

``` ruby
class MyApp::Contract < Dry::Validation::Contract
  def self.confirmation(name)
    rule(name) do
      key.failure("doesn't match confirmation") if values[name] != values[:"#{name}_confirmation"]
    end
  end
end
```
