### ISSUE TITLE
1.0.0.alpha2 errors / Contract

### ISSUE THREAD

**Issue by danielnc** [dry-rb/dry-validation#496]
Just started to play around 1.0.0.alpha2 and I am getting the following error and I am not sure if it's on my end something I am missing or it's indeed a bug:

```ruby
class API::V2::AppointmentContract < Dry::Validation::Contract
  RSVP ||= ["going", "not_going"].freeze
  TYPE ||= %w(sms voice).freeze

 params do
  required(:starts_at).filled(:string)
  optional(:rsvp).filled(:string, included_in?: RSVP)
  required(:type).filled(:string, included_in?: TYPE)
  rule(:starts_at) do
    failure(:invalid) unless values[:starts_at] =~ FormatConstraints::ISO8601_DATETIME
  end
end
```

```
API::V2::AppointmentContract.new.({type: "sms", starts_at: "2019-09-01T10:00:00Z+03:00"})
```

I get the following error:
```
Traceback (most recent call last):
        4: from (irb):26
        3: from app/contracts/api/v2/appointment_contract.rb:1:in `<main>'
        2: from app/contracts/api/v2/appointment_contract.rb:5:in `<class:AppointmentContract>'
        1: from app/contracts/api/v2/appointment_contract.rb:6:in `block in <class:AppointmentContract>'
NoMethodError (undefined method `visit_nominal' for #<Dry::Schema::PredicateInferrer::Compiler:0x00007fbf616abbc0>)
Did you mean?  visit_enum
```

**Comment by flash-gordon** [comment]
It's because of dry-types 0.15. Please use 0.14 for now, we'll release a new alpha/beta of dry-schema soon. Alternatively, you can work with master branches of dry-{validation,schema}, they are already compatible with 0.15.

**Comment by danielnc** [comment]
@flash-gordon thanks! that works

**Comment by solnic** [comment]
@danielnc I'll be releasing `1.0.0.beta1` later this week

**Comment by danielnc** [comment]
somewhat unrelated but I've been exploring 1.0

Where can I find examples for nested arrays?
On the specs I could only find for hash values

Feel free to close this issue if this is not the place to ask this kind of question

**Comment by solnic** [comment]
> Where can I find examples for nested arrays?

For questions like this you can join either our chat (we're testing out Zulip) http://dry-rb.zulipchat.com or post a message on https://discourse.dry-rb.org
