### ISSUE TITLE
Reusing Schemas

### ISSUE THREAD

**Issue by samnang** [dry-rb/dry-validation#502]
We're trying out the latest from master, but we can't seem to find how to reuse schema's like in the old version:

https://dry-rb.org/gems/dry-validation/0.13/reusing-schemas/

Is there a new way to reuse schemas with `Dry::Validation::Contract`?

**Comment by solnic** [comment]
schemas in dry-validation use dry-schema now, so you can re-use schemas the same way there https://dry-rb.org/gems/dry-schema/reusing-schemas/

ps. please don't ask support questions in Issues. See CONTRIBUTING.md for more info.
