### ISSUE TITLE
Merging schemas

### ISSUE THREAD

**Issue by rubenmoya** [dry-rb/dry-validation#511]
Hello!

I've been looking for an answer and didn't find it so I'm opening a new issue. I'm trying to extend and schema but it looks like if both schemas share the same attribute it only uses the later, for example:

```ruby
FirstSchema = Dry::Validation.Schema do
  required(:email).filled(:int?)

  required(:address).schema do
    required(:street).filled(:int?)
    required(:postal_code).filled(:int?)
  end
end


Dry::Validation.Schema(FirstSchema) do
  required(:address).schema do
    required(:country).filled(:int?)
  end
end
```

The second schema should validate `street`, `postal_code` and `country`, or at least is what I was expecting, but instead it only validates `country`.

Is this the expected behaviour? Is there any workaround to achieve what I want?

I'm using the `0.13.x` version of the gem.

**Comment by solnic** [comment]
This feature will be available via dry-schema either in dry-validation 1.0.0 or soon after

**Comment by rubenmoya** [comment]
Thank you for the answer!
