### ISSUE TITLE
Supporting hints in Validation::Result

### ISSUE THREAD

**Issue by bencallaway** [dry-rb/dry-validation#514]
Should `Dry::Validation::Result#hints` be implemented as well? Would it just be a matter of (conditionally) delegating to the underlying schema, or would it require an extension? I'm happy to lend a hand.

**Comment by solnic** [comment]
Yes this should be provided by an extension. It would have to enable `:hints` extension in `dry-schema` too + add new methods to the result object. A PR adding that would be lovely.
