### ISSUE TITLE
Provide #dig for Dry::Validation::Result

### ISSUE THREAD

**Issue by mensfeld** [dry-rb/dry-validation#523]
When building nested custom rules, one have to define a custom scoped builder method for that similar to this one:

```ruby
def self.kafka_scope_rule(key, &block)
  rule(key, :kafka) do
    instance_exec(values[:kafka], &block)
  end
end
```

one problem with that approach is that with a multi-nested schemas with more complex stuff, this causes a lot of duplication.

If there would be a `#dig` we could do `values.dig(*args)` to prepare the scope dynamically and use one scope defined custom builder.

**Comment by solnic** [comment]
I added it in #520 which is a hash-like object now so `Hash` API is available
