### ISSUE TITLE
Dry::Validation::Values#[] should support path

### ISSUE THREAD

**Issue by ndan** [dry-rb/dry-validation#528]
It's hard to use `register_macro` feature for nested keys. 
It would be nice if `Dry::Validation::Values#[]` can return value by nested path (eg "contact.name")

In the example below `values[key_name]` will be `nil` because `key_name` is `'doc.number'`

```ruby
# frozen_string_literal: true

RSpec.describe 'Nested custom macros' do
  subject(:contract) do
    Class.new(Dry::Validation::Contract) do
      schema do
        required(:doc).hash do
          required(:number).filled(:integer)
        end
      end

      rule('doc.number').validate(:event)
    end.new
  end

  before do
    Dry::Validation.register_macro(:event) do
      key.failure('must be even') unless values[key_name].even?
    end
  end

  it { expect(subject.({ doc: { number: 2 }})).to be_success }
end
```
The spec will pass if I replace `values[key_name]` with `values.dig(:doc, :number)`

**Comment by solnic** [comment]
Good catch. I'll improve this before 1.0.0 final.
