### ISSUE TITLE
Undefined method `Schema' for Dry::Validation:Module

### ISSUE THREAD

**Issue by ccverak** [dry-rb/dry-validation#544]
I'm new to dry-rb so please excuse me if this is not the right place for this bug report.

**Describe the bug**

According to the 1.0.0 documentation, one of the ways to declare a schema is in the following:

```ruby
require 'dry-validation'

schema = Dry::Validation.Schema do
  required(:email).filled(:str?)
  required(:age).filled(:int?, gt?: 18)
end
```

This breaks for me with the following error:

> undefined method `Schema' for Dry::Validation:Module (NoMethodError) 

**To Reproduce**

The following script fails with the mentioned error

```ruby
require 'bundler/inline'

gemfile do
  source 'https://rubygems.org'
  gem 'dry-validation', '1.0.0'
end

require 'dry-validation'

schema = Dry::Validation.Schema do
  required(:email).filled(:str?)
  required(:age).filled(:int?, gt?: 18)
end
```

**Expected behavior**

It should work as documented.

**Your environment**

- Affects my production application: **NO**
- Ruby version: 2.6.3
- OS: Manjaro Linux

**Comment by solnic** [comment]
Sorry about the confusion. This is old syntax. We had a bug on the website where it showed incorrect version number next to the docs. I've switched to 1.0.0 for all the default docs so this should no longer be an issue. See dry-rb/dry-rb.org/issues/312 for more context.
