### ISSUE TITLE
Documentation for registering a macro needs to be updated

### ISSUE THREAD

**Issue by cmavromoustakos** [dry-rb/dry-validation#546]
**Describe the bug**
 Currently the documentation states that to register a global macro you can use the following code:

```
Dry::Validation.register_macro(:email_format) do
  unless /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i.match?(value)
    key.failure('not a valid email format')
  end
end
```

This is incorrect and after following example from the tests provided here: https://github.com/dry-rb/dry-validation/blob/70afdeea6fe950f54d3d9f565a9a90cf65be55f7/spec/integration/macros/custom_macros_spec.rb#L37

the above code should be:

```
Dry::Validation.register_macro(:email_format) do
  binding.pry
  unless /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i.match?(values[key_name])
    key.failure('not a valid email format')
  end
end

```

**Comment by solnic** [comment]
This is correct. `value` is a shortcut for `values[key_name]`.

**Comment by cmavromoustakos** [comment]
@solnic 👍 thank you. I was using ` (1.0.0.rc3)` which I am guessing did not have this functionality

**Comment by solnic** [comment]
yes this was added in the final version, which explains it :)
