### ISSUE TITLE
Coercion on nested validation rule for array does not work

### ISSUE THREAD

**Issue by alexandru-calinoiu** [dry-rb/dry-validation#558]
**Describe the bug**

Coercion does not work for nested rules

**To Reproduce**

Create a simple contract like

```ruby
      class CreateContract < Dry::Validation::Contract

        params do
          optional(:member_qualifications).each do
            Dry::Schema.Params do
              required(:qualification_id).filled(:int?)
            end
          end
        end
end
```

Run:

```ruby
CreateContract.new.call(member_qualifications: [qualification_id: '1'])
```

You will receive:

```
#<Dry::Validation::Result{:member_qualifications=>[{:qualification_id=>"1"}]} errors={:member_qualifications=>{0=>{:qualification_id=>["must be an integer"]}}}>
```

**Expected behavior**

Should not receive an error

**Your environment**

- Affects my production application: **YES**
- Ruby version: 2.6.2
- OS: linux
- dry-validation version: 1.1.1

**Comment by alexandru-calinoiu** [comment]
This contract:

```ruby
      class CreateContract < Dry::Validation::Contract

        params do
          optional(:member_qualifications).array(:hash) do
            required(:qualification_id).filled(:int?)
          end
        end
end
```

Will produce the same error output

**Comment by flash-gordon** [comment]
`:int?` is a predicate, it doesn't coerce values in 1.x, use `:integer` – it's a reference to `Dry::Types['params.integer']`, a type with coercion. From it, dry-validation will infer the `:int?` predicate automatically and produce an error if coercion failed.
