### ISSUE TITLE
Can not define a rule when no parameters have been defined

### ISSUE THREAD

**Issue by shepmaster** [dry-rb/dry-validation#565]
**Describe the bug**

I was setting up a common base contract with a shared permission check and no parameters. This causes a `NoMethodError` for `nil` error. 

**To Reproduce**

```ruby
# frozen_string_literal: true

require 'dry-validation'

class ExampleContract < Dry::Validation::Contract
  rule do
    base.failure('conditional removed for tiny reproduction')
  end
end
```

**Expected behavior**

This code could be executed and do nothing.

**Actual behavior**

```
Traceback (most recent call last):
	4: from repro.rb:5:in `<main>'
	3: from repro.rb:6:in `<class:ExampleContract>'
	2: from $HOME/.rvm/gems/ruby-2.6.2@checklistpro/gems/dry-validation-1.1.1/lib/dry/validation/contract/class_interface.rb:129:in `rule'
	1: from $HOME/.rvm/gems/ruby-2.6.2@checklistpro/gems/dry-validation-1.1.1/lib/dry/validation/contract/class_interface.rb:183:in `ensure_valid_keys'
$HOME/.rvm/gems/ruby-2.6.2@checklistpro/gems/dry-validation-1.1.1/lib/dry/validation/contract/class_interface.rb:198:in `key_map': undefined method `key_map' for nil:NilClass (NoMethodError)
```

**Your environment**

- Affects my production application: NO
- dry-validation version: 1.1.1
- Ruby version: 2.6.2
- OS: macOS

**Workaround**

Use an empty `params` block.

**Comment by solnic** [comment]
We definitely should have a more meaningful error in such cases. I only wonder why do you think anybody would like to use a contract w/o params defined?

**Comment by solnic** [comment]
Oh wait, it crashes at the `rule` level - gotcha now! OK, this is clearly a bug. I'll fix it.

**Comment by shepmaster** [comment]
>> I only wonder why do you think anybody would like to use a contract w/o params defined?

> I was setting up a common base contract with a shared permission check

The children will specify params.
