### ISSUE TITLE
Use existing schema with contract

### ISSUE THREAD

**Issue by shanecav84** [dry-rb/dry-validation#574]
I have a schema defined separately. I would like to use it in my contract. Also, it might be worthwhile in the future to be able to extend the existing schema within the contract

## Examples

```ruby
class MySchema < Dry::Schema::Params
  # Schema DSL
end

class MyContract < Dry::Validation::Contract
  params(MySchema) do
    # Extended schema
  end
end
```

## Resources

- Previously mentioned: https://discourse.dry-rb.org/t/how-to-use-existing-schema-with-contract/834

**Comment by alassek** [comment]
I think this is reasonably important to have as a public API, because Contracts cannot be composed together in the same way Schemas can; therefore I need to be able to define them separately.

Currently, I just patch in
```ruby
def self.schema=(value)
  @__schema__ = value
end
```
and then do
```ruby
class MySchema < Dry::Schema::Params
  # Schema DSL
end

class MyContract < Dry::Validation::Contract
  self.schema = MySchema.new
end
```

**Comment by solnic** [comment]
@alassek yes it is, it'll be added in 1.3.0
