### ISSUE TITLE
Rules for array

### ISSUE THREAD

**Issue by barmic12** [dry-rb/dry-validation#583]
I have following schema:

```
params do
  required(:response_id).value(:string)
  required(:answers).array(:hash) do
    required(:question_id).value(:string)
    required(:value).hash do
      optional(:possible_answer_ids).value(:array)
      optional(:content).value([:hash, :string])
    end
  end
end
```

I'd like to be able define rules like:

`rule(answers: :question_id)`

But I get:
```
Dry::Validation::InvalidKeysError:
       Responses::Schema.rule specifies keys that are not defined by the schema: [{:answers=>:question_id}]
```

When I call `schema.key_map` I get:

`#<Dry::Schema::KeyMap["response_id", ["answers", ["question_id", {"value"=>["possible_answer_ids", "content"]}]]]>
`
I was looking for a similar example in specs, but I didn't find.

Is it possible to define rules like that?

**Comment by Mistgun** [comment]
Try with:
```
  rule(:answers).each do
     value[:question_id]
  end
```

**Comment by barmic12** [comment]
It works, thanks!

**Comment by barmic12** [comment]
Hello again, I have the additional issue related with this question.
I want to get response with errors in this way (like another default validations):

```
{
  answers: {
    0 => {
      question_id: [
        "error message"
      ]
    }
  }
}
```

I was trying in this way:
```
rule(:answers).each do
   key(:question_id).failure("error message")
end
```

But I get: 

`stages => ["error message"]`

**Comment by flash-gordon** [comment]
Please don't use Github for asking questions, see https://github.com/dry-rb/dry-validation/blob/master/CONTRIBUTING.md for links to our forum and chat.

**Comment by rruiz858** [comment]
It would have been nice if this was answered..
