### ISSUE TITLE
Dry::Validation::Result#messages ignore locale option

### ISSUE THREAD

**Issue by emaglio** [dry-rb/dry-validation#589]
**Describe the bug**

After calling a `Dry::Validation::Contract` on `errors` the `locale` option return the correct translation instead when using `messages` this option seems ignored 

**To Reproduce**

Giving a simple contract like this one:
```
class MySchema < Dry::Validation::Contract
  config.messages.load_paths << 'my_file.yml'
  params do
    required(:title).filled
  end
end

result = MySchema.call({})
result.errors(locale: :de) -> returns the de version
result.messages(locale: :de) -> returns the de version but it doesn't and returns the en version
```
Here a portion of my error file:
```
en:
  dry_validation:
    errors:
      filled?: "must be filled"


de:
  dry_validation:
    errors:
      filled?: "muss abgefüllt sein"
```
Here a screenshot from my console:
![image](https://user-images.githubusercontent.com/5493507/65822901-3e018b00-e28f-11e9-83f5-f48fdd1308d1.png)

**Expected behavior**

`result.messages(locale: :de)` returns the correct translation

**Your environment**

- adding compatibility to dry-v > 1.x in [reform](https://github.com/trailblazer/reform/pull/496)

**Comment by MatElGran** [comment]
@emaglio I had to change a bit your example to make it work for the base case (ie with default language). As I'm new to this code base, I'm not sure if I'm doing something wrong or if there were errors in your code example. 

Anyway, I think the problem here is that you are not providing the correct error key (cf cf https://dry-rb.org/gems/dry-schema/error-messages/#finding-the-right-key). Given this translation file (with `key?` messages added):

```yaml
en:
  dry_validation:
    errors:
      filled?: "must be filled"
      key?: "is missing"

de:
  dry_validation:
    errors:
      filled?: "muss abgefüllt sein"
      key?: "Sorry I don't speak german"
```

and the following schema (the same as yours):

```ruby
class MySchema < Dry::Validation::Contract
  config.messages.load_paths << 'my_file.yml'
  params do
    required(:title).filled
  end
end
```
Here is what I get:

```ruby
result = MySchema.new.call({}) # CHANGE HERE: had to instantiate the schema

errors = result.errors(locale: :de)
# =>  #<Dry::Validation::MessageSet messages=[#<Dry::Schema::Message text="Sorry I don't speak german" path=[:title] predicate=:key? input={}>] options={:source=>[#<Dry::Schema::Message text="is missing" path=[:title] predicate=:key? input={}>], :locale=>"de"}>

errors.messages # CHANGE HERE: no `messages` method on result object
# => [#<Dry::Schema::Message text="Sorry I don't speak german" path=[:title] predicate=:key? input={}>]
```

to get the `filled?` message, `title` key must be in params Hash, ie

```ruby
result = MySchema.new.call({title: ''}) # CHANGE HERE: had to instantiate the schema

errors = result.errors(locale: :de)
# => #<Dry::Validation::MessageSet messages=[#<Dry::Schema::Message text="muss abgefüllt sein" path=[:title] predicate=:filled? input="">] options={:source=>[#<Dry::Schema::Message text="must be filled" path=[:title] predicate=:filled? input="">], :locale=>"de"}>

errors.messages # CHANGE HERE: no `messages` method on result object
=> [#<Dry::Schema::Message text="muss abgefüllt sein" path=[:title] predicate=:filled? input="">]
```
It's completely possible I missed something, so don't hesitate to correct me or add information, and I'll have another try at it

**Comment by solnic** [comment]
@MatElGran `Result#messages` is a method provided by the `:hints` extension, so first you gotta enable it via `Dry::Validation.load_extensions(:hints)`.

**Comment by emaglio** [comment]
@MatElGran yeah as per @solnic reply we should be able to do something like:

![Uploading image.png…]()

So calling `messages` from the `result` object not from the `errors`
:+1:

**Comment by solnic** [comment]
Here's a valid repro:

```ruby
require 'dry/validation'

Dry::Validation.load_extensions(:hints)

class MySchema < Dry::Validation::Contract
  config.messages.load_paths << 'my_file.yml'

  params do
    required(:title).filled(:string)
  end
end

schema = MySchema.new

result = schema.call({})

puts result.errors(locale: :de).to_h.inspect
# {:title=>["wird vermisst"]}

puts result.messages(locale: :de).to_h.inspect
# {:title=>["is missing", "must be a string"]}
```

**Comment by solnic** [comment]
for the record, this is specific to dry-validation. I tried the same thing with standalone dry-schema and it works correctly.

**Comment by sirfilip** [comment]
Hello People, I can pick this one up

**Comment by moofkit** [comment]
I suppose this https://github.com/dry-rb/dry-validation/pull/652 is closing the issue

**Comment by flash-gordon** [comment]
thanks
