### ISSUE TITLE
Specifc message for more than one key validation

### ISSUE THREAD

**Issue by wscourge** [dry-rb/dry-validation#601]
According to the documentation: [Depending on more than one key](https://dry-rb.org/gems/dry-validation/1.3/rules/#depending-on-more-than-one-key), an error message related to the `rule` and added by `key.failure(:whatever)` relates to the first argument passed to the `rule` method:

```
class EventContract < Dry::Validation::Contract
  params do
    required(:start_date).value(:date)
    required(:end_date).value(:date)
  end

  rule(:end_date, :start_date) do
    key.failure('must be after start date') if values[:end_date] < values[:start_date]
  end
end

contract = EventContract.new

contract.call(start_date: Date.today, end_date: Date.today - 1).errors.to_h
# => {:end_date=>["must be after start date"]}
```

As you can see, `:end_date` is the `key` under which validation error resides in the output hash. This does not enable to validate interdependent keys in the same rule.

Consider the following example:

```
rule(:birth_date, :driving_license_date) do
  driving_license_date = values.keys.include?(:driving_license_date) && !values[:driving_license_date].nil?
  birth_date = values.keys.include?(:birth_date) && !values[:birth_date].nil?

  if birth_date
    key.failure(:date?) && next if invalid_date?(values[:birth_date])
    key.failure(:must_be_later) && next if values[:birth_date].to_date < MIN_BIRTH_YEAR
    key.failure(:must_be_earlier) && next if values[:birth_date].to_date < MAX_BIRTH_YEAR
  end

  if driving_license_date
    key.failure(:date?) && next if invalid_date?(values[:driving_license_date])
    key.failure(:must_be_earlier) && next if values[:driving_license_date].to_date.future?
  end

  if driving_license_date && birth_date
    key.failure(:must_be_later) if values[:driving_license_date].to_date < (values[:birth_date].to_date + 16.years)
  end
end
```

as you can see, there are two potentially shareable failures:

- `key.failure(:must_be_later)`, 
- `key.failure(:date?)`

which could be easily used for both `birth_date` and `driving_license_date`, but due to current behavior it results in being:

```
{
  birth_date: 'must be earlier'
}
```

for both `driving_license_date` and `birth_date`. 

Investigating further, under the usual `key` available within the `rule`, there's `Dry::Validation::Evaluator` with `@keys=[:birth_date]`. It'd be cool if in the example above one could use:

```
rule(:birth_date, :driving_license_date) do
...
keys[:birth_date].failure(:must_be_later) && next if values[:birth_date].to_date < min_birth_year
keys[:driving_license_date].failure(:must_be_later) if driving_license_date_too_early?(values.slice(:birth_date, :driving_license_date))
...
end
```

where the `keys` would be the `Hash` of `Dry::Validation::Evaluator` objects. I don't know the internals of your library well enough to understand if that's a viable solution and am generally open to anything that would allow specifying error messages on a per param basis.

**Comment by skryukov** [comment]
Hi, @wscourge, you can do this:

```ruby
rule(:birth_date, :driving_license_date) do
  #...
  key(:birth_date).failure(:must_be_later) && next if values[:birth_date].to_date < min_birth_year
  key(:driving_license_date).failure(:must_be_later) if driving_license_date_too_early?(values.slice(:birth_date, :driving_license_date))
  # ...
end
```

Also, I want to point out that we use issues for confirmed feature requests and bug tracking. For discussions/questions, please use https://discourse.dry-rb.org. See [CONTRIBUTING.md](https://github.com/dry-rb/dry-validation/blob/master/CONTRIBUTING.md) for more info.

**Comment by wscourge** [comment]
Thanks for a swift response, you're obviously right.
