### ISSUE TITLE
Generic and specific rule for a nested array

### ISSUE THREAD

**Issue by DawidJanczak** [dry-rb/dry-validation#620]
We have a deeply nested schema with an array of hashes where one of the attributes is also array of hashes. Now for that nested array it doesn’t seem to be possible to add an error both to the attribute itself and to its nested children. You can find a trivial example where an error is always being set below:

```
class RulesExample < ApplicationContract
  params do
    required(:outer).array(:hash) do
      required(:inner).array(:hash) do
        required(:attr).filled(:integer)
      end
    end
  end

  rule(:outer).each do
    value[:inner].each_with_index do |inner, idx|
      inner_nested_key = key(key.path.keys + [:inner, idx])
      inner_nested_key.failure("Inner #{inner} specific failure")
    end

    inner_key = key(key.path.keys + [:inner])
    inner_key.failure('Inner generic failure')
  end
end
```
This fails with
```
NoMethodError: undefined method `[]' for nil:NilClass
from /usr/local/bundle/gems/dry-validation-1.4.2/lib/dry/validation/message_set.rb:108:in `block in messages_map'
```
From glancing over the code it seems to me like once a message is being found on outer[i]inner[j] it can no longer be set on outer[i]inner because in the first example a hash is expected and in the other it’s an array (or the other way around).

Having just one rule (either on the attribute or on the children) works just fine.

Source: https://discourse.dry-rb.org/t/generic-and-specific-rule-for-a-nested-array/986

**Comment by kaleb4eg** [comment]
I am also interested in that ^. Also, it would be great to have ability to define rules for deeply nested data with arrays.

**Comment by DawidJanczak** [comment]
@kaleb4eg's comment reminded me about this issue and I started by writing a spec for it here https://github.com/dry-rb/dry-validation/compare/master...DawidJanczak:spec-for-issue-620 but it seems the issue is now resolved as the spec passes on master. @solnic could you double check if that's indeed the case and if this can be now closed? Also let me know if you'd like to merge that spec, I can open a PR in that case.

**Comment by solnic** [comment]
@DawidJanczak please open a PR with this spec and I'll take a look

**Comment by DawidJanczak** [comment]
@solnic done: https://github.com/dry-rb/dry-validation/pull/645

**Comment by solnic** [comment]
Closing via #645
