### ISSUE TITLE
Coercion of String to Integer broken in v1.5 with Rails 6

### ISSUE THREAD

**Issue by mediafinger** [dry-rb/dry-validation#642]
I added a dry-validation contract with `required(:amount).filled(:int?, gt?: 0)`.  
While this works the automatic **coercion** from _"String"_ to Integer does not work.

I even used the code from this example to ensure I didn't make a mistake:  
https://github.com/dry-rb/dry-validation/blob/master/examples/params.rb

As I am just starting a refactoring of this app and using dry-validation I don't know if it used to work, but as I am basically using the code from the example I am optimistic that it is supposed to work.

**To Reproduce**

Create a new Rails 6 API with Ruby 2.6 and dry-validation 1.5 with one POST controller action that receives JSON:

```ruby
# frozen_string_literal: true

require "dry-validation"

class MyController < ApplicationController
  def create
    validate_params!(create_schema, params.to_unsafe_h)

    # do stuff and render
  end

  private

  # code take from: https://github.com/dry-rb/dry-validation/blob/master/examples/params.rb
  def create_schema
    contract = Class.new(Dry::Validation::Contract) do
      params do
        required(:amount).filled(:int?, gt?: 0)
      end
    end.new
  end
end

class ApplicationController < ActionController::API
  def validate_params!(schema, parameters)
    params_hash = parameters.to_h.with_indifferent_access

    result = schema.call(params_hash)
    fail ::Errors::SchemaValidation, result if result.failure? # fails as coercion doesn't work

    result
  end
end
```

**Expected behavior**

I expect that strings get coerced to integers before the validation.

**Your environment**

- Affects my production application: **not tried yet**
- dry-validation version: 1.5.0
- Ruby version: 2.6.6
- Rails version: 6.0.2.2
- OS: macOS Catalina

**Comment by flash-gordon** [comment]
@mediafinger ah, sorry, these examples are stale, I updated this one https://github.com/dry-rb/dry-validation/commit/4e4d87a0c28eb96133b87c96f4cf840304bbe2bc
You should always pass types, i.e. `:integer` rather than `:int?` because types are what makes coercion. `:int?` is only a predicate, it's automatically inferred from the type so you don't need to pass it. I'll update (or remove?) those examples later today, please, refer to the docs.

**Comment by mediafinger** [comment]
@flash-gordon thanks a lot for this quick response and for updating the examples 😃 This solved my issue (and I learned a bit more about how to validate)!
