### ISSUE TITLE
Allow passing intial context to the contract

### ISSUE THREAD

**Issue by pyromaniac** [dry-rb/dry-validation#674]
Summary of what the feature is supposed to do.

Would be awesome to be able to pass the initial context state to the `Contract#call` method. This will enable some code optimizations and flexibility.

```ruby
class Contract < Dry::Validation::Contract
  params do
    required(:post_id).filled(:integer)
  end

  rule(:post_id) do |context:|
    context[:post] ||= context[:current_user].posts.where(id: value).first or key.failure(:not_found)
  end
end

Contract.new.call({post_id: 42}, current_user: user).context # => {post: #<Post id: 42>, current_user: #<User id: 1>}
Contract.new.call({post_id: 42}, post: post).context # => {post: #<Post id: 42>}
```

This approach allows us:
1. Pass the context further to the operation class, which will perform updates
2. Optimize operations performed in batches `posts.each { |post| contract.call({post_id: post.id}, post: post) }`

The implementation is as simple as:

```ruby
class Dry::Validation::Contract
  def call(input, **initial_context)
    context = Concurrent::Map.new.tap do |map|
      initial_context.each { |key, value| map[key] = value }
    end

    Result.new(schema.(input), context) do |result|
      ...
    end
  end
end
```

Let me know what do you think about it? I will be glad to submit a PR.

**Comment by pyromaniac** [comment]
We can even go further and allow to pass the initial initial context to the initializer. Not sure how idiomatic is it going to be though. And actually it is possible to do with DI but we will have to all an additional rule which populates the instance context, which is a bit ugly I'd say.

Nevertheless, I believe that passing initial context to the `call` method would be invaluable.

**Comment by solnic** [comment]
@pyromaniac hey, thanks for the suggestion but in the future please use our forum to propose new features. We're using issues only for bug reports and feature requests that were previously discussed on the forum (or some other channel of communication).

Anyhow, in this case, I think it's a good idea. I think we want to use the option API and do something like this:

```ruby
option :default_context, default: -> { EMPTY_HASH }
```

...and then in the call method, merge it with the execution context if the default context is not empty. WDYT?

**Comment by pyromaniac** [comment]
A-ha, I see now. I just thought that the fact that there is a feature template makes me free to use it.

As for `option :default_context, default: -> { EMPTY_HASH }`, I was afraid that you are going to propose this. I was thinking about it for a long time. Imagine, you have an application container that stores all the dependencies so you could inject them later. Dry-container, for example, doesn't have a request-long lifetime, only application-lifetime instances. So you have to initialize it lazily at the beginning. This is a configuration. And context is something that depends on the call itself, every time you pass a `model_id` and want the contract to look it up for you to perform additional validations, it is a new entity. You might want to pass the entity as well, if you have it already fetched. So adding it `default_context` might also make it more flexible but passing context to the `call` method is the main thing to do here, otherwise it will be useless. Context really depends on params.

**Comment by solnic** [comment]
@pyromaniac ah, yeah it makes sense! thanks for the explanation. I think having `def call(input, context: EMPTY_HASH)` would be better than kwargs though.

**Comment by pyromaniac** [comment]
Yeah, I'd say it will be a bit less convenient but API-wise more future-proof.

**Comment by flash-gordon** [comment]
You can always have a custom base class like
```ruby
class MyContract < Dry::Validation::Contract
  def call(input, **context)
    super(input, context: context)
  end
end
```

**Comment by pyromaniac** [comment]
Alright, can do the PR over the weekend probably. Maybe a bit earlier. Thanks for your opinions folks!

**Comment by solnic** [comment]
This was done via #675
