### ISSUE TITLE
Method `key?` does not accept any args

### ISSUE THREAD

**Issue by Somestuffman** [dry-rb/dry-validation#681]
## Describe the bug

Hello!
According to the [docs](https://dry-rb.org/gems/dry-validation/1.5/rules/#checking-if-the-value-is-present) it is possible to pass key name to the `key?` method. Passing key name to the method inside multiple keys rule returns `ArgumentError: wrong number of arguments (given 1, expected 0)`.

## To Reproduce

```ruby
class DistanceContract < Dry::Validation::Contract
  schema do
    optional(:kilometers).value(:integer)
    optional(:miles).value(:integer)
  end

  rule(:kilometers, :miles) do
    if key?(:kilometers) && key?(:miles)
      base.failure("must only contain one of: kilometers, miles")
    end
  end
end
```

## Expected behavior

```ruby
DistanceContract.new.call(kilometers: 1, miles: 2).success? # => false
```

## Actual behavior

```ruby
DistanceContract.new.call(kilometers: 1, miles: 2).success? # => ArgumentError: wrong number of arguments (given 1, expected 0)
```

## My environment

- Affects my production application: **NO**
- Ruby version: ruby 2.6.6p146 (2020-03-31 revision 67876) [x86_64-darwin19]
- OS: MacOS X
- Dry-validation version: 1.5.0

## Possible solution

Calling `values.key?(:some_param)` solves this issue, so this might be just typo in docs.

**Comment by solnic** [comment]
This was added in 1.5.4 so please upgrade. The docs assume you're on the latest version from a given minor version series, meaning that docs for 1.5 assume the latest 1.5.x release. The CHANGELOG explains when this feature was added btw, so in the future please see CHANGELOGs. We "should" of course have versioned docs for every-single-release and hopefully we'll have it one day.

**Comment by Somestuffman** [comment]
Thanks!
