### ISSUE TITLE
Params.date validation strange behaviour

### ISSUE THREAD

**Issue by pandwoter** [dry-rb/dry-validation#683]
## Describe the bug

Not sure is it a bug tho, but wanted to clarify the correctness of such behavior. 

## To Reproduce

```ruby
class NewUserContract < Dry::Validation::Contract
    params do
      optional(:date).filled('params.date')
    end
end

contract = NewUserContract.new

contract.call(date: '12') #=> <Dry::Validation::Result{:date=>Mon, 12 Apr 2021} errors={}>
contract.call(date: '123') #=> <Dry::Validation::Result{:date=>Mon, 03 May 2021} errors={}>
```

## Expected behavior

```ruby
contract.call(date: '12') #=>  <Dry::Validation::Result{:date=>"12"} errors={:date=>["must be a date"]}>
contract.call(date: '123') #=> <Dry::Validation::Result{:date=>"123"} errors={:date=>["must be a date"]}>
```

## My environment

- Affects my production application: **YES**
- Ruby version: 2.7.1

**Comment by flash-gordon** [comment]
dry-types delegates it to ruby by calling `Date.parse`. I don't really know why `Date.parse` works like that but you can use your own types with stricter definition

**Comment by pandwoter** [comment]
Fair enough let's close then, thanks for the answer.

**Comment by solnic** [comment]
@pandwoter btw - please use `optional(:date).filled(:date)` instead of the string qualifiers. Re parse behavior - this is actually really bad, I'd consider changing this in dry-types.

**Comment by pandwoter** [comment]
> @pandwoter btw - please use `optional(:date).filled(:date)` instead of the string qualifiers. Re parse behavior - this is actually really bad, I'd consider changing this in dry-types.

Ok, thanks! That example was just for demonstration.
