### ISSUE TITLE
 no implicit conversion of Integer into String

### ISSUE THREAD

**Issue by kadru** [dry-rb/dry-validation#689]
## Describe the bug

When I use a format validation with a value expected to be a string but when a integer is passed raises an error `no implicit conversion of Integer into String`

## To Reproduce

```ruby
require "dry-validation"

class ValidatorWithFormat < Dry::Validation::Contract
  params do
    required(:field).filled(format?: /a+/).value(:string)
  end
end

validator = ValidatorWithFormat.new

puts "it fails" if validator.call({ "field" => 0 }).failure?
puts "it pass" if validator.call({ "field" => "a" }).success?

```

## Expected behavior

The validation must fail

## My environment

- Affects my production application: YES
- Ruby version: 2.7.2
- OS: Ubuntu 20.04.2 LTS

**Comment by flash-gordon** [comment]
correct usage would be
```ruby
class ValidatorWithFormat < Dry::Validation::Contract
  params do
    required(:field).filled(:string, format?: /a+/)
  end
end
```
