### ISSUE TITLE
Contract do not find schema keys defined with nested Dry Params.

### ISSUE THREAD

**Issue by EricToshio** [dry-rb/dry-validation#702]
## Describe the bug

Dry Validation Contract class do not find schema keys defined with nested Dry Params.

## To Reproduce

Initial code (okay):

``` ruby
class DataContract < Dry::Validation::Contract
  params do
    required(:users).each do
      hash do
        required(:name).filled(:string)
      end
    end
  end

  rule(:users).each do
    key.failure('invalid name') unless value[:name].size >= 10
  end
end
```

refactor code (get error):

``` ruby
class UserParams < Dry::Schema::Params
  define do
    required(:name).filled(:string)
  end
end

class DataContractWithParams < Dry::Validation::Contract
  params do
    required(:users).each do
      hash do
        UserParams
      end
    end
  end

  rule(:users).each do
    key.failure('invalid name') unless value[:name].size >= 10
  end
end
```

error:

``` bash
Dry::Validation::InvalidKeysError (DataContractWithParams.rule specifies keys that are not defined by the schema: [:users])
```

## Expected behavior

Should define contract class `DataContractWithParams` without error.

## My environment

- Affects my production application: **NO**
- Ruby version: 2.6.6
- OS: macOS Monterey

**Comment by flash-gordon** [comment]
Have you seen where it was declared as supported?

**Comment by solnic** [comment]
I believe it should be:

```ruby
class UserParams < Dry::Schema::Params
  define do
    required(:name).filled(:string)
  end
end

class DataContractWithParams < Dry::Validation::Contract
  params do
    required(:users).each(UserParams)
  end

  rule(:users).each do
    key.failure('invalid name') unless value[:name].size >= 10
  end
end
```

No?

**Comment by EricToshio** [comment]
Thank you @flash-gordon for your help! 
It's not explicit declared as supported in `dry-validation`.
This declare was created based on `dry-schema` since `dry-validation` uses It under the hood.
In **reusing schemas** section of `dry-schema` documentation, show that you can use :

``` ruby 
required(:address).hash(AddressSchema)
```

And in **nested data**, show that you can use:

``` ruby
  required(:people).value(:array, min_size?: 1).each do
    hash do
      required(:name).filled(:string)
      required(:age).filled(:integer, gteq?: 18)
    end
  end
```

Merging both idea in `dry-validation` schema definition I wrote the refactor code. Should It not be supported ?

Thank you @solnic for your help!  The snippet you wrote didn't work, but after some changes this worked:

``` ruby
class UserParams < Dry::Schema::Params
  define do
    required(:name).filled(:string)
  end
end

class DataContractWithParams < Dry::Validation::Contract
  params do
    required(:users).filled(:array).each(UserParams.new)
  end

  rule(:users).each do
    key.failure('invalid name') unless value[:name].size >= 10
  end
end
```

So is necessary declare as `:array` and add `.new`

**Comment by solnic** [comment]
@EricToshio ah right, this should work too: `required(:users).array(UserParams.new)`

**Comment by flash-gordon** [comment]
@EricToshio we don't expect a value from the schema block, it's likely being ignored

**Comment by EricToshio** [comment]
Thank you!
