### ISSUE TITLE
Option to yield rather than instance_eval in DSL

### ISSUE THREAD

**Issue by hooptie45** [dry-rb/dry-validation#71]
### ISSUE
Currently the DSLs instance_eval the code block. This is fine in most cases, however it becomes awkward  in certain contexts. 

For example, say I want to generate an deeply nested hash validation programmatically. 

The structure I'm trying to create would look like this:
```ruby
    Dry::Validation.Schema do
      key(:Deeply).schema do
        key(:Nested).schema do
          key(:Object).required(&:string?)
        end
      end
    end
```

A failed attempt might look like this: 

```ruby
    # In my initializer 
     @path = %w(Deeply Nested Object)
    # ....
    Dry::Validation.Schema do
      @path.reverse.reduce(self) do |memo, segment| 
        key(:Deeply).schema
      end
    end
```

`instance_eval` changes `self`, so instance variables, and  methods in your current object become unreachable. Therefore `@path` is `nil` (hopefully...).  

```ruby

  @path = [:Deeply, :Nested, :Object]  

  Dry::Validation.Schema do |schema|
     @path.reverse.reduce(schema) do |s, segment|
        s.key(segment).schema { |nested| s = nested }
        s
      end
      schema
    end
```

Assuming the block is optional, and the return value is the schema you just created; one solution might look like this:

```ruby
  @path = [:Deeply, :Nested, :Object]  

  Dry::Validation.Schema do |schema|
     @path.reverse.reduce(schema) do |s, segment|
        s.key(segment).schema
      end
    end
```

I think we can implement this so both styles are possible, with changing the API. Perhaps something like this could work:

```ruby
if block.arity == 1
    res = block.call(key)
else
    res = key.instance_eval(&block)
end
```

**Comment by solnic** [comment]
I wouldn't want to make the already complex dsl code even more complex with this dual-arity mode. There are already lower level APIs for building up schema rules, these should be used in such cases. They are definitely not polished as the dsl, but I would be more interested in making them robust and simple to use vs messing with the dsl blocks.

**Comment by solnic** [comment]
@hooptie45 I was just chatting with Luca from Hanami project about the same thing and prepared a sample script which shows how to build rules manually, I figured I should share here too:

``` ruby
require 'dry-validation'

v = Dry::Validation::Schema::Value.new

v.key(:email).required(:str?)
v.key(:age).required(:int?)

class UserSchema < Dry::Validation::Schema::Form
end

UserSchema.configure do |config|
  config.rules = v.rules
end

schema = UserSchema.new

puts schema.(email: ‘luca@hanami.rb’, age: 'no idea').messages.inspect
```

**Comment by solnic** [comment]
I'm gonna close this one since the DSL won't be changed to support dynamic generation of rules. We have low-level interfaces to do this and even when these are not enough you can always build rule ast yourself. This will be documented properly once we're close to 1.0.0.
