### ISSUE TITLE
Building contract failed when or-ing types

### ISSUE THREAD

**Issue by sdalu** [dry-rb/dry-validation#712]
The following code result in `key not found: "int?" (Dry::Container::KeyError)`

~~~ruby
module Types
  include Dry::Types()
end
class B < Dry::Validation::Contract
  json do
    optional(:id).filled(Types::Integer | Types::String)
  end
end
~~~

dry-validation: 1.8.1
dry-schema: 1.10.2
dry-types: 1.5.1
ruby: 3.1.2

**Comment by solnic** [comment]
oh and btw, I would do it like that anyway:

```ruby
optional(:id) { int? | (str? & filled?) }
```

This makes more sense, because it's supposed to be either an integer or a string that's not empty.
