### ISSUE TITLE
Mixing of `~>` and `<` in gemspec versioning

### ISSUE THREAD

**Issue by sirneb** [dry-rb/dry-validation#726]
## Describe the bug

This issue is throughout the `dry-*` gem ecosystem in its .gemspec files where it is using a mix of `~>` and `<` for version dependencies to other `dry-*` gems, for example:
https://github.com/dry-rb/dry-validation/blob/ce18224a1c05a8fe78c1a729b804a12acdebbbb5/dry-validation.gemspec#L33

In the above case, it's not a huge deal because the `< 2` part is basically redundant as the `~> 1.0` covers all the 1.x versions and no under 2.0. But when dry-* were in the major version zero (ie. 0.x versions), the `< 2` part does not allow `1.x`. I'm sure whoever added these lines intended to allow `0.x` to `1.x` but not `2.0` or above.

Instead, we should write this in the following manner instead:
```
spec.add_runtime_dependency "dry-core", ">= 1.0", "< 2.0"
```

I hope this helps and I was in versioning hell when updating dry-* gems due to this issue with 0.x versions and some versions were actually not compatible when the versioning allows them. We should just not mix using `~>` and `<` moving forward.

## To Reproduce
With for example, if I have an app that uses `dry-validations` and `dry-validations` defines the following dependency version for `dry-core`:
```
spec.add_runtime_dependency "dry-core", "~> 0.5.0", "< 2.0"
```
bundler won't allow using `dry-core@1.x` (or even 0.6.x actually) in the app even though you would think it should

## Expected behavior

The intent is likely to allow 0.5.0 or greater, including 1.x but lower than 2.0.

**Comment by flash-gordon** [comment]
No, the goal was to allow 1.x only. I agree `< 2` is redundant,  it was set by mistake. When we released dry-core 1.0 we had to update all gems to allow this version. This led to changes in _some_ (or even all) gems making them incompatible with dry-core 0.x. To make things more manageable (on our side) we require updating to dry-core 1.0 for using _any_ recent release of dry-*.
