### ISSUE TITLE
Is there a built-in way to specify a value can be one of several values?

### ISSUE THREAD

**Issue by joevandyk** [dry-rb/dry-validation#79]
I have an attribute that must be one of `%w( this or that)` to be valid. Looked at the documentation, didn't see a way to do it without doing a custom predicate.

**Comment by timriley** [comment]
Hi @joevandyk – you want `inclusion?` (https://github.com/dry-rb/dry-logic/blob/master/lib/dry/logic/predicates.rb#L116-L118).

```ruby
schema = Dry::Validation.Schema do
  key(:status).required(inclusion?: %w[draft published])
end

schema.(status: "published").messages
# => {}

schema.(status: "invalid").messages
# => {:status=>["must be one of: draft, published"]}
```

**Comment by joevandyk** [comment]
ahhh yes

**Comment by joevandyk** [comment]
should that be in the documentation? (if it was, i missed it)

**Comment by solnic** [comment]
Seems like I forgot to include predicate-list page in the docs. Dammit :(
