### ISSUE TITLE
Predicate :number? inside "each" macro causes errors

### ISSUE THREAD

**Issue by lukaszbieniek** [dry-rb/dry-validation#95]
Predicate `number?` used inside `each` macro causes `TypeError` while calling `#messages` method. Here's how to reproduce an error:

**Fails for** `:number?`

```ruby
FailureWithNumberSchema = Dry::Validation.Schema do
  key(:items).each do
    key(:value).required(:number?)
  end
end

FailureWithNumberSchema.call({}).messages
# => TypeError: no implicit conversion of Hash into Array
```

**Works well with** `:str?`

```ruby
SuccessWithStringSchema = Dry::Validation.Schema do
  key(:items).each do
    key(:value).required(:str?)
  end
end

SuccessWithStringSchema.call({}).messages
# => {:items=>["is missing"]}
```

**Comment by fran-worley** [comment]
Could it be as simple as I forgot to include a default error message when I added the predicate?

**Comment by fran-worley** [comment]
Looks like this isn't specific to `:number?`.

```ruby

Schema = Dry::Validation.Schema do
  key(:items).each do
    key(:value).required(min_size?: 6)
  end
end

Schema.call({}).messages

# => TypeError: no implicit conversion of Hash into Array
```

**Comment by lukaszbieniek** [comment]
Indeed, I realized the bug occurs when `items` attribute is invalid or not defined.

```ruby
Schema = Dry::Validation.Schema do
  key(:items).each do
    key(:value).required(min_size?: 6)
  end
end

Schema.call({}).messages
# => TypeError: no implicit conversion of Hash into Array

Schema.call({items: 3}).messages
# => TypeError: no implicit conversion of Hash into Array

Schema.call({items: []}).messages
# => {}
```

**Comment by fran-worley** [comment]
It appears to be an issue with the hint compiler.

When you it doesn't try to compile any hints: 
```ruby
Schema = Dry::Validation.Schema do
  key(:items).each do
    key(:value).required(:str?)
  end
end

#hints => {}
```

However when you try with a predicate not excluded in the hint_compiler you get:
```ruby
Schema = Dry::Validation.Schema do
  key(:items).each do
    key(:value).required(:str?)
  end
end

#hints => {}
```ruby
Schema = Dry::Validation.Schema do
  key(:items).each do
    key(:value).required(:str?)
  end
end

#hints => {:items=>{:value=>["must be a number"]}}
```
Causing the TypeError here (https://github.com/dry-rb/dry-validation/blob/master/lib/dry/validation/error_compiler.rb#L94)  as hints[:items] is a hash not an array.

Is it right that we are trying to return a hint at all here given that the entire set is missing?

**Comment by solnic** [comment]
Please use a nested schema syntax with `each` too. Nested keys will be removed prior 1.0. So just do:

``` ruby
key(:items).each do
  schema do
    key(:value).required(:number?)
  end
end
```

**Comment by solnic** [comment]
Can you verify if using `schema` makes it any better? If yes, please close.

**Comment by lukaszbieniek** [comment]
Yes, using `schema` inside `each` solves the problem.

**Comment by lukaszbieniek** [comment]
Here we've another gotcha.
An input data should be marked as correct in this case:

```ruby
Schema = Dry::Validation.Form do
  key(:items).each do
    schema do
      key(:title).required(:str?)
    end
  end
end

Schema.call({
  items: [
    { title: 'A valid string value' }
  ]
})
#=> #<Dry::Validation::Result output={:items=>[{}]} messages={:items=>{0=>{:title=>["is missing"]}}}>
```

**Comment by blelump** [comment]
@lukaszbieniek , `Dry::Validation.Form` expects a hash with string primitves as keys. If you want to use symbols, use a `Dry::Validation.Schema`.

**Comment by solnic** [comment]
@blelump actually, it's no longer true, the underlying `:symbolized` hash from dry-types passes through keys that are already symbols

**Comment by lukaszbieniek** [comment]
Sorry for misleading suggestion,
the problem also occurs  for base `Dry::Validation::Schema` class.

**Comment by solnic** [comment]
@lukaszbieniek are you sure? works for me with Schema. I actually found out the cause - input processor is broken in this setup, I'm working on a fix.

**Comment by lukaszbieniek** [comment]
@solnic, I've tested example. My bad, for base class works well. :confused:

**Comment by blelump** [comment]
@solnic , oh , didn't know that. Sorry for just messing around :disappointed:

**Comment by solnic** [comment]
please test from master if you can, should be good now. yet another reason to remove nested-keys syntax ha-ha

**Comment by lukaszbieniek** [comment]
@solnic , it work's like charm :ok_hand:

**Comment by solnic** [comment]
@lukaszbieniek great, thanks for reporting and testing this

ps. it's because it's a charming library :laughing: 
ps 2. I can push a tiny release with this fix if you want

**Comment by lukaszbieniek** [comment]
@solnic thanks, but there's no hurry (for me), my app is still in development... :innocent:
