### ISSUE TITLE
Validation of root container

### ISSUE THREAD

**Issue by lukaszbieniek** [dry-rb/dry-validation#98]
Please consider adding of root container validation in next releases. At the moment, `.call` method requires a hash as a parameter to work properly, except in cases of array as root container. 

It causes a little inconsistency:

```ruby
ArrayRootSchema = Dry::Validation.Schema do
  each do
    schema do
      optional(:name).required(:str?)
    end
  end
end

HashRootSchema = Dry::Validation.Schema do
  optional(:name).required(:str?)
end

ArrayRootSchema.call({})
#=> #<Dry::Validation::Result output={} messages={nil=>["must be an array"]}>
ArrayRootSchema.call(nil)
#=> #<Dry::Validation::Result output={} messages={nil=>["must be an array"]}>

HashRootSchema.call([]) # or non-hash value
#=> NoMethodError: undefined method `key?' for []:Array
```

btw. a message for invalid container error is assigned to nil:

```ruby
ArrayRootSchema.call(123).messages
#=> {nil=>["must be an array"]}
```

Isn't it the better to return the array only?

**Comment by solnic** [comment]
Nice catch. We should improve this for sure.

**Comment by solnic** [comment]
I will tackle this once #100 is done

**Comment by fran-worley** [comment]
Now that #100 is closed, should we put this back on the task list @solnic?

**Comment by solnic** [comment]
yeah this can be improved along with #192
