### ISSUE TITLE
Refine DSL

### ISSUE THREAD

**Issue by solnic** [dry-rb/dry-validation#99]
After discussion in #90 we've ended up with the following proposal:

``` ruby
key(:email).required
# becomes
required(:email).filled

required(:email).filled
# is a macro for:
required(:email).value(:filled?)

# new `value` method builds rules for a value extracted from the input under specified
# key or attr so:
required(:name).value(:filled?, size?: 1..60)
# or shorter:
required(:name).filled(size?: 1..60)

# the `value` method will allow us to be more specific about complex types like
# arrays, ie:
required(:tags).value(:filled?).each(:str?)
# which means "tags must be filled and must be an array and each element must
# be a string

# we can be more specific, ie:
required(:services).value(:filled?, size?: 4).each(:str?)
# which adds a constraint that the services array must have exactly 4 elements
```

We can easily deprecate current `required` method and just warn that you should now use `value` instead. Same with `key` and `attr` becoming `required`.

This change needs a small tweak though, since we will have `required` instead of `key` or `attr`, we must have a specialized dsl builder object for models, because `required` in case of a model schema, must produce `:attr` rules, not `:key`.

If you have any concerns or other ideas, just leave a comment.

**Comment by mrbongiolo** [comment]
`optional(:email)` will stay as it is?

**Comment by solnic** [comment]
Yes

**Comment by coop** [comment]
Hey, few quick comments:

I really like the change from `key(:email)` to `required(:email)` - more explicit and mirrors `optional(:email)`.

I'm not a massive fan of `value(:filled?)` and `value(:filled?).each(:str?)` because I cannot think of a situation where I don't want `value(:filled?)`:

* if I set `required(:email)` I will _always_ want some value, that is why the key is required
* if I set `optional(:email)` I will _always_ want some value if email is present
* if the value is present I care about type validation and coercion

What if `value(:filled?)` was applied by default and the argument you pass is the type that you expect e.g.

``` ruby
# validate that email is present, not nil or empty and a string
required(:email).value(:str?)

# validate that email is present, not nil or empty, a string and matches the regex
required(:email).value(Dry::Types['strict.string'].constrained(format: /email-regex/))

# validate that tags is present, not nil or empty, an array of 4 elements where
# each element is a string that is not nil or empty
required(:tags).value(:array?, size?: 4).each(:str?)
```

Maybe there is a use case for `value(:filled?)` that I'm not considering?

**Comment by coop** [comment]
This falls down if you want to write a rule that expects a key to be present and the value to be nil or an empty string / hash - _maybe_ this use case exists? I personally haven't had it.

**Comment by solnic** [comment]
We need a plain value rule builder without implicit assumptions. There are cases where you do not want to apply filled? ie you want to ensure that something is an integer and that's all.

**Comment by coop** [comment]
>We need a plain value rule builder without implicit assumptions.

That sounds like a good enough reason for the API that has been proposed.

>ie you want to ensure that something is an integer and that's all.

I get what you're saying but in my mind `filled?` does that by saying "not nil and an integer".

I'm all for this change :)

**Comment by fran-worley** [comment]
I completely agree with the proposed changes. Enjoy your time off @solnic and thanks again for your hard work.

**Comment by mrbongiolo** [comment]
Probably most of the cases will fall under @coop statement, that if you want something to be an Integer, you expect it to be there. 
But having very explicit rules are great for avoiding misunderstandings, as: `required(:age).value(:int?, gt?: 18)` says that the key is required, but it can be nil or empty, if it's not empty it should be an integer greater than 18.
As a rule: `optional(:age).value(:filled?, :int?, gt?: 18)` says that the key is optional, but if it's present it should be filled with an integer greater than 18.
It can be a bit verbose, but I do prefer verbosity and being explicit in this case instead of making assumptions, the clear separation between key and value rules make the entire schema more expressive.
And after all, if we expect all our `required` keys to be filled, we can use the `filled` "shortcut" instead of `value`.

**Comment by solnic** [comment]
@mrbongiolo one of the goals of this library is to **completely remove any ambiguity* from validation logic, hence explicitness and granular rules. From the DSL pov though, we gotta make sure that we preserve clarity and explicitness while not causing too much boilerplate. I think we're very close to achieve that :)

@fran-worley thanks! I'll be around during this week, but focusing mostly on rom 2.0 and major upgrade of rom-repository, but I'll at least try to finish this dsl change and push it

**Comment by backus** [comment]
> This change needs a small tweak though, since we will have required instead of key or attr, we must have a specialized dsl builder object for models, because required in case of a model schema, must produce :attr rules, not :key.

Can you clarify what this would look like? Am I doing something like this

```ruby
Dry::Validations.Schema(Hash) do
  require(:foo) # => key rule
end

```

```ruby
Dry::Validations.Schema(Object) do
  require(:foo) # => attr rule
end

```

where I am specifying, as part of the definition, the object type? (ignore *how* you specify whether the definition is for a Hash vs. an Object in my example. I just care about whether this is defined up front)

Alternatively are we talking about the possibility that my schema decides dynamically whether to use `key` vs. `attr` depending on the object passed into `schema.call(...)`?

**Comment by backus** [comment]
Regarding the overall DSL change I think I am on board if I understand everything correctly. @solnic can you sanity check the table below and tell me whether I am understanding the intended behavior properly?

| DSL                     | Asserts                                                                                                                         |
| :---:                   | :-----------:                                                                                                                   |
| `required(:foo)`        | Provided hash has key `:foo`                                                                                                    |
| `required(:foo).filled` | Provided hash has key `:foo`, `hash[:foo]` is not nil, and `hash[:foo]` is not `empty?` if it is a `Hash`, `Array`, or `String` |
| `optional(:foo)`        | Does not assert anything                                                                                                        |
| `optional(:foo).filled` | Allows hash to omit key `:foo`. Applies behavior of `required(:foo).filled` if `:foo` is present                                |

On a separate note I did like that, while reading over a dry-validation definition, it was obvious
whether it was describing a hash (using `key`) or a PORO (using `attr`). It would be interesting if that benefit could be preserved with something like

```ruby
optional.key(:foo).filled
required.attr(:foo).filled(size?: 1..60)

```

**Comment by solnic** [comment]
> where I am specifying, as part of the definition, the object type? (ignore how you specify whether the definition is for a Hash vs. an Object in my example. I just care about whether this is defined up front)

This will be decided up-front via `Dry::Validation.Schema { .. }` vs `Dry::Validation.Model { .. }`

>  @solnic can you sanity check the table below and tell me whether I am understanding the intended behavior properly?

Yes the table describes it correctly.

> On a separate note I did like that, while reading over a dry-validation definition, it was obvious
whether it was describing a hash (using key) or a PORO (using attr). It would be interesting if that benefit could be preserved with something like

Optional `attr` makes no sense, you are validating a model, it is expected to have all attributes available. We can preserve `attr` DSL and make it behave like `required` and `optional` shouldn't be available in model schemas. BTW I want this to become a separate gem.

**Comment by coop** [comment]
>BTW I want this to become a separate gem.

:+1:

**Comment by coop** [comment]
I'm going to approach this in 4 steps:

1. remove `attr` code path (preserved in https://github.com/dry-rb/dry-validation/tree/attr-dsl)
2. `key` gets deprecated in favor of `required`
3. `value` is added
4. `required` gets deprecated in favor of `filled` which sits on top of `value(:filled?)`

I'm open to any help on this if someone else has been eyeing it off - let me know on the dry-rb gitter channel.
